### ISSUE TITLE
Cannot display `0` after select `0` with options: [0, 1, 2]

### ISSUE THREAD

**Issue by JeOam** [monterail/vue-multiselect#101]
now, I have to translate options from a list of number to a list of string, such as: ['0', '1', '2'].

Is it a bug or I missed something?

version: vue-multiselect@1.0.1

**Comment by shentao** [comment]
Hmm, there actually seems to be a bug when you select number 0 in a single-select. 
Thanks for catching this! I should fix this soon.

**Comment by JeOam** [comment]
@shentao thanks 👍

**Comment by shentao** [comment]
I think I got it fixed. The updated release should be available ~Wednesday.

**Comment by JeOam** [comment]
@shentao Hey shentao, May I ask about [the `v-modal` feature again](https://github.com/monterail/vue-multiselect/issues/63#issuecomment-242901258)? 

Or is there something I can help? I can try to submit a  PR for that. :)

**Comment by shentao** [comment]
This is something that requires some breaking changes, but I guess I will have it this week :)

**Comment by JeOam** [comment]
@shentao Thank you so much :)

**Comment by shentao** [comment]
Finally published and available in v1.1.3!

**Comment by JeOam** [comment]
@shentao Cool~! 👍
