### ISSUE TITLE
Select on tab?

### ISSUE THREAD

**Issue by paulstraw** [monterail/vue-multiselect#102]
Thanks so much for the super well-done library. I did a bit of digging on this, but wasn't able to find anything. I'd like to make it so when a user tabs away from the field, the option they have highlighted is selected.

Have I just missed an option somewhere? If not, would you like me to put together a PR for this functionality?

**Comment by shentao** [comment]
Hey! :) Thanks! Added the functionality just now. I will release the version somewhere around Wednesday, as I want to finally work on the other issues.

**Comment by paulstraw** [comment]
Oh wow! Awesome, thanks so much for the quick response + addition.

**Comment by shentao** [comment]
Finally published and available in v1.1.3!

**Comment by paulstraw** [comment]
Just trie this, but there doesn't seem to be a way to disable this behavior (e.g. for multiselects)? It also selects when using shift-tab, which probably shouldn't be the case.

**Comment by shentao** [comment]
Good catch! Solving the problem of shift+tab should be easy. Disabling or altering the behavior for key events would be a bit problematic though.

**Comment by shentao** [comment]
Sorry it’s so late.
Done in beta.11.

**Comment by stwic** [comment]
This doesn't seem to work anymore and looking at the code, the select function just returns void if the tab key is pressed. What's the status and are there any workarounds to make the tab selection work?

**Comment by SamuelSchwegler** [comment]
I am also searching for a workaround / solution.

**Comment by nicoloko002** [comment]
> I am also searching for a workaround / solution.

try this:

`               $(document).on('keydown', '.multiselect', function(event) {
                  if (event.which === 9) {
                     jQuery.tabNext();
                     var e = $.Event('click');
                     $(event.target).parent().siblings().find('.multiselect__option--highlight:not(.multiselect__option--selected)').trigger(e);
                     event.preventDefault();
                  }
               });`

It uses some JQuery, which I usually try to avoid, but that way worked really well for me =-)
The `jQuery.tabNext();` is from here: https://github.com/marklagendijk/jquery.tabbable

**Comment by SamuelSchwegler** [comment]
> try this:

Thanks! it worked but i had to change `$(document).on('keydown', '.multiselect', function(event) {'` to `$('.multiselect__input').keydown(function (event) {` some how the "tab"-key keydown did only get recognized the first way.

**Comment by hisuwh** [comment]
Is this still supported? It's not working for me?

**Comment by keyurkansara** [comment]
I'm on the latest version and still facing the issue. TAB key is not selecting the multiselect.
