### ISSUE TITLE
unable to prepopulate selection

### ISSUE THREAD

**Issue by z1haze** [monterail/vue-multiselect#103]
Hey! so far I am really enjoying this plugin so thank you! - I have a small issue though but it seems to be consistent with every select plugin ive tried so far.. I am storing a user id as the value in a dropdown, and displaying the username as the label, so when i attempt to edit something that shows the user dropdown, it will put 210 or some user id number in the selected field rather than the username. After inspecting the source, the span inside the selected li is actually the username, i just can't figure out why its using the userid as the label when i explicitly mention for it to use username. Any feedback is appreciated, thanks!

```
<multiselect
                        :selected="serverOwner"
                        :options="users"
                        @update="updateSelected"
                        placeholder="Choose server owner..."
                        key="id"
                        label="username">
                </multiselect>
```

**Comment by z1haze** [comment]
I figured this out by just pulling 2 arrays from my database and setting the selected ones .. it isnt perfect because it still allows the user to reselect the selected ones from the start. if there is a better way please share.

**Comment by shentao** [comment]
There really shouldn’t be any problem with this, unless you’re doing something wrong. How does your `updateSelected` method look like?
Please make sure you follow the docs! http://monterail.github.io/vue-multiselect/#select-object :)
