### ISSUE TITLE
Uncaught TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by PrimozRome** [monterail/vue-multiselect#105]
I am trying to solve this error I keep getting with vue-multiselect 2.0:

vue-multiselect.min.js?6cfa:1 Uncaught TypeError: Cannot read property 'includes' of undefined

I have no idea what that means. 

```
data: function () {
    return {
      localOptions: [{ name: 'Test' }, { name: 'Foo' }, { name: 'Bar' }]
    }
}

```

```
<multiselect
          :options="localOptions"
          :label="name"
          :selected=""
          :searchable="true"
          @update="updateSelected"
          @close="blur">
</multiselect>
```

What am I missing here?

**Comment by shentao** [comment]
You’re not passing anything to the `:selected=""` prop. Either remove it completely or pass there the selected value (which would probably be an empty object). That might be it.
Otherwise, it might be a problem with babel (Includes is an Array method). What browser are you using?

**Comment by PrimozRome** [comment]
I did try removing it but I still get the same error?

I am using Google Chrome with `vue-dev` tools and with `vue-cli - webpack template`

**Comment by PrimozRome** [comment]
I only get it when options is array of objects... If I add for options simple text values and remove `:label` prop then it works.

**Comment by shentao** [comment]
Now I see! You have to pass the `track-by="name"` props. Due to the changes in Vue 2.0, the `key` props has been renamed to `track-by`. It is used to identify objects inside the array. This also means that the names should be unique.

**Comment by PrimozRome** [comment]
Unfortunately still not working, same error ...

My options:
`options: [{name: 'Test 1'}, {name: 'Test 2'}]`

My component settings:
```
<multiselect
          class="form-control textarea" 
          :class="{ 'has-error': showError }"
          :options="options"
          :track-by="name"
          :label="name"
          :placeholder="placeholder" 
          :loading="loading"
          @update="updateSelected"
          @close="blur">
</multiselect>
```

**Comment by shentao** [comment]
If you use the `:` before the prop-name, it is looking for a property in the component. In this case you want to just pass the `name` string. Thus you should do `track-by="name"` instead of `:track-by="name"`.

```
<multiselect
          class="form-control textarea" 
          :class="{ 'has-error': showError }"
          :options="options"
          track-by="name" // change here
          :label="name"
          :placeholder="placeholder" 
          :loading="loading"
          @update="updateSelected"
          @close="blur">
</multiselect>
```

**Comment by PrimozRome** [comment]
Doooh I see my problem.... I have added `track-by` and `label` props as `:label="name" and `:track-by="name"`.

Thanks for your help

**Comment by shentao** [comment]
Exactly! Glad I could help!

**Comment by PrimozRome** [comment]
Do the track-by and label show to the same property inside option object? Because I migh have two times the same name and you said `track-by` needs to be unique. Can I add like `label="name"` and `track-by="id"`?

**Comment by PrimozRome** [comment]
Maybe it is a problem because I first add empty options array `[]`and then update options asynchronously when they are feched from api...

```
  data: function () {
    return {
      loading: false,
      localOptions: []
    }
  }
```

```
  created: function () {
      this.fetchData()
  }
```

```
          <multiselect
            class="form-control textarea" 
            :class="{ 'has-error': showError }"
            :options="localOptions"
            label="name"
            track-by="id"
            :selected="value"
            :searchable="true"
            :placeholder="placeholder" 
            :loading="loading"
            @update="updateSelected"
            @close="blur">
          </multiselect>

```

**Comment by PrimozRome** [comment]
Ok this is so strange... Check this out.

This is working (in my custom component)

```
<multiselect
            class="form-control textarea" 
            :class="{ 'has-error': showError }"
            :options="[{id: '1', name: 'Test 1'}, {id: '2', name: 'Test 2'}]"
            label="name"
            track-by="id"
            :selected="value"
            :searchable="true"
            :placeholder="placeholder" 
            :loading="loading"
            @update="updateSelected"
            @close="blur">
</multiselect>
```

This is working (in my custom component)

```
data: function () {
    return {
      loading: false,
      localOptions: [{id: '1', name: 'Test 1'}, {id: '2', name: 'Test 2'}]
    }
 }
```

```
<multiselect
            class="form-control textarea" 
            :class="{ 'has-error': showError }"
            :options="localOptions"
            label="name"
            track-by="id"
            :selected="value"
            :searchable="true"
            :placeholder="placeholder" 
            :loading="loading"
            @update="updateSelected"
            @close="blur">
</multiselect>
```

This is not working, in my custom component
```
  props: {
    options: {
      type: Array,
      required: true,
      default: []
    }
  },

```

```
<multiselect
            class="form-control textarea" 
            :class="{ 'has-error': showError }"
            :options="options"
            label="name"
            track-by="id"
            :selected="value"
            :searchable="true"
            :placeholder="placeholder" 
            :loading="loading"
            @update="updateSelected"
            @close="blur">
</multiselect>
```

In the above my `options` prop in my custom component gets passed the same value `[{id: '1', name: 'Test 1'}, {id: '2', name: 'Test 2'}]` also seen from this screenshot:

![screen shot 2016-09-14 at 11 56 03](https://cloud.githubusercontent.com/assets/1180467/18507829/432fcac0-7a72-11e6-97ed-76cfc8d0dc45.png)

**Comment by PrimozRome** [comment]
Made some more of the testing. If the `options` which came trough prop is a normal array with strings then it works as well... When it's object, demonstrated above not working. Maybe I am doing something stupidly wrong but I don't think so.

**Comment by shentao** [comment]
Haha :D If those are the cons of coding on the beach, then I think _this is a price I would gladly pay_! 
Anyway, I’m happy the problem is gone. Take care!
