### ISSUE TITLE
Disable keyboard interactions

### ISSUE THREAD

**Issue by nicolas-t** [monterail/vue-multiselect#109]
Hi !

I'm annoyed with the behaviour : `@keydown.delete="removeLastElement()"`

Is there an easy way to disable it? 

best regards, :peach:

**Comment by nicolas-t** [comment]
One cool way of doing so would be to allow the user to pass a custom `onKeydownDelete` function to the component.
 
If no custom `onKeydownDelete` function is provided then we fallback on the actual `removeLastElement` function. 

That way we could easily overwrite the default behaviour.

(of course `onKeydownDelete` is just an example, we can think of a custom event handler for every keyboard interaction)

**Comment by shentao** [comment]
Hey @nicolas-t!
What’s wrong with the current behavior?

We could do that, but this would additionally extend the already complex API.

Callback are generally executed within the parent’s `this` scope, thus it makes it not possible to actually run the `this.removeLastElement()` or any other private function (in cases where you would want to extend the default behavior). 
Even if I would use `.call(this)` on those custom functions, it would just reverse the problem.

I would need some more arguments before adding such functionality :)

**Comment by nicolas-t** [comment]
Maybe we can find something easier.

My usecase:  
I want to hide the `multiselect__tag elements`.
And manually loop over (and display) the `selected` array outside of the vue-multiselect component

I can hide them with css, but the keyboard event `@keydown.delete` is still updating the `selected` array.
So if we can't disable the keyboard event...
**maybe we can add an option to disable the tag display ? :D** 

btw I find confusing that tags can be : 
- custom selected items typed by the user
- the list of selected items displayed before the input

not sure if I'm clear, tell me if you need more explanations :)

**Comment by shentao** [comment]
What about `:block-keys="['Delete']"`? You could also block the `Enter` and `Tab` key.
