### ISSUE TITLE
Less strict Vue.js dependency

### ISSUE THREAD

**Issue by mrtnsn** [monterail/vue-multiselect#11]
As of now this module requires version `1.0.21` of `vue` which is very specific and version `1.0.24` is now out.

Can you update this to a less strict version constraint? E.g. allow for hotfix versions?

**Comment by shentao** [comment]
Yes, I will! My bad!
W dniu czw., 26.05.2016 o 08:55 Christoffer Martinsen <
notifications@github.com> napisał(a):

**Comment by shentao** [comment]
@mrtnsn 
Changed the dependencies. Will bump the version in a moment!
