### ISSUE TITLE
Options Group

### ISSUE THREAD

**Issue by oknoorap** [monterail/vue-multiselect#111]
Is vue-multiselect support options group? I dont' find any example of options group

**Comment by shentao** [comment]
Sadly option groups are not supported right now. Support for it is planned, but I can’t give you a timeline.

**Comment by shentao** [comment]
Almost done! )

**Comment by oknoorap** [comment]
okay great thanks.

**Comment by AlphaB** [comment]
Hi! Any estimates when it's gonna be finished? Can't wait to migrate from selectize.js to this component :)

**Comment by shentao** [comment]
Might be today actually! :D

**Comment by shentao** [comment]
A bit late but its finally done and available in beta-11. :)

**Comment by amer-pinetco** [comment]
how can i get the current group of the sellected item ?
