### ISSUE TITLE
Multiple select - get selected options

### ISSUE THREAD

**Issue by jorgenb** [monterail/vue-multiselect#112]
What would be the best way to extract the selected options for use in a traditional HTML form post with processing backend?

I am passing in my options as an array of objects.

I've set up my Multiselect component like this:

```javascript
<template>
    <div>
        <multiselect
                :options="options"
                :selected="multiValue"
                :multiple="true"
                :searchable="true"
                :close-on-select="false"
                :clear-on-select="false"
                :limit="2"
                @update="updateMultiValue"
                placeholder="Select authors"
                label="name"
                key="id"
                >
        </multiselect>
    </div>
</template>


<script>
    import Multiselect from 'vue-multiselect'
    export default {
        components: { Multiselect },
        props: {
            options: {
                type: Array,
                required: true
            }
        },
        data () {
            return {
                multiValue: []
            }
        },
        computed: {
        },
        methods: {
            updateMultiValue (value) {
                this.multiValue = value
            },
        }
    }
</script>
```

and I call it in my HTML like this:

```html
<v-multiselect
    :options="{{ $data }}" <!-- Laravel blade syntax -->
 >
</v-multiselect>
```

**Comment by shentao** [comment]
Honestly? I have no idea. It’s been already a long time since I had to do with the classic `<form action="doStuff">` way of handling the data. 
Is there no way to use ajax calls instead of form submit?
If not, then I would probably add a hidden `<select multiple>` element and try to move the selected data there and then submit it. But this feels like a hack. :/

Please let me know if you find a working solution! Good luck!

**Comment by jorgenb** [comment]
Thanks. I don't think a `<select>` can be hidden, but I solved it using an hidden input and moving the data there.

**Comment by shentao** [comment]
Glad to hear that!
Yeah, that might be true – didn’t had the opportunity to try it.
