### ISSUE TITLE
Unable to use debounce filter

### ISSUE THREAD

**Issue by StevenBock** [monterail/vue-multiselect#113]
Hello, 

I'm making an AJAX request to a search end point and am finding that I cannot use the debounce filter on the `@search-change` event.  Whenever I try and add the `asyncFind | debounce 500` filter, the asyncFind event is never fired.  Is there a way to debounce search changes? I'm sending a separate AJAX request for each letter, which isn't exactly the most efficient.

Thanks for your help and the wonderful package.

Oh and here's how I'm using the component:

```
            <multi-select
                    :options="searchOptions"
                    :selected="selected"
                    :multiple="false"
                    :local-search="false"
                    :clear-on-select="false"
                    :close-on-select="false"
                    :loading="isLoading"
                    id="ajax"
                    @search-change="asyncFind | debounce 500"
                    @update="asyncUpdate"
                    label="FullName"
                    key="ID"
                    placeholder="Search for something"
        ></multi-select>
```

**Comment by shentao** [comment]
Hey there! This is a problem I recently discovered myself. Sadly, for some reason, Vue is not able to debounce custom events (coming from `this.$emit()`). You can however go around it using `Vue.util.debounce`.

This would look like this then:
```
@search-change="asyncFind"
```

```javascript
methods: {
  asyncFind: Vue.util.debounce(function (searchQuery) {
    this.doSomeAsyncFind(searchQuery)
  }, 500)
}
```

Hope that helps! :)
