### ISSUE TITLE
"Select All" option

### ISSUE THREAD

**Issue by bozhkos** [monterail/vue-multiselect#115]
Is any way to add 'Select all' option in component? I can`t find any solution.

**Comment by shentao** [comment]
You have to do it manually. That should be relatively easy. Just push all the available options to the selected array.
If you want to have this option inside vue-multiselect, you can use the `beforeList` slot to put your custom option in there, that will trigger this behavior.

Hope that helps! :)

**Comment by bozhkos** [comment]
okay, i will try it. 

thanks a lot :)

**Comment by CathyZYF** [comment]
> You have to do it manually. That should be relatively easy. Just push all the available options to the selected array.
> If you want to have this option inside vue-multiselect, you can use the `beforeList` slot to put your custom option in there, that will trigger this behavior.
> 
> Hope that helps! :)

I have tried to put all the options into selected array,but it didn't change the view(no tags show in the input,and no options selected in the dropdown),how can i fix it?
