### ISSUE TITLE
Compile error with browserify

### ISSUE THREAD

**Issue by jbardnz** [monterail/vue-multiselect#12]
Hi,

Not sure if this is an issue just effecting me or a more general issue. 

I am getting a browserfiy issue after adding this to my project:

![image](https://cloud.githubusercontent.com/assets/1628446/15571666/40f7ed0c-2390-11e6-9bc9-dd7ba8931e3e.png)

**Comment by shentao** [comment]
Hey @jbardnz! 
Someone on reddit already noticed the problem and it is fixed in the latest commit.
I will bump the version in a moment. :)

**Comment by jbardnz** [comment]
Thanks so much for the super quick reply :)

**Comment by shentao** [comment]
No problem.
Fixed in v0.1.6

**Comment by jbardnz** [comment]
Hmm, I now seem to get a different compile error:

![image](https://cloud.githubusercontent.com/assets/1628446/15572868/7759c2e2-2397-11e6-95a3-1bc1f5ad35e6.png)

**Comment by shentao** [comment]
Ouch. This might be something sass related. I’m about to get rid of it in the multiselect.vue file. This might solve the problem. On it right now!
Thanks for reporting!
Can you also provide some of the configuration you’re using? Any preprocessors?

**Comment by jbardnz** [comment]
I'm using [Laravel Elixir](https://github.com/laravel/elixir) to compile my JS assets.

I am also running Sass for all my styling and in my own Vue components so it should have all the dependencies it needs to compile. Apart from that it is just a standard gulp setup.

**Comment by shentao** [comment]
@jbardnz 
Got rid of sass anyway (thus probably removing the line that throw the error). Give it a try now. :)

**Comment by jbardnz** [comment]
Thanks man!

That has cleared the Sass issue - but it has caused a different issue:

![image](https://cloud.githubusercontent.com/assets/1628446/15575385/abc6a28e-23a6-11e6-86ff-3d26f5ecf22a.png)

**Comment by shentao** [comment]
Damn! Could you try reinstalling/updating babel-preset-stage-2? And/or removing node_modules and running `npm install` again?
`pointerMixin.js` doesn’t really use any Babel requiring functionality.

This might be a problem with laravel-elixir.
https://github.com/laravel/elixir/issues/354

I will investigate it later, but probably not today.

**Comment by jbardnz** [comment]
Hmm potentially it is just a Laravel Elixir issue then. I will investigate the solutions suggested on that thread tomorrow and post back.

**Comment by shentao** [comment]
Thanks!

**Comment by jpmurray** [comment]
I had the same trouble, and (mind you I'm in no way knowledgable in all of this, so I don't know what can be done to fix it really), but following the thread in the above mentioned elixir issue, I removed the `.babelrc` file at the root of vue-multiselect folder in `node_modules` and it works perfectly fine now!

**Comment by shentao** [comment]
That’s interesting! Thanks @jpmurray. I will check it myself and add it to `.npmignore` if it doesn’t break anything for webpack based imports.

**Comment by shentao** [comment]
@jpmurray @jbardnz `.babelrc` file removed. This should fix the problem. If not, please reopen and let me know! :) Have a nice weekend!

**Comment by jbardnz** [comment]
@shentao I have just tested and can confirm that fixes the issue for me! Thanks so much for fixing this.

**Comment by shentao** [comment]
Awww yeah! 👯 Glad to hear that!
