### ISSUE TITLE
npm release is 1.1.4 but latest edition on Git is 1.1.3

### ISSUE THREAD

**Issue by SirLamer** [monterail/vue-multiselect#122]
Per the subject...

Having read the issues page, I suspect that 1.1.4 on NPM is a beta build not meant for Vue 1.0 users.

**Comment by shentao** [comment]
No worries, that was fixed shortly after the accidental publish. 
Sorry, I just forgot to create a GitHub release for v1.1.4. Thanks for reminding me!

Will do it in a moment, after I finish an update to the 2.0 beta (v-model support).

Cheers!

**Comment by shentao** [comment]
@SirLamer https://github.com/monterail/vue-multiselect/releases/tag/v1.1.4
