### ISSUE TITLE
Searchable multiselect inserts "search" value in form response

### ISSUE THREAD

**Issue by SirLamer** [monterail/vue-multiselect#125]
The searchable feature in vue-multiselect relies on an input field with name "search". Because of this, the value in the search field is returned as part of a form submission if used inside a form. Yes there are workarounds and all kinds of things one could do, but for the sake of simplicity it would be good to not have to fuss around this. One example is a form which uses both multiselect and normal input fields, in which case it might be desirable to not rely on Vue for the form submission.

This is very loosely related, but below is an example Vue component I am working on as a form element, which relies on a hidden form input in order to transmit the correct/intended value (usually an ID number). The search field value of the last vue-multiselect instance in my form also sends the search field result. For now I simply don't make use of the form value name "search" in my controller to avoid an issue.

``` html
<template>
    <div class="form-group drop-down">
        <label v-if="title" :for="randomId">{{ title }}</label>
        <multiselect
                :options="options"
                :searchable="searchable"
                :allow-empty="allowEmpty"
                :track-by="trackBy"
                :label="label"
                placeholder="Select..."
                :show-labels="true"
                :id="randomId"
                :value="value"
                v-on:input="onInput"
        ></multiselect>
        <input type="hidden" :name="formName" v-if="formName" :value="value ? value[trackBy] : ''">
    </div>
</template>

<script>
    import Multiselect from 'vue-multiselect/lib/Multiselect.vue';

    export default {
        components: { Multiselect },

        data () {
            return {
                randomId: 'input-' + Math.random()
            }
        },

        props: {
            options: {
                type: Array,
                default: function() {
                    return [];
                }
            },
            value: {
                default: null
            },
            placeholder: {
                type: String,
                default: 'Select...'
            },
            searchable: {
                type: Boolean,
                default: true
            },
            allowEmpty: {
                type: Boolean,
                default: true
            },
            trackBy: {
                type: String,
                default: 'id'
            },
            label: {
                type: String,
                default: 'name'
            },
            title: {
                type: String,
                default: null
            },
            formName: {
                type: String,
                default: null
            }
        },

        methods: {
            onInput(event) {
                this.$emit('input', event);
            }
        }
    };
</script>
```

Here is how it is used:

``` html
    <drop-down
        v-model="role"
        :options='{!! $roles !!}'
        form-name="role_id"
        title="Role"
        label="display_name"
    ></drop-down>
```

**Comment by shentao** [comment]
Nice catch. That’s actually easy to solve. I will just need to remove the name attribute of the input. :)
Thanks!

**Comment by SirLamer** [comment]
Sounds good. Oftentimes I'd do a PR but i wasn't sure what the point of it was.

**Comment by bpiviqd** [comment]
Great, I need the hidden input type with "id" as its name not "search" like the current one

**Comment by shentao** [comment]
Beta.14 released and should fix this problem. Sorry you had to wait so long :(
Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.
