### ISSUE TITLE
debounce

### ISSUE THREAD

**Issue by yuu2lee4** [monterail/vue-multiselect#127]
wishing add debounce prop to reduce net request

**Comment by shentao** [comment]
You already have debounce in Vue. Just debounce the function that is handling the search-change event.
As for Vue 2.0 beta – you will need you custom debounce implementation.

**Comment by yuu2lee4** [comment]
@shentao   it seems like debounce filter cant work with search-change event

**Comment by shentao** [comment]
You have to do it a bit different:
```
methods: {
  searchChangeHandler: Vue.options.filters.debounce(query => {
    ...do stuff with the search query
  }, 500)
}
```
Vue has to be imported.
Then you can just do:
`@search-change="searchChangeHandler"`

Let me know if this helps. :)

**Comment by yuu2lee4** [comment]
3ks  i already use lodash  to do this

**Comment by yuu2lee4** [comment]
@shentao   how to bind 'this' to current vue instance

**Comment by shentao** [comment]
You mean, inside the callback? Sorry, forgot that you shouldn't use the arrow function when doing denounce. Then it will be properly bound to this.

**Comment by yuu2lee4** [comment]
@shentao   thanks so much

**Comment by shentao** [comment]
No problem! ;)

**Comment by gustavobissolli** [comment]
Anyone knows why I have the following problem?

```
methods: {
            asyncFind: debounce((query) => {
                this.isLoading = true

                getAll({ identity: query })
                    .then(response => {
                        window.console.log(response)
                        this.leadOptions = response.data
                        this.isLoading = false
                    })
            }, 500),
}
```

Erro: `Cannot set property 'isLoading' of undefined`

I can't access `this`!

**Comment by gustavobissolli** [comment]
I've found a solution but didn't understand why!
Importing only the debound method instead of the entire lodash library doesn't work!

I had to use like:

```
import _ form 'lodash'
...
methods: {
            asyncFind: _.debounce((query) => {
                this.isLoading = true

                getAll({ identity: query })
                    .then(response => {
                        window.console.log(response)
                        this.leadOptions = response.data
                        this.isLoading = false
                    })
            }, 500),
}
```

**Comment by damienroche** [comment]
@parth115 by setting `:internal-search="false"` I was able to solve the `noResult` error message
