### ISSUE TITLE
option select on tab

### ISSUE THREAD

**Issue by mathiasfn** [monterail/vue-multiselect#128]
Is it possible to disable selection when pressing tab? i'd like my users to be able to tab through a form without selecting options from my dropdowns :)

**Comment by shentao** [comment]
This was a recent addition, from a feature request. Will see how to make it work for both of you. :)

**Comment by mathiasEasyInspect** [comment]
If you could make a setting like :select-on-tab:boolean that would be nice :)

**Comment by shentao** [comment]
Will do! :)

**Comment by aarobc** [comment]
Not sure if this has been implemented on the main branch, but v2 branch still needs this fix. without the ability to disable it, the user has no way to tab between the selects.
