### ISSUE TITLE
Module build failed: SyntaxError: 'with' in strict mode

### ISSUE THREAD

**Issue by ptitkiller** [monterail/vue-multiselect#130]
i use **vue-multiselect** v2.0.0-beta.9. 
looks like it is no problem to usestrict.

{ [Error: ./~/vue-multiselect/lib/vue-multiselect.min.js
Module build failed: SyntaxError: 'with' in strict mode (1:29119)
![image](https://cloud.githubusercontent.com/assets/9286322/19472728/995ea024-9552-11e6-8051-bbe005537a04.png)

**Comment by shentao** [comment]
This is a common problem, with no known solution yet.
A workaround this will be using `import Multiselect from 'vue-multiselect/lib/Multiselect.vue'`

**Comment by ptitkiller** [comment]
thanks @shentao .
