### ISSUE TITLE
Error when value == null

### ISSUE THREAD

**Issue by mathiasEasyInspect** [monterail/vue-multiselect#131]
So, either im retarded or this is some sort of bug.
But everytime i deselect an option, the dropdown gets the "null" value and i get this error:

Error when evaluating expression "function (){var t=this;return this.key?this.multiple?this.value.map(function(e){return e[t.key]}):this.value[this.key]:this.value}": TypeError: Cannot read property 'name' of null

Any thoughts?

**Comment by shentao** [comment]
How do you handle the deselecting? How does you `@update` handler looks like?

**Comment by mathiasEasyInspect** [comment]
child dropdown: 
`<log-dropdown
                                        :options="users"
                                        :searchable="true"
                                        @open="selectFormKey('pilot_id')"
                                        @update="addIdToForm"
                                        placeholder="Vælg en"
                                        label="name"
                                        key="name">
</log-dropdown>`

parent methods being used: 
`selectFormKey(key){
            this.currentFormKey = key;
        },
        addIdToForm(value){
            if(!value){
                delete this.form[this.currentFormKey];
                return false;
            }
            value.id ? this.form[this.currentFormKey] = value.id : delete this.form[this.currentFormKey];
        }`

**Comment by shentao** [comment]
Could you format the code properly? ;)

**Comment by mathiasEasyInspect** [comment]
i updated my previous comment :)

**Comment by shentao** [comment]
Which version of Multiselect is it?
This is quite weird. It looks like it tries to get the name of the value when it is null. But this shouldn’t happen inside Multiselect. Does it happen without the addIdToForm function?

**Comment by mathiasEasyInspect** [comment]
version: v1.1.3

looking like this i still get the error
```html
<log-dropdown
                                        :options="users"
                                        :searchable="true"
                                        placeholder="Vælg en"
                                        label="name"
                                        key="name"
                                        ></log-dropdown>
```

**Comment by shentao** [comment]
How does the data you pass to the `:options` look like? 
Could you provide a sample of the users array?

**Comment by mathiasEasyInspect** [comment]
```json
[
    {
        "id": "21dee85c-608c-47ca-8574-9998b8e",
        "name": "peter"
    }
]
```

**Comment by shentao** [comment]
Wouldn’t it be better to use the `id` as `key`? Also there is v1.1.4 available.

**Comment by mathiasEasyInspect** [comment]
Im not entirely sure what key is used for, i simply copied some example.
Do you think that could be it?

**Comment by mathiasEasyInspect** [comment]
I just tried changing the key to "id" but it doesn't seem to help

**Comment by shentao** [comment]
Key is used for identifying the options if those are objects. Keys have to be unique.
Are you – by some change – referring to the private value of Multiselect?

**Comment by mathiasEasyInspect** [comment]
I dont believe i am :/

**Comment by shentao** [comment]
Try to trace where does the component look for `.name` when it is `null`.

**Comment by mathiasEasyInspect** [comment]
Im not sure if i catch what you mean.
But im pretty sure it's on @update

**Comment by shentao** [comment]
Closing due to no update.
