### ISSUE TITLE
force dropdown to close

### ISSUE THREAD

**Issue by mathiasEasyInspect** [monterail/vue-multiselect#132]
I have made a button in my "noResults" slot which fires a method when clicked, in that method i'd like to close the dropdown afterwards, how can this be done? :)

**Comment by shentao** [comment]
This is a problem of the compilation scope. The slots are compiled using your parent scope, so they don’t have access to the Multiselect instance.
I would try changing the current focus to an element outside of Multiselect (this will force the dropdown to close).

**Comment by mathiasEasyInspect** [comment]
Alright i'll do that, thanks for the response :)

**Comment by shentao** [comment]
No problem :)
