### ISSUE TITLE
Suggestion: When the form element is near the bottom of the page, the select field should extend up

### ISSUE THREAD

**Issue by SirLamer** [monterail/vue-multiselect#136]
Per the subject...

This is just to resolve a usability issue related to this form element being at the bottom of the page. Whenever possible, the form should not render down below the existing bottom of the page, so causing the page length to temporarily extend to accommodate this and requiring the user to scroll down only after selecting the field element to expose the select list.

In cases where the above does not apply the list should appear underneath as it does now.

In the edge-case scenario where the form list will extend both over the top or bottom of the page in either case, then it should just extend down.

I'm not sure how straightforward this is to pull off and is outside of my experience level to affect with a PR. For what it's worth, the jQuery-based "select2" does this fairly well.

Package remains super awesome with or without this feature. I am building some form elements around this vue-multiselect package, I will likely publish them later and after your package is out of beta to avoid conflicts from changes.

**Comment by shentao** [comment]
Been thinking about this and I think I could implement this making the multiselect extend above the field when there is not enough space below the input. This is how select2 works now and it should be pretty straightforward.

Thanks for the suggestion!

Nice to hear that! Let me know when you publish them! Would really like to see it.

**Comment by dudesweet100** [comment]
select2 - you mean with vue2 version? I am using vue2 version of this library, but still the dropdown shows at the bottom.

**Comment by skechele** [comment]
Sehr geehrte Damen und Herren,

ich bin bis zum 09. Januar 2017 nicht im Büro.
Ich werde Ihre E-Mails ab dem 10. Januar 2017 beantworten.

In wirklich dringenden Fällen wenden Sie sich bitte per E-Mail oder Telefon an uns.
E-Mail (mit dem Betreff „Notfall“) an info@deitron.de. 
Telefon: 0731 / 938060. Sie werden per Rufumleitung an einen Techniker verbunden.

Freundliche Grüße,
Stefan Kechele

**Comment by shentao** [comment]
Implemented! Will be available in the next release! :)
