### ISSUE TITLE
Invalid prop: type check failed for prop "key".

### ISSUE THREAD

**Issue by callumacrae** [monterail/vue-multiselect#139]
The basic example in the documentation doesn't work for me: https://github.com/monterail/vue-multiselect#install--basic-usage

```
[Vue warn]: Invalid prop: type check failed for prop "key". Expected String, got Boolean. 
(found in component <multiselect>)
[Vue warn]: Invalid prop: type check failed for prop "label". Expected String, got Boolean. 
(found in component <multiselect>)
vue-multiselect.min.js?6cfa:1Uncaught TypeError: this.$options.filters.filterBy is not a function
```

Not sure what else is needed. I'm assuming it's specific to me as there are no other issues about it, but I can't see anything wrong…

**Comment by callumacrae** [comment]
Completely forgot I'm using Vue 2 on this project. Sorry, I see you're already working on it!

**Comment by shentao** [comment]
You can already use the beta version. `npm install vue-multiselect@next`.

**Comment by callumacrae** [comment]
Beta version is working great, thank you!

**Comment by shentao** [comment]
Happy to hear that! :)

**Comment by yusupprog** [comment]
Great component!Really pleasure to work with

**Comment by shentao** [comment]
Thank you @yusupprog :)
I just feel bad about prolonging the release of stable 2.0 version.

**Comment by HankBrown** [comment]
I am sorry but I have this question too, and the answer makes no sense to me.

**Comment by shentao** [comment]
@HankBrown Use `npm install vue-multiselect@next` to install the version that supports Vue 2.0+
