### ISSUE TITLE
Issue with Placeholder in vue-multiselect 2.0.0-beta.10

### ISSUE THREAD

**Issue by cmmize** [monterail/vue-multiselect#142]
First off Thank You for all the work you put into this!
I've been unable to get a placeholder to show in vue 2.0 version.  I've put a test project here so you can see.  I've tried both as an attribute and props (example is attr).

https://cmmize@bitbucket.org/cmmize/issue-with-placeholder-in-vue-multiselect-2.0.0-beta.10.git

Thanks for your help.

**Comment by shentao** [comment]
Will look into it tomorrow! :)

**Comment by SirLamer** [comment]
In your component DropDown, you pass to Multiselect a static string to the "placeholder" attribute. You need to handle "placeholder" as a prop within your DropDown component.

See: https://cmmize@bitbucket.org/cmmize/issue-with-placeholder-in-vue-multiselect-2.0.0-beta.10/src/152537eb0da79b149aef4cd09d18a4f2f07e2623/src/components/DropDown.vue?at=master&fileviewer=file-view-default#DropDown.vue-11

**Comment by shentao** [comment]
Just like @SirLamer said, you have to additionally create and pass the placeholder prop inside Dropdown component.

Thanks Sir! 👍

**Comment by cmmize** [comment]
Thanks for the quick reply.  I have tried as a prop(mentioned in original question) and it still does not work,  would you like me to post that project or can you confirm it works with example?
