### ISSUE TITLE
Componente Height

### ISSUE THREAD

**Issue by xereda** [monterail/vue-multiselect#143]
What is the simplest way to change the size of the component's height? Must adapt to the default CSS Bulma, but only the height. The rest can stay as it is, which is excellent.

I want to do it in the least invasive way possible. My concern is not without disturbing the natural behavior of the component.

Thanks a lot for the help.

**Comment by shentao** [comment]
That would be using CSS. You will have to override some css classes and set the correct `:option-height`.

**Comment by xereda** [comment]
What are the classes?
Other question: I have to increase the left margin of the text / value? How would I do this without causing problems in the standard structure?

**Comment by xereda** [comment]
I need to do this: Congratulations amazing job. You did an excellent component. Very good!

**Comment by shentao** [comment]
Well, thanks! :)
Take a look at the classes in this file: https://github.com/monterail/vue-multiselect/blob/master/src/Multiselect.vue
You can modify them at will.

**Comment by xereda** [comment]
@shentao, what it's ":option-height"? Css propertie? I am not find this.

**Comment by xereda** [comment]
I'm trying to override the classes of your component, but it has no effect.

**Comment by xereda** [comment]
My need is to increase the "z-index" (the bulma's footer, it's over.), Decrease the height of the field and increase the left margin of the content text.

I tried setting the css classes inside my <style> tag, but apparently there was no effect.

What should be done to work?

Thank you very much.

**Comment by shentao** [comment]
`:option-height` is for handling the arrow navigation. It is used to calculate the viewport offset. 

Which class do you override?
Probably you have to look on the classes inside multiselect and override the specific classes.
