### ISSUE TITLE
Issue with placeholder showing in  vue 2.0

### ISSUE THREAD

**Issue by cmmize** [monterail/vue-multiselect#145]
Update to a closed question:
I've been unable to get a placeholder to show in vue 2.0 using vue-multiselect-2.0.0-beta.10 version. I've put an updated test project here so you can see, which is using props (previous question on same subject suggested using props for placeholder instead of attribute).  This still does not work. 

https://cmmize@bitbucket.org/cmmize/issue-with-placeholder-in-vue-multiselect-2.0.0-beta.10.git

Thanks for your help.

**Comment by shentao** [comment]
Thanks! I will try to investigate this soon.

**Comment by shentao** [comment]
First, please remove the `.sync` suffix. It’s deprecated in Vue 2.0.
Also, you’re passing `value` prop to the dropDown component, but inside, you’re expecting a `selected` prop. 

Made a fix for the placeholder in case the select is `multiple` and not `searchable`. Should be released soon. Thanks!

**Comment by cmmize** [comment]
Hi shentao,

Is there a release I can get with fix for the placeholder in case the select is multiple and not searchable you mentioned above?  Thanks a bunch.
