### ISSUE TITLE
Partials 

### ISSUE THREAD

**Issue by vanderlin** [monterail/vue-multiselect#146]
with Vue2.0 not sure how this feature is implemented can someone give an example?

http://monterail.github.io/vue-multiselect/#partials

**Comment by shentao** [comment]
> Instead of Vue.partial for custom option templates you can use a custom render function.

Check out this: 
https://github.com/monterail/vue-multiselect/blob/2.0/src/Multiselect.vue#L189
and this:
https://github.com/monterail/vue-multiselect/blob/2.0/src/MultiselectOption.js
