### ISSUE TITLE
I've to click the gray arrow to open the menu in IOS

### ISSUE THREAD

**Issue by Abdelrahman3D** [monterail/vue-multiselect#147]
I love this very clean package  and I love that you used BEM conventions but i have a little issue when i used it on mobile.
I've tested the site on IOS Safari and IOS FireFox, and here is what I've got. The only way to open the menu is by clicking the gray arrow and this is not good behavior since users expected to click on the menu itself to open it. by the way it works fine on IOS Chrome, Android FireFox and Android Chrome.

**Comment by Abdelrahman3D** [comment]
I've fixed the problem using css to make the arrow take the hole width, It's a kind of hack but it worked fine for me 
```
.multiselect__select {
    z-index: 10 !important;
    width: 100% !important;
}
.multiselect--active .multiselect__select{
    transform: none !important;
}
.multiselect__select:before {
    right: calc(-50% + 10px) !important;
}
```

**Comment by shentao** [comment]
I will try to improve this before the 2.0 stable release. Thanks!
