### ISSUE TITLE
Object.label is not set as default when using Object options

### ISSUE THREAD

**Issue by evanb2** [monterail/vue-multiselect#151]
I'm passing in an Array of Objects to the options prop with keys "name" and "label" and I still have to explicitly say `label="label"`

**Comment by shentao** [comment]
Sadly there is no default for the `label` prop as it’s existence is used to determine the `getOptionLabel` strategy. Similarly same with the `key` (1.0) / `track-by` (2.0) props.

**Comment by evanb2** [comment]
Oh I see, I was confused by this comment:

    /**
       * Array of available options: Objects, Strings or Integers.
       * If array of objects, visible label will default to option.label.
       * If `label` prop is passed, label will equal option['label']
       * @type {Array}
       */

**Comment by shentao** [comment]
Och crap! Forgot to update the docs and readme with this change. Sorry about that! Big thanks for catching this! :)
