### ISSUE TITLE
Vue 2 issue / doubt

### ISSUE THREAD

**Issue by viraj-khatavkar** [monterail/vue-multiselect#154]
Hey @shentao how do I get reactivity in place for Vue 2 version?

I have a json array of options, something like:

```javascript
{
    [
        {
            "name":"master"
        },
        {
            "name":"production"
        }
    ]
}
```

In my Vue component's props, I have an option which is to be selected:

```javascript
selectedBranch: {
    name: this.server.meta.deployment_branch
},
```

I initially select the option as follows:

```html
<multiselect @input="updateDeploymentBranch" :options="branches" :value="selectedBranch"
```

But, when I update the `name` key of `selectedBranch` it doesn't get reflected in the UI

**Comment by shentao** [comment]
You might want to add the `track-by="name"` and `label="name"` props. This might help.

**Comment by viraj-khatavkar** [comment]
@shentao Already there :(

**Comment by viraj-khatavkar** [comment]
At first, the desired option is selected properly. But, once I change the data property of `selectedBranch` the reactivity is not achieved in UI

**Comment by shentao** [comment]
Where does the `this.server.meta.deployment_branch` come from? How do you assign it to name later on?

**Comment by viraj-khatavkar** [comment]
The `server` prop is already there from the start. The branch gets selected the first time.

If a selected server is updated on a later time, then the branch should also change according to server..

**Comment by shentao** [comment]
Yeah, but how do you track the changes? Is this a web socket connection?

**Comment by viraj-khatavkar** [comment]
It is an another dropdown that's it..

**Comment by shentao** [comment]
It should work without a problem if you’re doing a regular assigning. Could you provide a JSFiddle? Then maybe I could help.

**Comment by amitavroy** [comment]
having the same problem. I have an array of objects for the drop down called tags which is going in options property. 

Then I have selected property as selectedTags. But when I pre populate the selectedTags on edit screen, those tags are not automatically visible.

I can see the demo working, but for me on Vue2 it's not.
