### ISSUE TITLE
How to register it without require or import?

### ISSUE THREAD

**Issue by cve** [monterail/vue-multiselect#155]
Hi,

I would like to use this plugin at legacy page where I don't have webpack or require, so how can I register multiselect like:

````javascript
new Vue({
  el: '#app',
  components: {
    'multiselect': <<< ??? HOW TO REGISTER IT HERE >>>
  },
  data: {
    selected: null,
    options: ['list', 'of', 'options']
  },
  methods: {
    updateSelected (newSelected) {
      this.selected = newSelected
    }
  }
})
````

**Comment by shentao** [comment]
Should be available as `window.Multiselect.default` when you add it with just a `<script>` tag.

**Comment by cve** [comment]
Thanks for fast response :)

I made http://codepen.io/cve/pen/qqpZrv with demonstration this situation and in the console I see 

````Multiselect is not defined````

**Comment by shentao** [comment]
Sorry, my bad! Should be `window.VueMultiselect.default` :)

**Comment by cve** [comment]
Ok, I've updated code snippet, but now in the console I see:

`
 Invalid prop: type check failed for prop "key". Expected String, got Boolean. (found in component <multiselect>)
`

**Comment by cve** [comment]
Sorry, I miss #139 Thanks for help :)

**Comment by antholord** [comment]
This info should be more accessible on the official page. Took me a while to find it.
