### ISSUE TITLE
@next: select breaks if selecting same item

### ISSUE THREAD

**Issue by callumacrae** [monterail/vue-multiselect#158]
I'm using Vue 2.0 and vue-multiselect@next.

I'm using vue-multiselect for a language picker:

```vue
<template>
  <multiselect
    v-if="currentLocale"
    v-model="currentLocale"
    :options="locales"
    @input="localeChanged"
    label="name"
    track-by="code">
  </multiselect>
</template>

<script>
  import Multiselect from 'vue-multiselect';

  export default {
    data: () => ({
      currentLocale: undefined,
      locales: config.locales,
    }),
    mounted() {
      this.currentLocale = config.locale;
    },
    methods: {
      localeChanged() {
        console.log(this.currentLocale); // This is undefined
      },
    },
    components: {
      Multiselect,
    },
  };
</script>
```

It works when fine when changing the language, but if selecting the same language, `currentLocale` is set to `null`. `localeChanged` is still called so I've been to work around it, but it's probably still a bug.

**Comment by shentao** [comment]
You need to add the `:allow-empty="false"` prop. Otherwise selecting the same option results in deselecting it.

See http://monterail.github.io/vue-multiselect/#select-object for an example.

Let me know if this helps! :)

**Comment by callumacrae** [comment]
Whoops, that's better :)
