### ISSUE TITLE
How to intergrate with fastclick 

### ISSUE THREAD

**Issue by KeroVieux** [monterail/vue-multiselect#159]
As my test project , the vue-multiselect could not work with the fastclick.js , I was supposed that fastclick.js is useful in the mobile app .
However , I think that's a way to do it , like only the links or buttons work with fastclick.js except for vue-multiselect , perhaps there is a mobile option have been set on vue-multiselect ?

**Comment by shentao** [comment]
It should work without fastclick.js. 
I will look into it.

**Comment by KeroVieux** [comment]
@shentao Thx ! I know it's work so well on PC , but the 300ms delay is horrible on devices so that need the fastclick.js , I was really have no idea for it , even thought I have add the class="needsclick" to the node ...

**Comment by maddesigns** [comment]
try using `touch-action: manipulation;` in CSS, this will remove the click delay in most browser. http://caniuse.com/#feat=css-touch-action

**Comment by shentao** [comment]
Yeah, this might be useful @KeroVieux https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

Adding 
```
<meta name="viewport" content="width=device-width">
``` 
might fix your problem.

**Comment by KeroVieux** [comment]
Hey , everyone who had came in here , It was exact my bad , when you set up the meta as 
`<meta name="viewport" content="width=device-width">`
All the delay of clicked would be dismiss .
