### ISSUE TITLE
How to implement CustomLabel?

### ISSUE THREAD

**Issue by muchacho-diesel** [monterail/vue-multiselect#162]
How can I implement the CustomLabel function to create own labels directly at the input field like the example at the homepage (http://monterail.github.io/vue-multiselect/)? Because I can't find any explanation with source code in the documentation.

JsFiddle:
https://jsfiddle.net/1zecg8yc/11/

Used versions:
  - vue.js: 2.1.4
  - vue-multiselect: 2.0.0-beta.10

**Comment by shentao** [comment]
Depends what you want to accomplish :) 

You can have either custom label or custom option template (like the example with images in the docs).

Custom label:
`:custom-label="customLabel"`

```
methods: {
  customLabel (option) {
    return `${option.id}: ${option.title} has color: ${option.color}`
  }
}
```
Custom option template:
https://jsfiddle.net/1zecg8yc/12/
