### ISSUE TITLE
[Question] Allow extraneous values

### ISSUE THREAD

**Issue by silvestreh** [monterail/vue-multiselect#163]
First off I'd like to thank and congratulate everyone involved in _vue-multiselect_. It's being great to work with so far!

On to my question… Is there a way to set a value that's not in the `options` array? I'm listing health insurance companies, but since there could be companies that I'm not aware of, I need the user to be able to set whatever string they want.

BTW, I'm running `2.0.0-beta.10`.

**Comment by shentao** [comment]
Hey thanks! :)

I guess you could use the *tagging* feature. It can be used with single selects as well.
http://monterail.github.io/vue-multiselect/#tagging

Hope that helps!
