### ISSUE TITLE
Feature request: Debounce

### ISSUE THREAD

**Issue by smith64fx** [monterail/vue-multiselect#166]
Hi there,
For my async search I need a denounce timer, otherwise I make a search on each key input.

Is there any possibility ?

Thanks! 

Smith

**Comment by shentao** [comment]
Depending on which version of Vue are you running.
If Vue 1.x read #127 
If Vue 2.x basically the same but you have to provide a debounce function, for example from lodash. Using it should be the same as in #127

You can also look at #113 

I hope that helps!

**Comment by smith64fx** [comment]
@shentao Lightning-fast answer! And very good one. I made it with lodash finally :) Thanks!

**Comment by shentao** [comment]
Happy to hear that! :)
