### ISSUE TITLE
@next: Broken in Vue 2.1.5

### ISSUE THREAD

**Issue by callumacrae** [monterail/vue-multiselect#167]
I'm getting this fantastic, highly informative error when using the latest version of vue-multiselect with the latest version of vue:

<img width="1279" alt="screen shot 2016-12-13 at 10 46 13" src="https://cloud.githubusercontent.com/assets/472830/21137444/74972202-c121-11e6-9d07-d25b16c21458.png">

I hope that means more to you than it does to me!

Here's the release notes: https://github.com/vuejs/vue/releases/tag/v2.1.5

It works fine in 2.1.4.

Versions:

```
├── vue@2.1.5
├── vue-multiselect@2.0.0-beta.10
└── vue-template-compiler@2.1.5
```

**Comment by XiaoxiaoPu** [comment]
It was caused by a breaking change in `vue@2.1.5`. New dist release is required.

See https://github.com/ElemeFE/element/issues/1706 .

**Comment by callumacrae** [comment]
@XiaoxiaoPu: Has anyone opened an issue on the Vue tracker?

cc @yyx990803

**Comment by XiaoxiaoPu** [comment]
@callumacrae It's **NOT** a bug, just need rebuild.

**Comment by callumacrae** [comment]
Ah right, sorry! Misunderstood.

**Comment by shentao** [comment]
Will try to do it today. Thanks! :)

**Comment by callumacrae** [comment]
@shentao: When will you be able to do this? My app is broken on production, and Vue won't let me roll it back.

**Comment by yyx990803** [comment]
@callumacrae FYI you can clone this project, bump the deps and build it yourself if it's urgent.

**Comment by callumacrae** [comment]
I think I worked out what was happened: I had locked Vue to 2.1.4, and an update for this library was pushed earlier (I think). The new version relies on 2.1.5, and breaks when ran using 2.1.4. I didn't notice it had been updated.

Basically: beta 10 doesn't work with Vue 2.1.5, but beta 11 doesn't work with Vue 2.1.4, so locking only Vue caused my website to break again.

Sorry for confusion!

**Comment by shentao** [comment]
Ouch, wasn’t aware that there might be such complications!
The beta.11 was rebuilt with the newest 2.1.6 version of Vue and vue-loader.
It also introduced option groups! :)
