### ISSUE TITLE
stopropagation enter and @input bug

### ISSUE THREAD

**Issue by nunob87** [monterail/vue-multiselect#169]
vue 2,
How can I stop the event keydown enter to not send the form??

If I use the :input elements do not disappear from the list with :hide-selected = "true"
@input="onSelectTypes" -> Does not call function

thank you

**Comment by shentao** [comment]
That’s on my side I guess. I will add `.prevent` to the event handler. Right now there is just `.stop`.

What kind of options do you have? An array of objects? Remember that you always have to pass the `track-by` and `label`, so that multiselect can recognize the options and then hide them if needed.

**Comment by nunob87** [comment]
`<multiselect :value="tipos_" :options="tipos" @input="onSelectTipos" :multiple="true" label="nome" :track-by="id" placeholder="" select-label="" deselect-label="" :close-on-select="false" :clear-on-select="true" :searchable="true" :allow-empty="true" :hide-selected="true" @close="onTouch"></multiselect>

 onSelectTipos (value) {
        console.log(value)
        this.tipos_ = value
      },

`  -> Do not hide the selected options

package.json
"vue": "^2.0.3"
    "vuex": "^2.0.0",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.1.1",
    "vuex-router-sync": "4.0.1",
    "vue-multiselect": "2.0.0-beta.11"


thank you

**Comment by nunob87** [comment]
When added to prevent warns

**Comment by nunob87** [comment]
I need to solve 3 problems in my app:

1 - Prevent enter from submitting form

2 - I select 3 elements, and I want to delete the first one selected, and always delete the last one

3 - The selected options are not hiding

**My code:**
https://dev.bill.pt
email: **elcsat@hotmail.com**
password: **portugal**

**example**
https://dev.bill.pt/itens/criar

thank you

**Comment by shentao** [comment]
Already fixed
