### ISSUE TITLE
Ability to template the selection

### ISSUE THREAD

**Issue by iang0ld** [monterail/vue-multiselect#170]
We need to template multiline selections as well as the options. Can this be acheived, maybe through the selected hook?

**Comment by shentao** [comment]
Hey @iang0ld! Do you mean something like a custom template for options so one option can be multiline, for example:
```
---------------------
| avatar | User full
|        | User email 
---------------------
| avatar | User full
|        | User email 
---------------------
```
Or do you have something different in mind?

**Comment by nunob87** [comment]
It was interesting to print table type, and when you click on the table value, return what to click

example:
``<table>
<thead>
<tr>
<th>Product</th><th>Price Costs</th><th>Price 1</th><th>Price 2</th><th>Price 3</th>
</tr>
</thead>
<tbody>
<tr>
<td>Test</td><td @click>10.00</td><td @click>15.50</td><td @click>18.00</td><td @click>12.00</td>
</tr>
<tr>
<td>Test 2</td><td @click>10.50</td><td @click>19.00</td><td @click>25.15</td><td @click>30.00</td>
</tr>
...
</tbody>
<tfoot>
<tr>
<td colspan="5">ADD</td>
</tr>
</tfoot>
</table>``

**Comment by shentao** [comment]
Sadly I guess that’s out of the scope of Multiselect.
You can try using the `option-function` prop for a custom render function but the select handler will be on the whole option object anyway as it looks like this:
https://github.com/monterail/vue-multiselect/blob/2.0/src/MultiselectOption.js

**Comment by nunob87** [comment]
thank you

**Comment by shentao** [comment]
You could also build your own dropdown using the available mixins with your custom template.

**Comment by shentao** [comment]
@nunob87 I updated this in the beta.12 so that you can use scoped slots for this. Should be a lot easier to do it now :)

**Comment by iang0ld** [comment]
Great news.  Thank you.

**Comment by shentao** [comment]
Forgot to mention it – it’s all documented in the new docs: https://monterail.github.io/vue-multiselect/ :D

**Comment by iang0ld** [comment]
Thx

**Comment by iang0ld** [comment]
FYI new project will be using vue-multiselect with the quasar framework.

**Comment by shentao** [comment]
Happy to hear that! :)
