### ISSUE TITLE
searchable props with async vue-multiselect

### ISSUE THREAD

**Issue by chocochaii** [monterail/vue-multiselect#172]
I'm working on async with vue-multiselect and I've got an issue like the response from API return 8 options in total but the multiselect displays only 2 options.

I found that the root cause is the :searchable="true" props, since those 2 options from response contain exactly match word as input while others don't.

Are there any ways to maintain all the returned options OR to modify the searchable functions?
(I've tried using :internal-search='false' but still doesn't work)

Thank you.

**Comment by shentao** [comment]
`:internal-search="false"` should help with this. Are you using version 2.0 or 1.x?

**Comment by chocochaii** [comment]
I use 2.1

**Comment by shentao** [comment]
So it might be a bug. I will look into it, thanks!

**Comment by chocochaii** [comment]
Wow! `:local-search="false" ` made it works.

**Comment by shentao** [comment]
Still have to look into it. Or revert the change from `:internal-search` to `:local-search`. :/ Thanks!
