### ISSUE TITLE
Need a standalone version for non-Node back-end

### ISSUE THREAD

**Issue by dc3671** [monterail/vue-multiselect#173]
Do we have a standalone version that can be simply inserted to a template? Such as:
```html
<script src="script/vue-multiselect.min.js"></script>
```
I can download through `npm` and get a similar file from `node_modules/vue-multiselect/lib/vue-multiselect.min.js`, but I'm not sure how to use it and whether including this file only is enough.

Thanks!

**Comment by shentao** [comment]
It is enough to just add it as a script tag! :) The 1.x version is also available on CDN: https://cdn.jsdelivr.net/vue.multiselect/1.1.4/vue-multiselect.min.js

The 2.0 version will be after it’s stable. I hope to do this during the incoming holidays. :)

Jsdelivr wrongly assumes that the 2.0 is on master branch, so the link to 2.0 doesn’t work.
