### ISSUE TITLE
Nothing being rendered

### ISSUE THREAD

**Issue by midnite81** [monterail/vue-multiselect#174]
I am trying to use the vue-multiselect component within another component I am building. However, I am getting the following error:

![image](https://cloud.githubusercontent.com/assets/254850/21394324/0eb5d832-c790-11e6-94d7-23eea25208c8.png)

I am importing it using the following 

`'multiselect': require('vue-multiselect')`

I did try using an `import` statement, however that resulted in another error

**Comment by shentao** [comment]
When using require you have to access the `.default` property.

```
'multiselect': require('vue-multiselect').default
```

**Comment by midnite81** [comment]
Thanks, however this now produces the same error message as when using the `import` statement. The error is as follows:

![image](https://cloud.githubusercontent.com/assets/254850/21394925/7a1537d8-c792-11e6-986f-95be8b8c2aa4.png)

**Comment by shentao** [comment]
Please update Vue to 2.1.6. This should solve the problem.
I will change the issue title to the above error to make it easier to find for other people.
Thanks!

**Comment by midnite81** [comment]
Thanks that worked.

**Comment by smith64fx** [comment]
updated vue and everything works. @shentao you are awesome!!! thank you

**Comment by shentao** [comment]
Happy to hear that! :) 
Also there already was an update to Vue v2.1.7. There were some changes to the compiler so if you happen to have any other problems - just update Multiselect to beta.13. It's already compiled using the newest version.
