### ISSUE TITLE
Disabled option

### ISSUE THREAD

**Issue by lavezzi1** [monterail/vue-multiselect#176]
Hello there, 

How can I disable select option? So user couldn't select it.

**Comment by shentao** [comment]
Not impossible but will require some work to make it actually work.
Depending on the version of Vue you’re using you can use the `Vue.partial` or scoped slots solution.
Inside a custom option template you can add `pointer-events: none` to some of the options. Or play with `preventDefault`/ `stopPropagation`. :)

Hope this helps!

**Comment by lavezzi1** [comment]
@shentao Can you please show an example of how you would do it, please.

**Comment by shentao** [comment]
Been looking into it and sadly I wasn’t able to accomplish this. Sorry to mislead you. It might require some changes inside Multiselect itself. Will work on this feature around January.

Wondering if I should also make it possible to disable internal selections (thus forcing to update the selections through `@select` and `@remove` instead of relying on `@update` or `v-model`.

What’s your opinion?

**Comment by shentao** [comment]
Ok :)

**Comment by zv3** [comment]
Great suggestion, would love to have a way to prevent selection on greyed out options.

**Comment by lukechapman** [comment]
+1 for this please!

It would also be great if we could set options that cannot be removed from the list. Something like:

`options: [{
        name: 'Important',
        value: 'important',
        removable: false
    }]`

**Comment by lavezzi1** [comment]
@shentao any progress?

**Comment by shentao** [comment]
Well. You will now be able to add `$isDisabled` to the options that should be unable to be selected.

**Comment by Jlavatai** [comment]
Is there a way to custom style disabled options?

**Comment by zealotrahl** [comment]
Hi, will be really cool adding isDisabled to group options, how do you think it can be implemented?

**Comment by X2Style** [comment]
Hi @shentao! It would be helpful to add similar option to prevent deselect disabled option. (For example: $isCanDeselect: true)
`removeElement (option, shouldClose = true) {
      if (option.$isCanDeselect) {
        return
      }`

**Comment by shentao** [comment]
You should be able to do that if you use the `option` slot and provide your own way of displaying options. There you can decide what styling you want to use.
See docs: https://vue-multiselect.js.org/#sub-custom-option-template

**Comment by bymaximus** [comment]
should have 2 different options, 'selectable' and 'deselecteable' if selected, $isDisabled make it unable to be deselected

**Comment by BenBroide** [comment]
I had an issue when multiple is false, if user selects the same option again the v-model becomes null, even that the value stays the same. This was causing errors in the app.
To solve is I added a slot that disables click in css if the option is selected.
Adding the code below I hope this may help someone 
```
<multiselect
				v-model="selectedOption"
				:options="optionsArray"
				@input="callbackFunction"
			>
				<template slot="option" slot-scope="props" >
					<span v-if="props.option === selectedOption" :style="{'pointer-events': 'none'  }">
						@{{props.option}}
					</span>
					<span v-else>@{{props.option}}</span>
				</template>
			</multiselect>
```

**Comment by Groundbender** [comment]
vue 2: 
options () {
      return options.map((option) => {
        return {
          ...option,
          $isDisabled: option.disabled,
        };
      });
    }

**Comment by Timur-hs** [comment]
vue 2: 
options () {
      return options.map((option) => {
        return {
          ...option,
          $isDisabled: option.disabled,
        };
      });
    }

**Comment by Timur-hs** [comment]
> ```
> vue 2: 
> options () {
>       return options.map((option) => {
>         return {
>           ...option,
>           $isDisabled: option.disabled,
>         };
>       });
>     }
> ```

Thanks for helping
