### ISSUE TITLE
How to prevent the dropdown from showing on focus?

### ISSUE THREAD

**Issue by wujekbogdan** [monterail/vue-multiselect#177]
Hi,

I'd like to show the dropdown after at least one character is entered. Is it possible? I wasn't able to find an answer in the documentation.

It would be great if there was a possibility to define when the dropdown is shown (for example onFocus, onInput, etc) or if there were a programmatical way to show/hide the dropdown - the open/closed state could be determined by a boolean property - exactly like `:loading` or `:disabled` properties.

**Comment by shentao** [comment]
I’m not sure if this is possible right now.
You can, however use the `:local-search="false"` and initialize the component with an empty `:options` list. After someone types a character you could restore the list. This will, however require you to do the searching yourself using the `@search-change` event.

**Comment by wujekbogdan** [comment]
Thanks. Looks like a good workaround, I'll try it out. But it would be great if such a feature was implemented.

**Comment by shentao** [comment]
I will think about it! :)

**Comment by shentao** [comment]
As of now, nothing is shown if the search and options are both empty.
