### ISSUE TITLE
Uncaught TypeError with Vue 2.1.7

### ISSUE THREAD

**Issue by silvestreh** [monterail/vue-multiselect#179]
I'm getting this error after upgrading to Vue `2.1.7` (I was on Vue `2.1.6` before):

```
Uncaught TypeError: Cannot set property 'isRootInsert' of undefined
    at createElm (vue@2.1.7:4055)
    at createChildren (vue@2.1.7:4164)
    at createElm (vue@2.1.7:4089)
    at VueComponent.patch [as __patch__] (vue@2.1.7:4507)
    at VueComponent.Vue._update (vue@2.1.7:2483)
    at VueComponent.<anonymous> (vue@2.1.7:2457)
    at Watcher.get (vue@2.1.7:1663)
    at new Watcher (vue@2.1.7:1655)
    at VueComponent.Vue._mount (vue@2.1.7:2456)
    at VueComponent.Vue$3.$mount (vue@2.1.7:6078)
```

I put this [JSbin](http://jsbin.com/zulutocika/edit?js,output) together, in case it helps. And [here's a (resolved) Vuejs issue](https://github.com/vuejs/vue/issues/4466) which *might* be related since the error message is similar.

Also: Merry christmas! 😁

**Comment by martinBadin** [comment]
I have same issue with same plugin (Vue `2.1.7`). With Vue `2.1.6` he worked correctly.

**Comment by silvestreh** [comment]
Unfortunately I can't roll back to Vue `2.1.6`. Webpack fails to create the bundle because of version mismatches:

```
- vue@2.1.6
- vue-template-compiler@2.1.7
```

**Comment by rousos87** [comment]
@silvestreh just delete node_modules and just insert vue@2.1.6 and vue-template-compiler@2.1.6 version on package.json and npm install.

**Comment by silvestreh** [comment]
@rousos87 that's exactly what I ended up doing while this issue gets resolved 😄

**Comment by yasirhantoush** [comment]
I am getting similar errors with vue@2.1.7 and vue-remplate-compiler@2.1.7:
```
vue.common.js?e881:435 TypeError: Cannot read property '_transitionClasses' of undefined(…)logError @ vue.common.js?e881:435
bluebird.js?e366:1546 Unhandled rejection TypeError: Cannot set property 'isRootInsert' of undefined
    at VueComponent.Vue$3.$mount (eval at <anonymous> (http://singlebody.local/group-admin-dev/app.js:598:2), <anonymous>:6080:15)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (http://singlebody.local/group-admin-dev/app.js:598:2), <anonymous>:8454:16)
From previous event:
    at Object.<anonymous> (http://singlebody.local/group-admin-dev/app.js:814:2)
    at __webpack_require__ (http://singlebody.local/group-admin-dev/app.js:554:30)
    at fn (http://singlebody.local/group-admin-dev/app.js:85:20)
    at Object.<anonymous> (http://singlebody.local/group-admin-dev/app.js:585:19)
    at __webpack_require__ (http://singlebody.local/group-admin-dev/app.js:554:30)
    at http://singlebody.local/group-admin-dev/app.js:577:37
    at http://singlebody.local/group-admin-dev/app.js:580:10
```

**Comment by johnleider** [comment]
I'm getting the same error but it involves nested components with slots.

**Comment by shentao** [comment]
That must be related to https://github.com/vuejs/vue/releases :) 
Going to recompile the plugin in a moment :)

**Comment by shentao** [comment]
Published `vue-multiselect@2.0.0-beta.13`. :)
I hope this solves the problems!

**Comment by mmochetti** [comment]
Same here... how do I tackle this down?
![image](https://cloud.githubusercontent.com/assets/3678598/21506247/53ef9872-cc4d-11e6-9e5d-a26cb8d178cb.png)

**Comment by shentao** [comment]
Please update to `beta.13` :)

**Comment by bkrztuk** [comment]
@shentao the min.js file is recompiled too? Used latest vue and beta13 package still get the same problem

**Comment by shentao** [comment]
@bkrztuk Which Vue version are you using?

**Comment by bkrztuk** [comment]
Downgraded from 2.1.8 to 2.1.7 just now and still the same…

**Comment by shentao** [comment]
Weird. It should work. Are you using npm or yarn? I heard that with the latter there are sometimes problems with cleaning the cache.

**Comment by bkrztuk** [comment]
Just download b13 release and use vue-multiselect.min.js which is there

**Comment by bkrztuk** [comment]
@shentao found a problem, it is not mutlselect issues but rather my code where I've duplicated the same properties in other component. All works fine with b13 version.

**Comment by shentao** [comment]
Happy to hear that. :)

**Comment by renwz** [comment]
TypeError: Cannot read property '_transitionClasses' of undefined
