### ISSUE TITLE
How to use custom option templates with 2.0.0-beta.10

### ISSUE THREAD

**Issue by shaneeza** [monterail/vue-multiselect#185]
I noticed in v1 and v2 of vue-multiselect you could you custom option template for a custom template.  However I am using v2, 2.0.0-beta.10, but the example [here](http://monterail.github.io/vue-multiselect/#sub-custom-option-template) uses, i believe, 2.0.0-beta.13 which i don't have the option of upgrading to at the moment.  Is there an example of how to use the custom option template for 2.0.0-beta.10?

**Comment by shentao** [comment]
Hey! I don't have access to my computer at the moment, but there was an example in the issues. Try searching there!

**Comment by shentao** [comment]
This might be helpful: https://github.com/monterail/vue-multiselect/issues/135

**Comment by shaneeza** [comment]
Yes, #135 works perfectly!  Thanks!
