### ISSUE TITLE
Got Uncaught TypeError when value is null

### ISSUE THREAD

**Issue by zipme** [monterail/vue-multiselect#186]
It seems if the value is null, and when the component is being dealloc, an error 'Uncaught TypeError: Cannot read property '${track-by property}' of null' will be thrown.

I think this line here may cause the issue: https://github.com/monterail/vue-multiselect/blob/2.0/src/multiselectMixin.js#L292

**Comment by shentao** [comment]
The track-by prop is used to identify and compare the elements if they are objects. It's more of a unique key, that must be available on all the options. This might be confused with track-by="$index" which is not possible in Multiselect.

**Comment by zipme** [comment]
@shentao Sorry for not making myself clear, the options are not the issue here, but the :value = null causes the problem. It's strange that everything works fine until I navigate to a new route (using vue router), I guess somewhere in the deactivate hook referencing the `valueKeys` computed property in where `this.internalValue[this.trackBy]` is called, and if `this.internalValue == null`, the error occurs

**Comment by shentao** [comment]
That makes sense. There is already a PR to fix the null value error. That should resolve the problem.

**Comment by zipme** [comment]
@shentao cool! thanks for the update!
