### ISSUE TITLE
"Space" gets automatically deleted when entering text

### ISSUE THREAD

**Issue by smith64fx** [monterail/vue-multiselect#187]
I made a video to explain this issue:

![](https://media.giphy.com/media/3o6ZsTv7ih2JMDipLq/giphy.gif)

When I enter "bmw" and press space immediatly, the space gets deleted.
But when I wait a little bit, the "space" gets inserted and not deleted.

Does somebody have an idea where this could come from?

Thank you so much! I love this component! <3

**Comment by shentao** [comment]
That's really weird! I will try to look into it! Thanks for submitting it!

**Comment by shentao** [comment]
Trying to reproduce this but no success so far. 
What browser do you use? Which versions of Vue and vue-multiselect are you running?

**Comment by smith64fx** [comment]
Hi,
Thanks for your fast answer. I use the latest version of vue and vue-multiselect
vue: 2.1.8
vue-multiselect: 2.0.0-beta.13

I'm doing my requests asynchroniously. This is the problem.

http://monterail.github.io/vue-multiselect/#sub-asynchronous-select

Just have a look at this example here. There is the same problem.
e.G. if you look for "afgh" and press backspace a few times.

You can also make your internet connection slower in chrome so you can see it better.

![image](https://cloud.githubusercontent.com/assets/3246782/21550674/0d994264-cdfc-11e6-9865-a934503ba509.png)

![image](https://cloud.githubusercontent.com/assets/3246782/21550677/14438e8a-cdfc-11e6-9236-d00c1ae8674b.png)

**Comment by shentao** [comment]
Now I see. Weird I never noticed this in the first place. It doesn’t happen in the 1.x version so that seems to be a regression. Thanks!

**Comment by Novynn** [comment]
Maybe related to this, when you type something in the input such as "abc d" then hit backspace with the cursor on the "d" the string will be trimmed back to "abc" rather than "abc ".

**Comment by smith64fx** [comment]
is this already fixed? couldn't find the related commit. Thanks!

**Comment by shentao** [comment]
Have it locally atm. Will push and release (hopefully) soon.

**Comment by smith64fx** [comment]
ok cool. 👍

**Comment by florentsorel** [comment]
Same problem here.

It seems to happen when I debouncing the ```@search-change``` event, otherwise I don't see the bug.

```javascript
getResults: debounce(function (query) {
  this.isLoading = true;
  axios.get(`/api/search?name=${query}`)
    .then((response) => {
      this.items = response.data.results;
      this.isLoading = false;
    });
}, 250),
```

**Comment by blocka** [comment]
This is happening because of https://github.com/monterail/vue-multiselect/commit/2cac27a2607ab054a7a91289c83ffc6edac487c2#diff-6b5af0f1e9c993645e63370d4087a280R246

I can't think of any reason why I would want my keyword trimmed...at least it should be an option if there is a usecase.

**Comment by shentao** [comment]
I know. It’s already solved but waiting to be released. :)

**Comment by blocka** [comment]
Looking forward!

**Comment by blocka** [comment]
Any reason you haven't pushed this up? Seems like a really simple fix!

**Comment by shentao** [comment]
Sorry. Not time yet. :/

**Comment by blocka** [comment]
Ok...I guess I have to fork in the meantime. Causing issues on our end.
