### ISSUE TITLE
[V1] Change placeholder or remove it

### ISSUE THREAD

**Issue by rjcrystal** [monterail/vue-multiselect#189]
In multiple selection the input field has html placeholder to it. when i select more options the height changes, because of limited width, and limits has to be set too less to keep it in one line. is there any way i can disable or remove the entire input tag which has the placeholder or even just change the placeholder so that it does not goto next line. 
also is there way where i can disable tag creation and just show custom label in the select box.
thanks

**Comment by shentao** [comment]
You can change the placeholder with the `placeholder` prop.
