### ISSUE TITLE
searchable='false'  and multiple='true' shows not only Selections but also additional Text 

### ISSUE THREAD

**Issue by wotamann** [monterail/vue-multiselect#193]
Working with the latest VUE 2.0 stack I updated to  

`"vue-multiselect": "^2.0.0-beta.13" `

`<multiselect> `works well, but if `:searchable="false"`  and `:multiple="true"` the display shows, not only the green selections 2 3 4 but also nearby the text 2,3,4. 

![vue-multiselect](https://cloud.githubusercontent.com/assets/5354164/21606083/716995c8-d1ad-11e6-8898-d37e2ad8f0d9.png)

This is a new behaviour, which I got after my last update without changing my code. I could reproduce this with a simple example 

```
<multiselect 
	:searchable="false"
	:multiple="true"   
	:options="[1,2,3,4,5,6]"  >
</multiselect>
```

Please can you help and explain me, what i'm doing wrong or how to hide the text 2,3,4

**Comment by shentao** [comment]
That’s a bug! Thanks for finding it!

**Comment by wotamann** [comment]
Thanks for your fast response!!!
