### ISSUE TITLE
[V2] Autoselect first non-label

### ISSUE THREAD

**Issue by Novynn** [monterail/vue-multiselect#195]
I'm currently working with groups of options, and I have an issue pertaining to selection. 
It seems the internal pointer starts at 0 which is usually fine since it will select the first item in the list. However when groups are involved, the first entry returned is usually a group label which cannot be selected. 
This prevents using enter or tab to autocomplete the first entry.

Ideally the first entry selected would be the first non-label.

Thank you for your time!

**Comment by shentao** [comment]
Hey!
I might have missed that! I will try to fix it, this weekend as it seems quite easy to do actually.
Thanks!

**Comment by shentao** [comment]
Fixed. Will be in the next release! Thanks! :)

**Comment by shentao** [comment]
Released! :)
