### ISSUE TITLE
New tagging entries are always lowercase...

### ISSUE THREAD

**Issue by jmrauen** [monterail/vue-multiselect#197]
It is possible to let the creation of tag entries case sensitive?

**Comment by shentao** [comment]
Sure, can do :)

**Comment by nickfederighi** [comment]
I second this! Couldn't figure out why everything was lowercase and it was driving me bananas!

**Comment by jmrauen** [comment]
See image attached from your example page, I write "HELLO" and it create the tag "hello". But the available tag is written in "Javascript". 
![image](https://cloud.githubusercontent.com/assets/23209835/21741066/b861c060-d4cb-11e6-8c51-7b8dd29f4efe.png)

**Comment by shentao** [comment]
On it! :)

**Comment by shentao** [comment]
Fixed. Should be in the next release! :)
