### ISSUE TITLE
Need help to understand something

### ISSUE THREAD

**Issue by florentsorel** [monterail/vue-multiselect#198]
Hi @shentao 

Can you please explain what mean the [$isLabel](https://github.com/monterail/vue-multiselect/blob/2.0/src/Multiselect.vue#L72).

[Here](https://github.com/monterail/vue-multiselect/blob/2.0/src/pointerMixin.js#L53) too.

Thx :)

**Comment by pczarn** [comment]
The only place where `$isLabel` is set is in the `flattenOptions` function. That function looks for a `this.groupValues` attribute on each option. When that attribute is present, it adds an option that has `$isLabel: true`. The documentation says `groupValues` is the "name of the property containing the group values".

It's best if you check out the documentation for groups. https://monterail.github.io/vue-multiselect/#sub-option-groups
The gray fields that cannot be selected are labels.

**Comment by shentao** [comment]
Exactly what @pczarn just said :)
