### ISSUE TITLE
Reversed arrow position issue

### ISSUE THREAD

**Issue by freakone** [monterail/vue-multiselect#2]
![image](https://cloud.githubusercontent.com/assets/1595360/14881748/9edb6dd4-0d35-11e6-89a1-a9a635c6e079.png)

**Comment by shentao** [comment]
@freakone please update to the latest version and see if this is still happening

**Comment by freakone** [comment]
![image](https://cloud.githubusercontent.com/assets/1595360/15541412/a9d1ed78-228c-11e6-91f0-5556c7bf0522.png)

@shentao still the same. I assume that there is some css conflict.

**Comment by shentao** [comment]
Yes, this might be it! Please double check your styles, as also list elements are larger than they supposed to be. I will change the `inherit` values to fixed ones later.

**Comment by freakone** [comment]
@shentao: see .multiselect__select:before and .multiselect__select:active. My input height is smaller, and arrow positions are fixed. I think they should be relative to input box.

**Comment by shentao** [comment]
Hmm. So you’re changing the height of the select input right? That might cause this problem. Will think about how to fix this!
