### ISSUE TITLE
Is there any way to prevent multiselect styles from loading?

### ISSUE THREAD

**Issue by wujekbogdan** [monterail/vue-multiselect#201]
I want to write styles from scratch, I need a very customized design and I don't want to overwrite the default styles with my own styles. Is there any way to disable the default stylesheet completely?

**Comment by shentao** [comment]
My guess would be to extend the Multiselect:

```vue
<template>
// custom multiselect template
</template>

<script>
import Multiselect from 'vue-multiselect'

export default {
  extends: Multiselect,
  // your custom logic here
}
</script>

<style>
// your custom styles here
</style>
```

This however, would require creating a new template that you will be styling. However you might try not providing a template here, just the styles. This might result in overriding just the styles, not the template. But that’s just a guess. Let me know if that helps! :)

**Comment by wujekbogdan** [comment]
Thanks for the response. I've already tried this solution before posting on Github. It doesn't prevent default styles from loading. Even if you extend the component and provide a custom template and CSS then original styles are still injected into the page.

This way I can only override the original styles (which I can do without extending the component as well), but the original styles are still loaded.

But it seems that it has nothing to do with the vue-multiselect component, it's a vue.js core issue, or even a vue-loader/vuify issue.

**Comment by shentao** [comment]
I will talk with Linus or someone other from the core team to find a solution. Thanks! :)

**Comment by sqal** [comment]
I'm also looking for some easy solution for this problem. Currently i have to override styles with `!important` tag which I dislike very much  I think the best solution would be if  you guys would drop `.vue` component  in favour of plain js file and `render` function and provide styles in separate file (.css, .scss)  then the customization will be much more easier  :)

**Comment by shentao** [comment]
For SSR I’m working on separating the styles from the component so that you have to import them yourself. This should solve all problems regarding using custom styles.

**Comment by shentao** [comment]
@sqal @wujekbogdan beta.14 released and should fix this problem. Sorry you had to wait so long :(
Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.
