### ISSUE TITLE
[feature request] Add more slots to make each part of the component fully customizable

### ISSUE THREAD

**Issue by wujekbogdan** [monterail/vue-multiselect#202]
It would be great if every part of the component was fully customizable. I'd love to be able to replace `multiselect__select`, `multiselect__spinner`, and `multiselect__select` elements with a custom HTML.

**Comment by shentao** [comment]
Might come in a later release. If you want to customize every part of the multiselect I guess you would be better just extending the component with your own custom template and styling

**Comment by shentao** [comment]
Already implemented. Available slots:
- `carret`
- `tag`
- `loading`
- `beforeList`
- `maxElements`
- `option`
- `noResult`
- `afterList`

**Comment by wujekbogdan** [comment]
Thanks a lot!

**Comment by aios** [comment]
@shentao not have example for implement noResult slot? i cant implement it
