### ISSUE TITLE
Is there any way to prevent the search field from clearing on focus?

### ISSUE THREAD

**Issue by wujekbogdan** [monterail/vue-multiselect#203]
1. Define a searchable component.
2. Search a term and accept the selection
3. Click the search field again
4. The previously selected term is removed.

I'd like to prevent the search field from clearing. Is there any clean way to do it? I think I could listen to events and restore the state manually, but it feels a bit hacky to me.

**Comment by shentao** [comment]
Sadly it is not possible at the moment.

**Comment by asvae** [comment]
That would be nice to have. But I think, doing type-ahead would require a whole lot of remodeling.

1) Type-ahead should return string, while options could be an array of strings or objects.
2) Typed text should persist at all times.

That's not the case for `vue-multiselect` at the moment.

Might be worth to make another library. BTW, there is [one](http://pespantelis.github.io/vue-typeahead/). Not sure about its quality or usefulness though.

**Comment by shentao** [comment]
There will be a new prop `preserveSearch` that preserves the search query through opening/closing the select. Will be available in the next release.

**Comment by Glideh** [comment]
Useful option, however the search is not preserved after selection, is there a way to do that ?

**Comment by Glideh** [comment]
Useful option, however the search is not preserved after selection, is there a way to do that ?

**Comment by bakhti-uzb** [comment]
> Useful option, however the search is not preserved after selection, is there a way to do that ?

As said in the docs you can use 

> `:clear-on-select="false"` – the search query stays the same after selecting an option

**Comment by Glideh** [comment]
Well the prop docs actually says
> Clear the search input after select(). Use only when multiple is true.

While I was talking about a non multiple select here, it's not keeping the search on a multiple either, maybe I have another incompatible prop

**Comment by bakhti-uzb** [comment]
Interesting, I am using the same version `2.1.6`, and `clear-on-select` prop is working as expected with both `single` and `multiple`
Here is my config: 
```vue
<multiselect
    v-model="editingItem.mxikCategoryCode"
    class="custom-multiselect"
    :class="[
		    !!errors.length ? 'invalid' : '',
		    valid ? 'valid' : ''
    ]"
    label="mxikCategoryNameUz"
    :custom-label="customLabel"
    placeholder="MXIK search"
    open-direction="bottom"
    :options="mxikCategories.map(cat => cat.mxikCategoryCode)"
    :searchable="true"
    preserve-search
    :clear-on-select="false"
    :loading="isLoadingMxik"
    :internal-search="false"
    :hide-selected="false"
    :options-limit="300"
    :limit="3"
    :max-height="600"
    :show-labels="false"
    @search-change="debounceSearchMxikCategories"
    @select="mxikCategorySelected"
    >
    <span slot="noResult">Hech qanday element topilmadi. Qidiruv so'rovini o'zgartirib ko'ring.</span>
</multiselect>```

**Comment by bakhti-uzb** [comment]
I think you should use `preserve-search` prop as well, set it to `true`.
From docs: 

> preserveSearch | Boolean | false | If set to true, will preserve the search query when opening/closing the component.

**Comment by uacode** [comment]
Crutch solution
```js
<multiselect v-model="value"
....
:class="`el_${parentIndex}_${index}`"
@open="presetValue"
/>

methods: {
presetValue() {
        if (this.v.title)
                this.$nextTick(() => $(`.el_${this.parentIndex}_${this.index} input`).val(this.v.title));
        }
}

```

**Comment by anwar3606** [comment]
Here is my solution:

```js
<multiselect
    ref="multiselect"
    v-model="search_text"
    :multiple="false"
    :preserve-search="true"
    :clear-on-select="false"
    @open="open"
/>


methods: {
  open() {
    this.$nextTick(() => {
      this.$refs.multiselect.search = this.search_text
      this.$refs.multiselect.placeholder = this.search_text
    });
  },
```

**Comment by mounssif** [comment]
@donnyv try :can-clear="false"

**Comment by Arafat7616** [comment]
`clear-on-select="false"` or `clear-on-select="true"`

It's working. Thank you so much everyone.
