### ISSUE TITLE
[Bug] Full options list is visible for a short period of time right after a component looses focus.

### ISSUE THREAD

**Issue by wujekbogdan** [monterail/vue-multiselect#204]
1. Define a searchable component.
2. Type anything (not really anything: anything that will narrow down the search results).
3. Click outside the component in order to close the dropdown.
4. A full list of all available options shows up for a fraction of a second.

Here's a video: https://zippy.gfycat.com/GrouchyUnfitCaterpillar.webm

It happens because the component's state is changed before the animation is complete, so it's rather a visual glitch, not a "real" bug, but it looks odd.

**Comment by shentao** [comment]
Thanks. Fixed! :) Will be in the next release.

**Comment by wujekbogdan** [comment]
omg, so fast!
thank you.

**Comment by shentao** [comment]
You will have to wait for the release, though. I want to first add SSR support to the release, so it should should be available ~tomorrow.

**Comment by shentao** [comment]
Released! Late I know :(
