### ISSUE TITLE
Any chance to have this component working with vue.js 2?

### ISSUE THREAD

**Issue by naretini** [monterail/vue-multiselect#205]
It would be great to have this component working with vue.js 2.
Do you have any plan or hint on how to make it work?

Thanks

**Comment by shentao** [comment]
It's already working with Vue 2.x. Look at the docs! ;)
The beta can be downloaded with:
npm install vue-multiselect@next --save

It should become stable soon. Still want to improve some things so there might be some small breaking changes till that.
