### ISSUE TITLE
Async Tagging Question

### ISSUE THREAD

**Issue by TheSycamore** [monterail/vue-multiselect#206]
Firstly I would like to thank you for the great work in creating vue-multiselect! 
I was reading through the documentation and couldn't figure out whether it is possible to do Asynchronous Tagging. (I see they both have separate sections in the Docs) For example: the users input sets off a ajax request retrieving any tags already in the database which would come up as an select option. I hope that made sense to you.

Thanks for your time!

**Comment by shentao** [comment]
Hey! Thanks for your kind words! 

I think that’s possible!
The only drawback could be having a short moment while loading the available tags from backend when someone could enter a new tag that would duplicate an existing one. Unless you would change the `:taggable` props from `true` to `false` the same way you have to do with `:loading`. This would disable the 'adding a tag' functionality for the time of loading available tags. I haven’t tried that combination though, yet.
Besides that there shouldn’t be any other problems. The `@tag` event doesn’t add anything to the options list/value thus you can handle the adding asynchronously too! :) 

I hope that helps! Let me know if you any more assistance!

**Comment by TheSycamore** [comment]
Thank you for your quick response shentao. I will experiment with your suggestions and write back if I get it working.

**Comment by bartlomieju** [comment]
I am currently working on exactly this feature. The problem I encountered: my tags have roughly this structure (simplified) `{id: 1, name: 'foobar'}`. I added `:label="name"`, however this causes to throw `Cannot read property 'toString' of undefined`. 

After some investigation I pinpointed the culprit to be the value we input as it constructs: `{label: <input value>}` ignoring `:label:` prop we specified. 

The solution I came up with for now:
1. `:label="label"`
2. Add `label` key to tags that maps to actual value we wanted to use as `label`.
It works, but still causes short insertion of the 'input object' to the list. I guess it may be related to the fact that it has no key for `track-by`. @shentao any ideas on this one?

**Comment by sandbox-services** [comment]
@bartlomieju  We tried your solution but even after defining label="label" when using options groups it was still failing, we ended up using the solution below. not sure if @shentao see's it as a viable solution but it allowed the additional functionality we needed..

Its probably not the most ideal solution but it does the job.
https://github.com/monterail/vue-multiselect/pull/313

**Comment by shentao** [comment]
Closing as #313 is implemented.
