### ISSUE TITLE
Inline onmousedown event on remove button

### ISSUE THREAD

**Issue by floorish** [monterail/vue-multiselect#207]
Each selected option has a remove icon, which has an inline `onmousedown` event attached.
See: https://github.com/monterail/vue-multiselect/blob/2.0/src/Multiselect.vue#L16

I'm not sure why that is a plain inline javascript event, but it causes an error when inline javascript is disabled by the Content Security Policy (i.e. `script-src 'self';`)

    Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

Removing that particular `onmousedown` event solves the issue.

**Comment by shentao** [comment]
Will look into it. Thanks! :)
