### ISSUE TITLE
[question] dont show noResult until there truly are noresults.

### ISSUE THREAD

**Issue by jaketoolson** [monterail/vue-multiselect#211]
I'd like the noResult message only to appear _after_ a search request has been completed.  Can this be done?

In my scenario, I'm using ajax to search and return results based on the search query.  The moment someone begins typing, the noResult box appears even though the request is still pending a response.  I've tried to play with the slot adding ```v-if="!isLoading"``` but no real tangible solution.

![wz0diag04m](https://cloud.githubusercontent.com/assets/612332/21880592/a480dd88-d854-11e6-9c6b-02effe3cec9c.gif)

**Comment by shentao** [comment]
A nice idea! Thanks! I will add it in the next release around this week :)

**Comment by jaketoolson** [comment]
When I use the following, its ignored and the package's default noShow takes over:
```<template slot="noShow" v-if="!isLoading">
<span>No results could be found</span>
</template>```

However, when I remove the ```v-if```, then my slot overrides the package' slot (as intended) but it still displays the no results message even though its still searching.

**Comment by shentao** [comment]
Fixed. Doesn’t show `noResults` when `loading` is true. Will be published with the next release. :)

**Comment by jaketoolson** [comment]
Awesome, looking for to the next release.  This is one of my favorite packages I've used in a very long time - its smooth, & works well.

**Comment by shentao** [comment]
@jaketoolson beta.14 released and should fix this problem. Sorry you had to wait so long :(
Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.
