### ISSUE TITLE
Bug remove selected options

### ISSUE THREAD

**Issue by nunob87** [monterail/vue-multiselect#212]
hello, my code
``````
<multiselect :value="itens_" v-model="itens_" :options="categorias" :multiple="true" label="nome" :track-by="id" placeholder="" select-label="" deselect-label="" :close-on-select="false" :clear-on-select="true" :searchable="true" :allow-empty="true" :hide-selected="true" @close="onTouch"></multiselect>
``````

When you delete the first selected item, always delete the last one
The options I select do not disappear from the list

thank you

**Comment by shentao** [comment]
`:track-by="id" => track-by="id"`
It should be a string. 

Also please remove `:value` if you’re using `v-model`. That’s redundant.
