### ISSUE TITLE
Clear selection without setting `:selected`

### ISSUE THREAD

**Issue by evanb2** [monterail/vue-multiselect#213]
I'm using two dropdowns to set a single field.

So if I make a selection in the first I need to clear the selection in the selection, and vice versa.

Right now I'm doing that by toggling the `:selected` prop, but by using this prop I'm unable to deselect that value once I've set it...

Is there any way I can clear the selection without using the `:selected` prop?

**Comment by shentao** [comment]
It is only possible by using the `:selected` prop. Or `:value` if you’re using Vue 2.0. 
If you need any further help please provide a JSFiddle.

**Comment by LindenWalsh** [comment]
@shentao How would I go about clearing the value inside a method? Say I have a method that gets fired when I submit a form and I want to clear the values for each multiselect in that form?

Cheers!

**Comment by shentao** [comment]
You will have to set the `:value` or `:selected` (if using Vue 1.x) to either `null` or empty array.

**Comment by LindenWalsh** [comment]
@shentao I guess I have a more general question then; how do I change the components prop from within a method on the root?

**Comment by shentao** [comment]
Not sure what you mean by `root`. 
If you have for example `:value="selectedValue"`
then you can just reset that `selectedValue` inside a submit method.
```
onSubmit () {
  doStuff()
  this.selectedValue = null
}
```

**Comment by marcelinhov2** [comment]
@shentao It just work for the first time, if you try to reset again it didn't work. Do you know why?

**Comment by shentao** [comment]
Try using `Vue.set(this, 'selectedValue', [])`.
