### ISSUE TITLE
Key is a reserved attribute?

### ISSUE THREAD

**Issue by celinekoe** [monterail/vue-multiselect#218]
I changed the version of Vue (I'm not sure which, I had to downgrade from Laravel 5.3 to 5.2). When I tried to view the page, the console logged the followed error: "key" is a reserved attribute and cannot be used as component prop."

Is it possible to fix or do I have to remove the multiselect component?

**Comment by celinekoe** [comment]
My bad, I'm using Vue 2, using npm install vue-multiselect@next worked.

**Comment by shentao** [comment]
Happy to hear that! I have to finally update the readme for the 2.0 version.
