### ISSUE TITLE
Add search button option?

### ISSUE THREAD

**Issue by nikolaynesov** [monterail/vue-multiselect#219]
Is there any option to add a search button to the input or any plan to do that in nearest future?

**Comment by shentao** [comment]
No plans for it yet. So far you can detect the search changes by using `@search-change` for it.

**Comment by nikolaynesov** [comment]
Sure, thank you. 

I already use it to track search changes. Any chance to edit the input HTML? We only need this for call to action button and in fact the redirect will be triggered after user clicks on the list-item so the button is just to attract user and can be not functional.
