### ISSUE TITLE
Invalid props key event with latest beta version

### ISSUE THREAD

**Issue by maxKimoby** [monterail/vue-multiselect#220]
I read on the README that the key props was changed from key to track-by. Even with this, I still get this error : 

`[Vue warn]: "key" is a reserved attribute and cannot be used as component prop. 
(found in component <multiselect>)`

Install process :

`npm install --save vue-multiselect@next`

Component template:

    <multiselect
      v-model="selected_customer"
      id="ajax"
      label="name"
      track-by="id"
      :searchable="true"
      :options="customers_list"
      :internal-search="false"
      :close-on-select="true"
      :limit="5"
      @search-change="fetch_customers">
    <multiselect>

Component script : 

    import Multiselect from 'vue-multiselect'
    import axios from 'axios'

    export default {
      components: {
        Multiselect
      },
      data: function () {
        return {
          selected_customer: null,
          customers_list: []
        };
      },
      methods: {
        fetch_customers: function (term) {
          axios.get('/customers/autocomplete', {
            params: {
              term: term
            }
          })
          .then( (response) => {
            this.customers_list = response.data;
          })
          .catch( (error) => {

          })
        }
      }
     }

**Comment by maxKimoby** [comment]
Closed, dependencies problems.

**Comment by xereda** [comment]
Can you give more details of this problem?
