### ISSUE TITLE
Vue.js 2.1.6+ has "key" as reserved word

### ISSUE THREAD

**Issue by emperorjm** [monterail/vue-multiselect#221]
Because "Key" is now a reserved word it cannot be used as a PROP which is causing vue-select to crash my application.

**Comment by shentao** [comment]
@emperorjm The new 2.0 version of multiselect which is currently in a beta state is using `track-by`. Please look at the docs: https://monterail.github.io/vue-multiselect/#sub-single-select-object

**Comment by emperorjm** [comment]
Sorry. This was fixed already. When I updated composer it installed another version of vue-multiselect. I had to run npm install vue-multiselect@next again.
