### ISSUE TITLE
Set selected value inside custom multiselect component

### ISSUE THREAD

**Issue by legreco** [monterail/vue-multiselect#224]
Hello, I'm using the 2.0 beta 13 version of vue-multiselect. I would like to know how to set the selected value of multiselect when you use it in a custom component. If i try to do it via props vue js warn me about mutating a prop directly.
Case 1: In a add new line modal I would like to reset the value

Case 2: In an edit line model I would like to set all the selected value to a specific value.

#

**Comment by achchu93** [comment]
for case 1 : use :value attribute in multiselect component and make it's initial value null or empty object(if you are using object).

for case 2 : just assign value to the :value attribute property that you want to set as selected.

**Comment by legreco** [comment]
Thanks!
