### ISSUE TITLE
Enhancement - allow new tag entry to be case sensitive (taggable: true)

### ISSUE THREAD

**Issue by OliverGrimsley** [monterail/vue-multiselect#225]
(Great plugin, thanks for developing it).  

I am using 2.0 beta 13 version, works great, but . . . I would like the tag on the fly to be case sensitive so that if I enter say "Mid-Atlantic" in the search to create a new tag, I do not get "mid-atlantic".  In the mixin for the search, the code lower cases all search elements, and by doing so,  the new tag to be added is forced to lower case as well.  

Perhaps a props to make it an option?

**Comment by shentao** [comment]
I’m actually refactoring the way search works, so this shouldn’t be a problem anymore soon. :)

**Comment by predhme** [comment]
This would be a great change.

**Comment by shentao** [comment]
@OliverGrimsley, @predhme  beta.14 released. Sorry you had to wait. Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.

**Comment by acelot** [comment]
I can't understand where it was fixed? I'm on 2.0.6 and `@tag` event returns lowercased tag.
