### ISSUE TITLE
Single file import

### ISSUE THREAD

**Issue by devmsh** [monterail/vue-multiselect#226]
How can I build a single JS and CSS file import? I don't want to install an npm package and complicate my old project front-end workflow, so it will be very helpful if I can get a dist version of the JS and CSS and import it directly with my project using CDN or local static file?

**Comment by shentao** [comment]
https://unpkg.com/vue-multiselect@1.1.4 for Vue 1.x support 
https://unpkg.com/vue-multiselect@2.0.0-beta.13 for Vue 2.x support

**Comment by devmsh** [comment]
```html
<body>
<div id="app">
  Test single file import
  <vue-multiselect v-model="value" :options="options">
</div>
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<script src="https://unpkg.com/vue-multiselect@2.0.0-beta.13"></script>
<script>
var app = new Vue({
  el: '#app',
  components: { MultiSelect },
  data: {
    value: 'test',
	options: [
		'just','for','test'
	]
  }
})
</script>
</body>
```

but this error appeared:
```
Uncaught ReferenceError: MultiSelect is not defined
``` 

Any help?

**Comment by shentao** [comment]
After adding Multiselect with the `<script>` tag, it will be available as `window.VueMultiselect`, thus to use it you have to pass it like this:
```
components: { 
  VueMultiselect: window.VueMultiselect 
}
```
Remember that camelCase is translated to kebab-case in template usage. 
`VueMultiselect => vue-multiselect`
`MultiSelect => multi-select`

**Comment by devmsh** [comment]
@shentao I'm so sorry, but it seem I still miss something!

```html
<body>
<div id="app">
  Test single file import
  <vue-multiselect v-model="value" :options="options">
</div>
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<script src="https://unpkg.com/vue-multiselect@2.0.0-beta.13"></script>
<script>
var app = new Vue({
  el: '#app',
  components: { 
    VueMultiselect: window.VueMultiselect 
  },
  data: {
    value: 'test',
	options: [
		'just','for','test'
	]
  }
})
</script>
</body>
```

the new error

```
vue.js:525 [Vue warn]: Failed to mount component: template or render function not defined. 
(found in component <vue-multiselect>)
```

**Comment by devmsh** [comment]
:D Thanks man!

I use 
```
VueMultiselect: window.VueMultiselect.default
```

and it working now.

Thanks again 👍
