### ISSUE TITLE
Bring to the front

### ISSUE THREAD

**Issue by xereda** [monterail/vue-multiselect#227]
Bring to the front

How do I leave the component above all other layers?

Observe the illustration below. The vue-multiselect should, in this case, stand on top of all other screen elements. In fact, it should always stay on top of the other screen elements. I think this should be a standard match.

How do you solve this?

Thanks a lot for the help.

![7hbgrvznht](https://cloud.githubusercontent.com/assets/14337850/22307315/a2a401b8-e329-11e6-96cc-652fd412b051.gif)

**Comment by shentao** [comment]
Well, this isn’t a problem related to staying above other elements. It happens because your container styles have the `overflow` property set to `auto`. You could probably change it to `visible` and it should work then :) Without showing the scrollbar.

**Comment by xereda** [comment]
Okay, but I want multiselect to be over the footer of the modal component of Bulma css.

**Comment by shentao** [comment]
Then do the change that I suggested. Otherwise, it won’t be possible.
It’s a problem of the container – you can’t get outside of it with anything you have inside. Not just multiselect.

**Comment by xereda** [comment]
```html

<template lang="html">
  <transition name="fade">
    <div id="modal" class="modal is-active">
      <div class="modal-background"></div>
      <div class="modal-card custom">
        <header class="modal-card-head">
          <!-- Here are the title -->
        </header>
        <section class="modal-card-body">
          <form>
            <div class="columns is-multiline">
              <div class="column is-3">
                <label class="label">Cidade</label>
                <!-- Within this component is the multiselect. -->
                <dm-form-select @event="getValueField" field-name="city"></dm-form-select>
            </div>
          </div>
        </form>
      </section>
      <footer class="modal-card-foot">
      <!-- Here are the buttons -->
      </footer>
    </div>
  </div>
  </transition>
</template>

```

**Comment by shentao** [comment]
I would say try changing this class `modal-card-body`.

**Comment by xereda** [comment]
i tried:

```js

  .modal-card {
    overflow: auto !important;
  }

```

```js

  .modal-card {
    overflow: auto !important;
    z-index: 1 !important;
  }

```

```js

  .modal-card-body {
    overflow: auto !important;
  }

```

```js

  .modal-card-foot {
    overflow: auto !important;
  }

```


But I was not successful.

**Comment by shentao** [comment]
You have to change it to `visible` instead of `auto`.

**Comment by xereda** [comment]
Yeah! It's work!

```js 
  .custom {
    width: 80% !important;
    overflow: visible !important;
  }
  .modal-card-body {
    overflow: visible !important;
  }
```

Thanks a lot for the help.

**Comment by shentao** [comment]
Happy to help! :)

**Comment by xereda** [comment]
![c5lrohh8gw](https://cloud.githubusercontent.com/assets/14337850/22329304/d8528d88-e3a7-11e6-86fe-03f1fb11a6df.gif)

**Comment by shentao** [comment]
Looks great! 👍

**Comment by xereda** [comment]
Returning...

The problem using "overflow: visible;" In a Bulma modal is that I can no longer scroll when the form is larger than the screen layout.


What I effectively need is that scrolling within the modal works and that "vue-multiselect" is over all elements.

Look at the illustrations below:

![bulma_modal](https://cloud.githubusercontent.com/assets/14337850/22530737/3721e982-e8c4-11e6-852d-97fbb3f79fb6.gif)

**Comment by daenuprobst** [comment]
IMHO this is not a Bulma Modal scrolling problem. This will happen with all scrollable containers. Wouldn't it be preferable to position the dropdown list absolute, given this would mimics the behaviour of a native select? [codepen](https://codepen.io/anon/pen/gRxNgr).

**Comment by shentao** [comment]
The element is positioned absolutely within the multiselect container. What you probably mean is positioning it absolutely within the whole document, which is a bit harder to accomplish.

**Comment by tornography** [comment]
Hi there,

I ran into the same issue, and it's definitely a problem of the absolute positioned list, rather than the overflow of a parent container. As the multiselect wants to "imitate" and extend a html select element, which is overlapping any overflow (it even reaches out over the Browser), there needs to be a fix.

A solution I was working on is to set the list to `position: fixed; z-index: n;` with a calculated position to an element that acts as – as I call it – anchor. I build a little helper:

```
const calculatePosition = function calculatePosition(anchor, element) {
    const anchorBounding = anchor.getBoundingClientRect();
    const height = window.innerHeight;
    const general = ` width: ${anchorBounding.width}px; left: ${anchorBounding.left}px;`;
    let pos = `top: ${anchorBounding.bottom}px;` + general;
    if (height - anchorBounding.bottom < 200 && height - anchorBounding.top > height - anchorBounding.bottom) {
        pos = `top: inherit; bottom: ${height - anchorBounding.top}px;` + general;
    }

    element.setAttribute('style', pos);
};
```

with a method:

```
recalulateList() {
    calculatePosition(this.$el.querySelector('input'), this.$el.querySelector('ul'));
}
```
Triggering on start and, on scroll, to recalculate the position, keeping the element attached.
Hope this helps finding a solution. 

Regards,
Manuel

**Comment by ArthurShlain** [comment]
I found very interesting example with Popper.js, but it's uses old version of vue-multiselect.
https://codesandbox.io/s/0x608nxo10

**Comment by bibermann** [comment]
Why is this closed? I have the same issue in conjunction with a fixed header.

**Comment by shentao** [comment]
The v3, once it finally releases... allows for the user to provide their own implementation of the list (or the built-in but wrapped in whatever you want). You could then use popper or any other solution for that. As for 2.x, I sadly don’t have the time to work on this and I don’t want to introduce any dependencies.
If you want to help, feel free to dig into the v3 branch, look for regressions compared the current version / see if what’s there solves this problem.

**Comment by swapnilnandgave08** [comment]
I am facing this in tailwind Dialog. How would i fix this?

**Comment by benoitkopp** [comment]
Same problem in bootstrap modal, any solution ?
