### ISSUE TITLE
search-change event does not emit when input cleared

### ISSUE THREAD

**Issue by petecoop** [monterail/vue-multiselect#228]
Hey I'm using `2.0.0-beta.13`, with Asynchronous select. An issue I've come to is the `search-change` event is not fired when the input is cleared, ideally it'd send a null or empty string so I can reset my search

**Comment by shentao** [comment]
Already working on it. Having a large update mostly done (ssr, detecting position to change the location of the dropdown and some more), but I still have a problem with SSR which is blocking me from releasing it. Please be patient. :(

**Comment by petecoop** [comment]
Oh nice SSR would be great, I'll be patient 👍

**Comment by shentao** [comment]
It mostly works, but I guess I stumbled upon a Vue bug, so I am kinda blocked right now. :(

**Comment by petecoop** [comment]
:( what's the Vue bug?

**Comment by chocochaii** [comment]
FYI. I've found some clues. I got this issue as well and I noticed something.

If I type to search an option but don't select any options, then delete the searched text to empty, this issue will occur.

But after I select something, then type again and delete to empty string, the issue will not happen.

**Comment by shentao** [comment]
@petecoop https://github.com/vuejs/vue/issues/4872 This one.

**Comment by HerringtonDarkholme** [comment]
Hi. I think there is no ideal fix on vue's repo. So I would suggest to make some workaround rather than blocked by core library.

The best workaround I can think is to return a function in `default`. Otherwise you need to pack vue's source code into server bundle. For more information please refer to the corresponding issue in vue's repo.

Maybe `default` taking a function is bad design, we can have another option name like `factory`.

**Comment by shentao** [comment]
I know, I intend to ignore the issue for now as it will be fixed in Vue 2.2. However, there is a new feature incoming in Vue 2.2 that might make the changes now required for SSR obsolete. From what I know, Vue 2.2 will be able to automatically extract the CSS when on the server side.

**Comment by shentao** [comment]
@HerringtonDarkholme @chocochaii @petecoop beta.14 released and should fix this problem. Sorry you had to wait so long :(
Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.

**Comment by rjcrystal** [comment]
Is there any workaround for detecting empty query on vue-multiselect 1 ?
