### ISSUE TITLE
Override Styles - Remove Scope

### ISSUE THREAD

**Issue by frankdugan3** [monterail/vue-multiselect#23]
While scoped styles are nice in that they don't interfere with other components, they are hard to override. Since you already use BEM in your CSS, it would be trivial to remove the scoped style option and change the block selector to 'vue-multiselect'. That should prevent any interference.

This would make it much easier to override only a few CSS settings, in my case all I need to change is the colors and remove the borders/border-radius. Much less maintenance than duplicating the entire template and stylesheet with each update.

**Comment by shentao** [comment]
Hey mate! For a moment I removed the scope and now that you mention it I think I should get back to it. So here you have it, v0.2.1 with no more scoped css!

**Comment by frankdugan3** [comment]
Wow, that was quick. Thanks!

**Comment by shentao** [comment]
No problem! Sorry, removed the previous comment by accident. :(

**Comment by ianwalter** [comment]
@shentao This doesn't look like it's built into v0.2.1. I'm still getting scoped styles when I `import { Multiselect } from 'vue-multiselect';` but not when I `import Multiselect from 'vue-mulitselect/src/Multiselect'`. Just a heads up.

**Comment by shentao** [comment]
@ianwalter Hey! Good catch! Published v0.2.2 to make sure that I removed the scoped attribute.
