### ISSUE TITLE
Question: Close after clicking on selected option

### ISSUE THREAD

**Issue by azamat-sharapov** [monterail/vue-multiselect#230]
Using version 1.1.4.

When certain option is selected, and `:allow-empty='false'`, clicking on already-selected option does nothing. I would like to close dropdown instead. Is it possible without hacking core? If not, will you accept PR for this?

Thanks!

**Comment by shentao** [comment]
Sounds good. Would gladly accept a PR with this functionality! :D

**Comment by azamat-sharapov** [comment]
Should we introduce new prop for this (like `close-on-selected-click` or whatever you may suggest) or just closing on `:allow-empty='false'` is fine?
