### ISSUE TITLE
Clicking or pressing enter on a new tag doesn't close the dropdown in single select

### ISSUE THREAD

**Issue by innominata** [monterail/vue-multiselect#231]
`if (this.closeOnSelect && !this.multiple) this.deactivate()`
on line 416 of multiselectMixin.js seems to fix it, this.deactivate() is only being called if this.multiple is true.

I'd do a pull request, but I have a) no idea if this is desired functionality (tho I can't imagine why) and b) no idea what I'm doing re: github

Cheers :)

**Comment by shentao** [comment]
I'd welcome such PR, so feel free to send it to me! :)

**Comment by innominata** [comment]
Done :)
