### ISSUE TITLE
Separate CSS

### ISSUE THREAD

**Issue by ecmel** [monterail/vue-multiselect#232]
Hi, is it possible to produce a separate CSS file for npm distribution?

**Comment by shentao** [comment]
I'm working on SSR support right now and having a separate css file is a side-effect of supporting SSR. So after I'm done, the css file will be available on npm.

**Comment by shentao** [comment]
@ecmel beta.14 released and should fix this problem. Sorry you had to wait. Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.
