### ISSUE TITLE
Tagging: with multiple 'multiselects' on page

### ISSUE THREAD

**Issue by eybarta** [monterail/vue-multiselect#233]
Thanks for this amazing plugin.

I'm trying to use multiple single tag selectors with ability to 'add new tag'..

Using:

`
<multiselect
                                            placeholder="Select brand or type"
                                            :taggable="true"
                                            :selected="brand.selected"
                                            :options="brand.options"
                                            @update="updateBrand"
                                            @tag="addTag">
                                        </multiselect>
`

The addTag method only returns the newTag string, but I also want to return
the 'brand' prop so I know which multiselect returned which tag..

In your API documentation you write Event > Tag has attributes > (searchQuery, id)

I'm not sure what the 'id' refers to, but could you please explain how I return
the query (newTag) and either the element it came from or my own prop?

thank you

**Comment by shentao** [comment]
Thank you! 😄 

The `id` comes from the prop `id` that you can pass to the component. This can be used to identify the dropdown that triggered the event.
See: https://monterail.github.io/vue-multiselect/#sub-props for the prop list and description. Each of the events sends the `id` as the second argument.

This should fix your problem :)

**Comment by eybarta** [comment]
thanks bro,

forgot to actually put the ID attr on the element :) my bad..

**Comment by shentao** [comment]
Sure, no problem! :D
