### ISSUE TITLE
Uncaught ReferenceError: Multiselect is not defined

### ISSUE THREAD

**Issue by legreco** [monterail/vue-multiselect#236]
Hello, I m using laravel 5.3 and vue js 2.0. How to use register vue js globally?
I have put  
`import Multiselect from 'vue-multiselect';`
`Vue.component(Multiselect);`
in my app.js file and gulp all

in my vue instance i have: 
`......`
`   components: { Multiselect },`
`.....`
`

but i get "Uncaught ReferenceError: Multiselect is not defined" in my console.

**Comment by shentao** [comment]
Hey!
If you registered the component with `Vue.component(Multiselect)` then you don’t have to declare it inside the Vue instance / components anymore. :)

**Comment by legreco** [comment]
I remove the component declaration inside my vue instance but i get an another error.
When i tried:
`import Multiselect from 'vue-multiselect';`
`Vue.component('multiselect',Multiselect);`
in my  app.js it works.
i am wondering why?
Anyway thank a lot for your help!

**Comment by shentao** [comment]
I guess it might depend on how you build setup looks like, but it’s hard to say without more details.
This might be helpful. I usually do local registration just in components that actually will use Multiselect inside.
https://vuejs.org/v2/guide/components.html#Registration
