### ISSUE TITLE
Close drop down after adding tag.

### ISSUE THREAD

**Issue by eybarta** [monterail/vue-multiselect#237]
I'm using tags with single select to allow the user to select or add new option.. 

When the user enters text and hits enter I invoke @tag with addTag() but I also
want the dropdown to close without having to tab out, is there a close() function 
I could use for this? or a prop that does it? (:close-on-select doesn't work for this)

thx for your help :)

**Comment by shentao** [comment]
I will double check the `:close-on-select` implementation to make sure it work the same when tagging and simple selecting. :)

**Comment by bovisp** [comment]
I, too, would like to see this functionality. Great component though!

**Comment by shentao** [comment]
Fixed, should be released today/tomorrow.

**Comment by bovisp** [comment]
@shentao. Many thanks for fixing this!

**Comment by eybarta** [comment]
Awesome, thank you!!

**Comment by shentao** [comment]
@bovisp @eybarta beta.14 released and should fix this problem. Sorry you had to wait. Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.
