### ISSUE TITLE
Bug with css on the demo website

### ISSUE THREAD

**Issue by Landen13** [monterail/vue-multiselect#238]
Screenshot was made in Mozilla Firefox 51.0.1

http://dl3.joxi.net/drive/2017/02/01/0007/0745/492265/65/e1d96b8c20.jpg

I'm not sure if this is issue for repository, but I suppose it should be fixed asap :)

**Comment by shentao** [comment]
This might be related to some of the badges not loading properly. :( If they don’t start working in the coming days I guess I would have to remove them.
Thanks for pointing it out!

**Comment by Landen13** [comment]
It can be fixed with following css changes:

`.multiselect__option {
    display: flex;
    justify-content: space-between;
    align-items: center;
}
.badge__img {
    float: right; // remove
}`

**Comment by shentao** [comment]
Fixed. Should be online soon.
