### ISSUE TITLE
Custom css in custom-label

### ISSUE THREAD

**Issue by AlexeyShaykov** [monterail/vue-multiselect#240]
Hi, @szymo.

Thanks for your plugin. 
I wanted to ask whether it is possible to apply a style in custom-label?
For example:
https://monterail.github.io/vue-multiselect/#sub-select-with-search
make Vue.js - green color; [JavaScript] - red color?

**Comment by shentao** [comment]
You would have to use the custom template functionality to accomplish this. That's really easy if you're using Vue 2.x and is done with scoped slots.

**Comment by AlexeyShaykov** [comment]
Thanks

**Comment by mwei0210** [comment]
Hi Alexey, did you mean custom template for multiselect_tag? I could not find named slot for tag, but there is only name slot for option. Thanks @AlexeyShaykov

**Comment by shentao** [comment]
@mwei0210 From what I understood he asked for options. You can modify them through scoped slots.
As for tags, this is not yet possible however, there are discussion related to adding an option to provide a custom template/slot for the selected options.

**Comment by mwei0210** [comment]
@shentao Opss, supposed to tag you instead hahaha. Alrighty! Looking forward to customizing the tag too! Thanks for making it clear.
