### ISSUE TITLE
CDN is not working

### ISSUE THREAD

**Issue by murilolivorato** [monterail/vue-multiselect#247]
Hello my friend , this CDN is not workig for vue 2.0  -

<script src="https://cdn.jsdelivr.net/vue.multiselect/1.1.4/vue-multiselect.min.js"></script>

AND this -
<script src="https://cdn.jsdelivr.net/vue.multiselect/2.0.0-beta.13/vue-multiselect.min.js"></script>

Is not working property , it has some errors when I select the component .

**Comment by shentao** [comment]
Please try https://unpkg.com/vue-multiselect@2.0.0-beta.13
