### ISSUE TITLE
Change the hover green color 

### ISSUE THREAD

**Issue by murilolivorato** [monterail/vue-multiselect#248]
Hello , My friend .
Thanks for sharing this code with us .
How could I change with css the green Hover color of the select box ?

I tried like this -

div.multiselect li:hover{background-color:#467993!important;}
div.multiselect a:hover{background-color:#467993!important;}
ul.multiselect__content li a:hover{background-color:#467993 !important;}

But I was o success .

**Comment by shentao** [comment]
Hey! 
The hover is done with JS (adding the `.multiselect__option--highlight` class.
```
.multiselect__option--highlight {
  background: #41B883;
  outline: none;
  color: white;
}
```
This is the rule you have to modify.

Hope that helps!

**Comment by jerearaujo03** [comment]
Not working for me!

**Comment by jerearaujo03** [comment]
I was able to do it by using <style> instead of <style scoped>

**Comment by shentao** [comment]
Oh yeah. You can’t use `scoped` as the multiselect component won’t have the correct `data-[hash]` attribute. You could try with a deep selector `>>>` but I’d say it’s better to just make it a global CSS rule.
