### ISSUE TITLE
Question: How can I make an option selected by default?

### ISSUE THREAD

**Issue by masoudmemariani** [monterail/vue-multiselect#250]
Hi, 

How can I make an option selected by default? I have a single-select multiselect tag which gets its options from a parent component. 
Thanks for the great component!

Regards
M

**Comment by shentao** [comment]
Hey! 

Use the `:value` prop (Vue 2.x) or `:selected` (Vue 1.x).

**Comment by masoudmemariani** [comment]
:value works. thanks you! 👍

**Comment by digitalit** [comment]
Could you please give me an example of this.

My code

```
<multiselect
                                    id="type"
                                    v-model="type"
                                    :value="null"
                                    :options="projectfilteroptions.typeoptions"
                                    placeholder="Välj projekttyp"
                                    label="type_label"
                                    track-by="type"
                                    @input="changeType">
</multiselect>
```

I want my value from Vuex store "projectfilters.type" set the current selected.

Thank you

**Comment by Aravinda93** [comment]
@digitalit Have you found answer for the `multiselect` default selection? I tried `:value` and `:selected` but both does not seem to work. Any suggestion that may have worked for you?

**Comment by digitalit** [comment]
> @digitalit Have you found answer for the `multiselect` default selection? I tried `:value` and `:selected` but both does not seem to work. Any suggestion that may have worked for you?

Hi @Aravinda93,

I now use Quasar Framework so this is not an issue for me anymore.

Have a nice day.

**Comment by Aravinda93** [comment]
@digitalit Thanks a lot for the response. You too have a nice day :)
