### ISSUE TITLE
Reserved Keyword Errors in console

### ISSUE THREAD

**Issue by bushcode** [monterail/vue-multiselect#251]
I tried to replicate some of the examples on the demo website but I keep getting errors including "key" is a reserved attribute and cannot be used as component prop. 
(found in component <multiselect>)"  in the console. Am I doing something wrong?
![screen shot 2017-02-07 at 15 28 17](https://cloud.githubusercontent.com/assets/24473025/22695227/57cf3fce-ed4a-11e6-859c-d5c396e9d921.png)

**Comment by enlore** [comment]
https://github.com/vuejs/vue/blob/769c4dc2032251323c8f61ad8eba2c26c615a618/src/core/instance/state.js#L38

**Comment by shentao** [comment]
Hey! 
Please make sure you’re running the correct version of Multiselect according to your Vue.js version.

Vue 1.x -> Vue-multiselect 1.x
Vue 2.x -> Vue-multiselect 2.0-beta (can be installed with `npm install vue-multiselect@next`)

This should fix the problem!

**Comment by bushcode** [comment]
@shentao Thank you. That fixed the problem.
