### ISSUE TITLE
Custom Template for the Selected Chips in Multiselect

### ISSUE THREAD

**Issue by roylkng** [monterail/vue-multiselect#255]
I am using multi-select to select from 3 groups of items, when a user selects item from group-1 I want to add group name in prefix of the selected item when it displayed in selected items in input bar, similarly for rest groups of the groups.

**Comment by shentao** [comment]
I guess `:customLabel` is the functionality you look for.
Look into the documentation for an example: https://monterail.github.io/vue-multiselect/#sub-select-with-search

**Comment by cloud-tribal** [comment]
@shentao Does custom-label take HTML or just text? Not quite clear

**Comment by roylkng** [comment]
CustomLabel is only for the options in dropdown there is no variable which binds with the already selected options displayed in input bar of multiselect. These are two different things drwopdowns options vs selected option.

**Comment by shentao** [comment]
@cloud-tribal @roylkng `customLabel` only works with text and appears both in the selected options and in dropdown options.
Custom templates work only for the dropdown options though.

**Comment by roylkng** [comment]
@shentao  customLabel return the option value to the custom template which is used,  and you are right that same value is passed to selected options, and that is the exact problem. Need another custom template or variable which binds with value of the selected options. Because customLabel of dropdown options can't be changed when it is selected.

**Comment by shentao** [comment]
You can use scoped slots (aka custom templates) for dropdown options and `customLabel` for selected options. have you tried this?

**Comment by roylkng** [comment]
@shentao nope, actually i don't know how to do that, i thought customLabel returns option for custom templates , can you please help me with an example of how its done

**Comment by shentao** [comment]
@roylkng https://monterail.github.io/vue-multiselect/#sub-custom-option-template 

You can provide any HTML you want. You can actually even use components inside (functional ones would do best). Example from the docs:
```
<multiselect v-model="value" placeholder="Fav No Man’s Sky path" label="title" track-by="title" :options="options" :option-height="104" :custom-label="customLabel" :show-labels="false">
    <template slot="option" scope="props">
      <img class="option__image" :src="props.option.img" alt="No Man’s Sky">
      <div class="option__desc">
         <span class="option__title">{{ props.option.title }}</span>
         <span class="option__small">{{ props.option.desc }}</span>
      </div>
   </template>
</multiselect>
```

**Comment by roylkng** [comment]
Thanks @shentao . But can we get HTML input for customLabel as well.

**Comment by shentao** [comment]
Not really for customLabel but rather for selected options, you mean. I guess that’s possible. :)

**Comment by roylkng** [comment]
Yes  i meant selected options, looking forward for the feature. Thanks man.

**Comment by shentao** [comment]
Implemented custom slot for tags (selected options). Will be released soon.

**Comment by bouchezb** [comment]
Hello,

I'm trying to use the `tag` slot to modify the tags display to show flags icons next to country names.
I'm using it like this (after looking into source code)

```html
<template slot="tag" scope="props">
  <span class="multiselect__tag">
    <span :class="'mr-2 flag-icon flag-icon-' + props.option.code.toLowerCase()"/>
    <span>{{props.option.name}}</span>
    <i aria-hidden="true" tabindex="1" @keydown.enter.prevent="removeElement(option)"  @mousedown.prevent="removeElement(option)" class="multiselect__tag-icon"></i>
  </span>
</template>
```
I have an issue on the delete link.
If i don't set `@keydown.enter.prevent="removeElement(option)"  @mousedown.prevent="removeElement(option)"` tags can't be deleted.

If i set it, i have an error message 

`Property or method "removeElement" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.`

I think i don't use this correctly, but i'm not able to find a solution.
How can i reference the native `removeElement` method in my custom template (or not but, be able to delete tags)?

Regards.

**Comment by bouchezb** [comment]
@arunrreddy i did not solved it, i think this is an evolution of the tag system. Maybe a new slot or an update of the current slot `tag` can be the solution, but i'm not a Vue.js master. Sorry.
Maybe @shentao can give us some tips ?

**Comment by arunrreddy** [comment]
The only way we can delete selected tags right now is to select on the option already selected if it is available in the drop-down. @shentao Is there a way to access the removeElement method written for the action triggered on clicking the delete icon on a tag.

**Comment by arunrreddy** [comment]
Works like a charm! Thanks a lot!

**Comment by luyandasiko** [comment]
@jaybones90 Thank you this it was very helpful for me :-)
