### ISSUE TITLE
Custom search interfering with option groups

### ISSUE THREAD

**Issue by espiegel** [monterail/vue-multiselect#256]
Does anyone have a working example of `:internal-search="false"` working with option groups (I.E. groupLabel="..." groupValues="...") ?

The option groups work fine until I add `:internal-search="false"` and then the grouping doesn't show up anymore. It seems as though those two features are mutually exclusive.

I'm using Vue 2.1.10 and vue-multiselect 2.0.0-beta.13

**Comment by shentao** [comment]
I didn’t consider this use case but you’re right. Groups heavily depend on the search mechanism, which in the case of groups is a bit fancier. It additionally flattens the list so it can be displayed inside the dropdown and drops the group label for empty groups.

Please follow the below function. 
https://github.com/monterail/vue-multiselect/blob/2.0/src/multiselectMixin.js#L281

If you want to use both groups and external search, you will have to recreate a similar set of methods.

**Comment by espiegel** [comment]
Are there any plans to support these two features together in a future release?

**Comment by shentao** [comment]
Now that you suggest it, I think it might be possible if I decouple the flatting of the results from the search mechanism.

**Comment by shentao** [comment]
@espiegel beta.14 released and should fix this problem. Sorry you had to wait so long :(
Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.

**Comment by espiegel** [comment]
thanks

**Comment by espiegel** [comment]
> Breaking change regarding the styles.

Does that mean I have to use:
`<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>` in the parent component of vue-multiselect? For some reason if I don't add that then the multiselect css doesn't work

**Comment by espiegel** [comment]
Btw, did you upgrade `http://monterail.github.io/vue-multiselect` to version beta 14?

**Comment by shentao** [comment]
Not yet. I kinda released it in a break between talks at a conference. I will update the docs tomorrow. And also add the release notes. The important change is in the 2.0 branch readme.

Yes, this is what you have to add, because the css is now separated. Also you can those styles to your static assets / vendor files.
