### ISSUE TITLE
Problem with selected value by default

### ISSUE THREAD

**Issue by cpfarher** [monterail/vue-multiselect#259]
If you used it in VueJs 2 with the option :value and pass a method or a computedProp to value like:
`:value = "myMethod(2)"`

and 
```
methods: {
  myMethod: function (id) {
    return something
  }
}
```
This error appeared: 
`vue.common.js?e881:435 TypeError: this.internalValue.slice is not a function(…)`

With some data defined in data all works fine....

**Comment by shentao** [comment]
Interesting. I have to check whether doing something like this passes down a function or primitive/array. 

Also please make sure that if you have `:multiple="true"` you have to make sure that `:value` is an Array.

**Comment by cpfarher** [comment]
yes, I pass a function which return an array...... The array is the same that I pass on data properties. So, the same data in data of vue works fine, but when return as a function  in a method or computed properties does not work

**Comment by cpfarher** [comment]
Ignore this bug. It is a bug of my code :+1: 
It works fine with computed prorperties!
