### ISSUE TITLE
Roadmap question - will there be ordering/sorting support for multiselect?

### ISSUE THREAD

**Issue by lbjones** [monterail/vue-multiselect#26]
This is a great component, thank you!

I'm curious if you have in mind adding support for reordering items with mouse drag and drop?

I'm making an email contact box, which needs tagging, remote loading, custom delimiters, and reordering support.  No project that I've found seems to support all of this completely bug free.  I'd be willing to contribute to this project to help get there.  But since everyone has their own needs, it seems that most multiselect components suffer from massive bloat after time.  Having a clear roadmap may help with that.  If you'd rather not support one or more of these features just let me know.

**Comment by shentao** [comment]
Hey @lbjones! Thanks for your kind words!

**Tagging, remote loading, and custom labels are supported right now.**
However, even if drag and drop reordering sounds interesting I believe this wouldn’t fit into the component’s scope. Introducing such functionality would additionally increase the complexity of the component. Cases, where you need to reorder the dropdown elements or tags are quite rare. Such cases usually also require some additional changes which bring you to the point of writing the solution yourself. 

There is, however, something we could do about it.
Right now it is possible to just import the underlying logic of the component as mixins. I’m thinking of creating some kind of example components/templates that would utilize those mixins. For example, it could be very easy to create search boxes similar to those of IMDb, Facebook or Slack’s `cmd+k` jump functionality. 
Or some things with drag and drop support that could match your problem!

Right now the component itself (without the mixins) is just a template with data and event bindings, css styles and some javascript related to showing on-highlight labels and so on. All core features are in mixins. 

About the roadmap: There are 2 major enhancements and few more I want to introduce: 
* **Option grouping**
* **Better mobile support**
* Stateless dropdowns (with no selected prop, just action pickers / search boxes)
* RTL support, accessibility
* Examples of custom components / templates ready to use in project
* Reworking the documentation to include much more examples and use cases

**If you wish, we could work together on a example template/component that would extend the use vue-multiselect with drag & drop support and more!**
Let me know if you are interested.

Cheers!

**Comment by lbjones** [comment]
Hey that sounds awesome!  I'm a bit new to vue and coming from angular development.  I've been looking through your code and I'll see how this all works, but I can see I have much to learn.

So you are saying that we should create a new project that is a fork of this one?  Or is there a way to import the mixins as a dependency?

**Comment by shentao** [comment]
That's exactly my story - coming from angular development. 

In Readme.md there is an example on how to create new components using the mixins and which to import.

http://vuejs.org/guide/mixins.html

So you can just create a new component in the docs and import those. 

If we manage to create some more examples we can create new projects that would use this one as dependency. What do you think about such approach?

**Comment by shentao** [comment]
You can use the src/Multiselect.vue as an example on how to build a component that uses the mixins.

**Comment by lbjones** [comment]
Right on, sounds great!
