### ISSUE TITLE
selected object not displayed

### ISSUE THREAD

**Issue by joshua1** [monterail/vue-multiselect#260]
I have an issue where the selected value is not displayed. the v-model object gets assigned the selected object but this is not displayed in the multiselect (still displays the placeholder string). What am i doing wrong. see my markup below

```
<div class="col-sm-7 col-md-7 col-lg-7">
                        <multiselect name="location" v-model="location" :options="this.$store.state.flight.airportList" :close-on-select="true" :clear-on-select="false" placeholder="Departing from ..." label="text" track-by="id"></multiselect>
                    </div>
```
<img width="1331" alt="screen shot 2017-02-12 at 8 14 37 pm" src="https://cloud.githubusercontent.com/assets/557293/22864768/ed070964-f15f-11e6-9a6e-ea933da4a973.png">
<img width="1291" alt="screen shot 2017-02-12 at 8 14 20 pm" src="https://cloud.githubusercontent.com/assets/557293/22864769/ed0abe06-f15f-11e6-850f-54502f843940.png">

**Comment by shentao** [comment]
I can’t see any errors in the markup. You might try to remove the `:clear-on-select` prop. Also there is no prop `name`.

**Comment by joshua1** [comment]
Thanks for responding @shentao , i have removed the name prop as well as ```:clear-on-select``` still no joy

**Comment by shentao** [comment]
Could you try moving the vuex source to a computed value? Also, I’m not sure about `this.` from `this.$store...`. You shouldn’t be using `this` inside the template.

**Comment by joshua1** [comment]
passing a computed property to options , i get the same thing , still not displaying the selected option. my selected object looks like this ```
{
id:"UAK"
latitude:"61.160517"
longitude:"-45.425978"
text:"Narsarsuaq,(UAK),Narssarssuaq,Greenland"
}
```
i expect the text property to be displayed when this object is selected

**Comment by joshua1** [comment]
I took out the ```close-on-select``` and it started working as expected. Thank you @shentao
