### ISSUE TITLE
Question: Can I use getters for the label?

### ISSUE THREAD

**Issue by risc12** [monterail/vue-multiselect#261]
I want to create field where I can select one user, it's label should be 'name'. The only problem is that 'name' is a getter which combines the firstname with the lastname.

The list shows the name nicely, but the selected value does not seem to work... Am i doing something wrong?

`<multiselect
      v-model="selectedElement"
      label="name"
      track-by="id"
      :options="relationshipCollection"
      :loading="inRequest"
    ></multiselect>`

**Comment by shentao** [comment]
Hey! You can use `:customLabel` for this functionality. See docs for an example. :)
