### ISSUE TITLE
Component remove necessary space from the right end of a query string.

### ISSUE THREAD

**Issue by pastdevr** [monterail/vue-multiselect#266]
For example, when we search for location st. louis and start type `'st. '` then `'louis'` we will see no space.
I think it because of `String.prototype.trim()` function in this code
`
updateSearch (query) {
  this.search = query.trim().toString()
}
`

**Comment by pastdevr** [comment]
I was trying to change `trim()` to `trimLeft()` or completely do not touch query string
it lead to emitting `search-change` event with an empty query

**Comment by shentao** [comment]
Hey! This is already fixed and will be published with the next release. I hope to *finally* do it this weekend...
