### ISSUE TITLE
Search multiple fields

### ISSUE THREAD

**Issue by nunob87** [monterail/vue-multiselect#273]
hello,
How do I search in multiple fields

search: 123 or test
[
{code: '123', label: 'test', ...},
...
]

thanks

**Comment by shentao** [comment]
By providing a custom search implementation using `@search-change` and turning `:internal-search="false"`.
See http://monterail.github.io/vue-multiselect/#sub-asynchronous-select for an example. It is called ajax search, but it also shows how to use multiselect with your own search mechanism.
