### ISSUE TITLE
 Icon support

### ISSUE THREAD

**Issue by xereda** [monterail/vue-multiselect#275]
Does the component have icon support? My need was to include an icon on the left side of the field.

Example:
![captura de tela 2017-02-20 as 17 39 03](https://cloud.githubusercontent.com/assets/14337850/23141033/8c858586-f793-11e6-89a8-4460db66548d.png)

Thank you for your help.

**Comment by shentao** [comment]
Yes, you just have to customize the CSS a bit to include a before element with the icon and adjust the padding-left accordingly.
