### ISSUE TITLE
when  vue version 2.1.10 meet error _h is not defined

### ISSUE THREAD

**Issue by aeolusheath** [monterail/vue-multiselect#279]
[Vue warn]: Error when rendering component <vue-multiselect>: 
Uncaught ReferenceError: _h is not defined
![image](https://cloud.githubusercontent.com/assets/5978548/23203127/1852dc7e-f91c-11e6-9a31-9fbdcbae4236.png)

vue-multiselect version is 2.0.0-beta.13

**Comment by shentao** [comment]
Weird. Will have to check what might have gone wrong.

**Comment by aeolusheath** [comment]
@shentao  bro  I reboot the project .  the error is not like content above. 
it's like this
![image](https://cloud.githubusercontent.com/assets/5978548/23207429/3c1550b4-f92c-11e6-97e2-c10bdbfda21a.png)

**Comment by shentao** [comment]
Can you show me the markup and data that you pass into multiselect?

**Comment by aeolusheath** [comment]
@shentao  
really sorry. 
it's the data 's issue that pass into component because of my incaution. 
it's nothing to do with your nice component.
