### ISSUE TITLE
Trigger @select Event manually

### ISSUE THREAD

**Issue by achchu93** [monterail/vue-multiselect#280]
Hi there,

I have two dropdowns and one dropdown is getting filled based on the first dropdown selection. So on the first dropdown @select event i fill data to the second one. In a scenario i manually select the first dropdown value. So when i do that i wanna trigger the @select event manually. Is there any possibilities?

Thanks in advance.

**Comment by shentao** [comment]
You don’t have to trigger `@select` on the second dropdown if you know the data you want to add to the value. Just push it to the value of the second dropdown.
Is this what you mean?

**Comment by achchu93** [comment]
No, what i want to do is i wanna fill the second dropdown on first dropdown @select event.. so when we manually set the selected item to first dropdown no events are triggered.therefore i cannot fill the second dropdown..events are triggering on user interact..so my question is there any way to identify the selected item change, when we manullay set selected item?

**Comment by achchu93** [comment]
Still finding a solution..any solution for this author? @shentao

**Comment by shentao** [comment]
You can trigger the update function for the other multiselect from inside of the `@search` handler of the first multiselect.

Reopen if this is still valid issue.
