### ISSUE TITLE
Clicking 'X' on any item in multiselect always removes last item

### ISSUE THREAD

**Issue by evanb2** [monterail/vue-multiselect#282]
![2017-02-24 at 9 59 am](https://cloud.githubusercontent.com/assets/11276439/23314726/0af0c296-fa78-11e6-9bf4-60313754bdc6.gif)

Here are my settings:
```
<multiselect class="order-select__input--dropdown"
                 :options="selection.options"
                 label="description"
                 :loading="loading"
                 :disabled="disabled"
                 :selected="selected"
                 @update="selectionChange"
                 :multiple="isMultiple"
                 :hide-selected="isMultiple"
                 :name="identifier">
</multiselect>
```

**Comment by SirLamer** [comment]
Personally I don't get this behavior. What does your "selectionChange" event method look like?

**Comment by evanb2** [comment]
```
selectionChange(selected) {
  this.$set('selected', selected);
},
```

**Comment by shentao** [comment]
Which version of multiselect are you using? In the v2-beta version you have to pass `:value` instead of `:selected`.

**Comment by evanb2** [comment]
@shentao I'm using `v1.1.4` with Vue `v1.0.16`

**Comment by evanb2** [comment]
@shentao can I use v2-beta with Vue v1?

**Comment by evanb2** [comment]
Code:
```
<multiselect :options="insuranceCodeOptions"
                     name="insurance-codes"
                     label="name"
                     v-model="insuranceCodes"
                     :show-labels="false"
                     :multiple="true"
                     :searchable="false"
                     :close-on-select="false">
</multiselect>
```

**Comment by shentao** [comment]
Hey! Please use the 2.0.3 stable release instead of the beta.

**Comment by evanb2** [comment]
@shentao Updated with same result. Ideas?? lol

**Comment by shentao** [comment]
Not yet. Will have to debug it myself :(

**Comment by dannynicolas** [comment]
There's actually a pull request that fixes this!  Hopefully it can get merged in. 
https://github.com/shentao/vue-multiselect/pull/614

**Comment by Owlnofeathers** [comment]
Also seeing this behavior, would be nice to get #614 merged in

**Comment by shentao** [comment]
To anyone still having this issue. Please read the docs: https://vue-multiselect.js.org/#sub-single-select-object on how to work with an *array of objects*.
