### ISSUE TITLE
Is there a way to disable the new behaviour where the "dropdown" becomes a "dropup"?

### ISSUE THREAD

**Issue by jazoom** [monterail/vue-multiselect#285]
I've noticed that in the new beta the dropdown actually goes up on short devices. This isn't helpful because there's actually about 5px of room above the multiselect box so almost all of the "dropup" is hidden.

I just want it to dropdown.

**Comment by shentao** [comment]
Oh, my bad. Didn’t thought about such case, sorry! I will introduce a prop for controlling this behavior. Thanks for noticing!

**Comment by jazoom** [comment]
My pleasure. I'll await your fix.

**Comment by jazoom** [comment]
Shouldn't this be considered a bug since the behaviour I'm seeing is dropup where there is no space (essentially you can't see it) when there is about half a phone screen worth of space underneath? It also breaks the rule of least surprise.

I don't think we can really call this an "enhancement".

**Comment by nikolaynesov** [comment]
We started testing the app on mobile phones and it became a problem. We use vue-multiselect on a lot of pages and that became unusable. It is hard to interact with dropup. I think the best way for mobiles would be to make the dropdown after clicking on it a full-screen with the cross to close it and probably the search field. But for now is it possible to add an option to disable dropup in next beta?

**Comment by shentao** [comment]
Planning to introduce this in the next beta.

**Comment by hurradieweltgehtunter** [comment]
did you do anything there yet? Having the same problem.
ty

**Comment by jazoom** [comment]
Is this still going to be implemented?

**Comment by shentao** [comment]
Implemented. Will be available in the next release.

**Comment by gerardreches** [comment]
I can't find a prop for this in [the docs](https://vue-multiselect.js.org/#sub-props). How was it named?

**Comment by shentao** [comment]
`open-direction="bottom"`

**Comment by gerardreches** [comment]
Hmm... I'm trying with `open-direction="up"` and the options still opens below the select.

![multiselect](https://user-images.githubusercontent.com/7549815/34114810-05738aac-e414-11e7-8da5-9d225007039b.png)
