### ISSUE TITLE
Error on gulp --production

### ISSUE THREAD

**Issue by tintinboss** [monterail/vue-multiselect#29]
Hi, I'm facing this error while trying to run `gulp --production` [complies fine when running gulp --dev].
Using elixir and mix.webpack()
Elixir version: ^4.2.0
Gulp version: 3.8.8
npm version: 2.14.12
nodejs version: v4.2.4

Error on console:
`- public\js\app.js

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error
  at new JS_Parse_Error (<anonymous>:1526:18)`

Thanks in advance for the help!

**Comment by shentao** [comment]
I would need some more data to provide any help. How does your gulp and webpack configs look like? What are the differences in webpack prod and dev configs? Where do you handle minimization and so on?

**Comment by tintinboss** [comment]
@shentao : Thank you for your response! The problem was in my webpack configuration. I had to set `babel` as loader and all went fine.
Thank you so much for the beautiful work!

**Comment by shentao** [comment]
Och! I’m glad to hear that.
However, I still wonder why didn’t it work before as the component is already transpiled to es5 so it should not require Babel to work. But maybe there is some other stuff going on (like es6 imports or so) that would require it.

**Comment by SirLamer** [comment]
As an update for those who arrive here in the future, as of Laravel 5.3 (and presumably on, but please verify) it's easier to use Buble instead of Babel because the former ships with Laravel.

```js
module.exports = {
    module: {
        loaders: [{
            test: /\.js$/,
            loader: 'buble'
        }]
    }
};
```
