### ISSUE TITLE
Setting value of single select to null throws errors

### ISSUE THREAD

**Issue by pstephan1187** [monterail/vue-multiselect#290]
The current implementation allows a single select box to start with a null value. However, once you select an option and then programmatically set the value back to null, it breaks. I have found that you must programmatically set the value to an empty array. This doesn't make sense semantically. You aught to be able to set the value of a single select to null, definitely not an empty array. I hope that makes sense.

**Comment by nikolaynesov** [comment]
It relates to PR: #264

**Comment by shentao** [comment]
Hey @pstephan1187. Just like @nikolaynesov said, it is related to a newly introduced bug in the beta.14 release. I hope I can manage to publish a new release today. More info inside the #264

**Comment by nikolaynesov** [comment]
@shentao tried to install the package directly from the repo with
"vue-multiselect": "https://github.com/monterail/vue-multiselect.git#fix-value-clear-error"
to include the fix into beta.14, but looks like it does not publish the dist files. Is there any way to install it like that (directly)?

**Comment by nikolaynesov** [comment]
@stephan1187 There is still no release with that fix, so this is how I managed to make **beta.14** work. (I hope it will help)

1. Fork the repo
2. Update your package.json to

` "vue-multiselect": "https://github.com/your_account/vue-multiselect.git#fix-value-clear-error"`
3. No need to include styles separately
4. Add alias to webpack config:
`
module.exports = {

    output: {
        publicPath: "/assets/js/"
    },
    resolve: {
        alias: {
            'vue-multiselect': 'vue-multiselect/src/Multiselect.vue'
        }

    }

};

`
5. npm update

**Comment by shentao** [comment]
Should be fixed in the just released beta.15. :)

**Comment by nikolaynesov** [comment]
@shentao Are you going to update github tags/releases?
![screen shot 2017-03-09 at 11 42 59](https://cloud.githubusercontent.com/assets/17743574/23744685/dd0babe8-04bd-11e7-9396-0a6859da012e.png)

**Comment by shentao** [comment]
Yeah, probably today. It's a large release.

**Comment by nikolaynesov** [comment]
@shentao is there any way to get breaking changes list for **beta.15** since **beta.14** before you update tags/releases?
