### ISSUE TITLE
Start searching when clicking on a button

### ISSUE THREAD

**Issue by shyamchandranmec** [monterail/vue-multiselect#291]
Hi, 
  I want to configure this in a way where the user enters the search text and then clicks on the search button next to the multi-select to trigger the search. The search text can be something which is not in the options list.

 But the moment the user clicks outside the multi select the entire value is reset to empty string.
The value persists when I press Tab or Enter key. I want the value to persist even on mouse down.
Any way to achieve this.

**Comment by Reiss-Cashmore** [comment]
+1 Is there any way of achieving this ?

It would be good if there was an option for disabling the auto clear on a loss of focus.

I am aware however that we might be trying to use this tool for a purpose it was never intended for, I'm not sure if the scope of what we want to do should be within the vue-multiselect library

**Comment by shentao** [comment]
Added a `clear` slot that accepts `search` as prop (current search query). This, combined with `:internal-search="false"` makes it possible to trigger searching when clicked.
It also makes it possible to create a *clear-all* button. Or both if you use a `v-if / v-else` combination.
