### ISSUE TITLE
How to keep the input persist when the user clicks on the input

### ISSUE THREAD

**Issue by shyamchandranmec** [monterail/vue-multiselect#292]
Assume the searchable multiselect already has a text "project one". When the user clicks on the input the text becomes empty. But when I click outside it comes back. 

I want the text input to persist and let the user press backspace to remove it.
How to achieve this?

**Comment by asvae** [comment]
Possibly duplicate of #203.

**Comment by shyamchandranmec** [comment]
@asvae . I ended up making my own library 😄 . Thanks for the reply

**Comment by asvae** [comment]
@shyamchandranmec Believe it or not, but I did the same. :)

**Comment by shentao** [comment]
You can submit a PR with additional config to not clear the input (search) value inside `activate` and/or `deactivate` methods. That should do the work.
