### ISSUE TITLE
Requires vue 2.2+

### ISSUE THREAD

**Issue by OliverGrimsley** [monterail/vue-multiselect#293]
Just a note:  I upgraded to the Vue 2 beta 14 release of this plugin and was using Vue 2.1.10, and the component was firing emissions but the parent was not _receiving_ them.   I upgraded to Vue 2.2.0 and now the parent receives emissions and is working again.  In case anyone else is thinking "ahh what happened to my parent component" (you may want to update the composer json file to require the new vue 2.2+ release).

**Comment by shentao** [comment]
Added vue 2.2+ as peer dependency. Thanks!
