### ISSUE TITLE
Input appears unstyled in v2.0.0-beta.14

### ISSUE THREAD

**Issue by mrchimp** [monterail/vue-multiselect#294]
Not sure why but I'm not getting any styles applied when using beta 14. It works as expected if I roll back to beta 13.

**Comment by shentao** [comment]
https://github.com/monterail/vue-multiselect/tree/2.0#install--basic-usage
You have to add 
```
<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>
```
The docs will be updated soon.

**Comment by mrchimp** [comment]
Ah fair enough. Thanks for the quick response!

**Comment by jaketoolson** [comment]
Happened to me also -- spent way too long debugging LOL and I didn't defer to the docs because I assumed since it's beta, 2.0 wouldn't have changes from beta13 to beta14.

**Comment by shentao** [comment]
Sorry. It is in beta so it can have breaking changes until the API stabilizes. There’s one urgent bug to fix and I might finally release the stable version.
