### ISSUE TITLE
Not working with latest version of vue/vue-loader/vue-template-compiler

### ISSUE THREAD

**Issue by soloiago** [monterail/vue-multiselect#296]
We're working with webpack/vue/vue-multiselect in my company and today I've realised that vue-multiselect is not working anymore with the latest version of vue-related libraries (I guess). There are some steps to reproduce:
- Create a simple project with:
`vue-init webpack-simple test-multiple`

* The versions installed are:
`├── vue@2.2.1`
`├─┬ vue-loader@11.1.3`
`│ ├── vue-hot-reload-api@2.0.11`
`│ ├─┬ vue-style-loader@2.0.3`
`│ └── vue-template-es2015-compiler@1.5.1`
`├─┬ vue-template-compiler@2.2.1`
- The I install vue-multiselect:
`└── vue-multiselect@2.0.0-beta.14`
- If a add a vue-multiselect at the very beginning of the App.vue, the component is not working (styles are not applied):
[http://3.1m.yt/3TDONc8.png](url)

**Comment by shentao** [comment]
https://github.com/monterail/vue-multiselect/tree/2.0#install--basic-usage
You have to add
```
<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>
```
The docs will be updated soon.
