### ISSUE TITLE
Missing styles in vue-multiselect 2.0 beta 14

### ISSUE THREAD

**Issue by aswinkp** [monterail/vue-multiselect#297]
After I upgraded to vue-multiselect beta 14, I did not see any CSS in the selectors. Read this issue #293 and even installed  vue 2.2.1, but still issue persisted. No CSS were seen and when clicked on input textbox, the drop down came as the plain bulleted html list element. When reverted back to beta-13, everything started working fine again.

**Comment by ChrisSFR** [comment]
confirm
thanks @aswinkp you saved me a lot of time :D I have the same issue. I made a npm install yesterday and npm installed me the new 2.0.0-beta.14 instead of 2.0.0-beta.13. From that point on, all styles are missing. I didn't recognize a new vue-multiselect version was installed. 
With beta.13 my styles are back.

**Comment by shentao** [comment]
https://github.com/monterail/vue-multiselect/tree/2.0#install--basic-usage
You have to add
```
<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>
```
The docs will be updated soon.

**Comment by SirLamer** [comment]
For what it's worth, if you are using gulp or webpack or something, you can also just build the CSS in to there, which is better when that option is available.

Personally my opinion is that Vueify should be doing this already - baking its CSS snipets in to the CSS package and not in to the JS script - but it doesn't work that way right now.

**Comment by jbruni** [comment]
I would like to understand the reason why. Meanwhile, I'm just sticking to beta.13

**Comment by jbruni** [comment]
Ah! Now I saw at README: it is to support server-side-rendering. Thanks.
