### ISSUE TITLE
How to get selected values to process in backend?

### ISSUE THREAD

**Issue by nezaboravi** [monterail/vue-multiselect#299]
Seems i cant find a way to grab what values from multiselect has been selected to pass with the form to backend. Is there any documentation i can read about it?  I went thru docs a few times, but could not find the solution

**Comment by nikolaynesov** [comment]
@nezaboravi http://monterail.github.io/vue-multiselect/#sub-getting-started

So, from Basic usage example from docs, you need `value` from component data. This is what has been selected from `options` and is `null` by default.

Hopefully, it will help if I understood you correctly.

**Comment by nezaboravi** [comment]
Hi @nikolaynesov 
So i did like this: 
`<multiselect v-model="value" @input='updateSelected' :options="options" :multiple="true" :close-on-select="false" :clear-on-select="false" :hide-selected="true" placeholder="Pick tags" label="name" track-by="id"></multiselect>`

`<input name="tags_selected" id="tags_selected" value="" type="hidden">`

And in compnent:

`
methods: {
        updateSelected: function() {
            this.value.map((index)=>{
                this.tags_selected.push(index.id)
            })
            document.getElementById('tags_selected').value = this.clean(this.tags_selected);
        },
        clean: (arr) => {
            let tmp = [];
            for(var i = 0; i < arr.length; i++){
                if(tmp.indexOf(arr[i]) == -1){
                    tmp.push(arr[i]);
                }
            }
            return tmp
        }
    },
`
Sorry, cant format it :(

Then later in my PHP side i had to explode(',', $tags_selected ) and insert in DB

Do you see better approach? 
Thanks
Vladimir

**Comment by OyvindAndersson** [comment]
I'm guessing he means that no form-input data is sent with the request by default. I wondered about the same thing..

**Comment by nezaboravi** [comment]
quite simpler, yes. Thank you

**Comment by jamesfairhurst** [comment]
Instead of the extra hidden select I used the following which is just a little cleaner:

`<input type="hidden" name="users[]" v-for="user in selectedUsers" :value="user.id">`

**Comment by shentao** [comment]
I would say that @jamesfairhurst solution is the recommended one. Thank you.

**Comment by emilv** [comment]
I don't really like the workaround. Would anyone else be interested in a PR where we add these hidden fields automatically if a `name` prop is provided?

**Comment by antonioftamura** [comment]
<input type="hidden" name="users[]" v-for="user in selectedUsers" :value="user.id">

WORKED LIKE A CHARM!!

**Comment by agalya043** [comment]
<multiselect :options="[{label: 'Canada', code: 'ca'}]"></multiselect>
I Need to show the label,but the value should be saved as code,What i need to do?

**Comment by agalya043** [comment]
I Need to show the label,but the value should be saved as code,What i need to do?
`<multiselect :options="[{label: 'Canada', code: 'ca'}]"><multiselect>`
