### ISSUE TITLE
Wrong height / font-size

### ISSUE THREAD

**Issue by victor-ponamariov** [monterail/vue-multiselect#30]
Hi shentao!

I tried to use this awesome plugin and came across next issue:
![5860114b59ba43738b8d036ed1f34fc8](https://cloud.githubusercontent.com/assets/6241595/15988526/d7ccbeaa-305c-11e6-8d61-2428fa9795cd.png)

I realized that when I include bootstrap.less it breaks multiselect's height (for comparsion I included another select on the screenshot). But I couldn't find out why. I see multiselect uses rem units, maybe this is the key. 

Haven't you got such problem? Really want to use the plugin but got no idea how to fix that issue and what might cause this

Thanks in advance

**Comment by shentao** [comment]
Yes, this is the reason. I shall change everything to `px` in the next release! :)

**Comment by shentao** [comment]
Fixed in 0.2.5!
