### ISSUE TITLE
reset selected value after options change

### ISSUE THREAD

**Issue by bardiarastin** [monterail/vue-multiselect#302]
hi, first of all tnx for this awesome component !
i have 2 multiselects which the second one options depends on first one selected value
A & B (B options depends on A)
it's working fine but i have an issue : 
after selecting the A again B's options gets updated but i don't know how to reset current B value

**Comment by bardiarastin** [comment]
issue solved by changing B's v-model value to '' (empty string)

**Comment by marcelinhov2** [comment]
@bardiainjast hey bro, can you share your code pls? I'm having the same problem

**Comment by abkrim** [comment]
@bardiainjast hi, same problem for me (reset current value child mulstisleect). Please you can shre code or solution ?

**Comment by bardiainjast** [comment]
@marcelinhov2 @abkrim it's a lot of time that i'm not working with vue js anymore and i don't have my code on new laptop, old laptop is at home and i'm at work right now, i'll take a look tonight at 10PM (Tehran +3:30)

**Comment by C0unt23r0** [comment]
Hi, i would love to see this changed in the implementation. I think keeping the value per default selected if it isn't anymore available in the options makes no sense.

So i would expect something like this:
keep the option(s) selected if available if not clear selected or select first element based on the preferences (preselect-first/allow-empty)

It has to be possible to check that even when the options are objects with the help of the track-by prop.

**Comment by shentao** [comment]
Given that you are in control of the options (besides it being filtered when searchable), you can just modify the value yourself when the option is no longer available because of reasons other than search.

**Comment by waelkhalifa** [comment]
Hi, guys did anyone find the solution for this issue?
