### ISSUE TITLE
Interference of tab order of inputs in form

### ISSUE THREAD

**Issue by thupi** [monterail/vue-multiselect#303]
I am just started using this awesome dropdown/multiselect.

While i was trying to make a form partly using this component i had some issues with the order of focus when using tab.

Even though the multiselect behaves predictable while the option list is hidden, the component forces the user to press tab twice when the option list is visible. However, thhe component do handle reverse tab (SHIFT + TAB) as expected.

**Comment by infotokabil** [comment]
Hi @thupi ,

I am also getting the same problem.., Did you found any solution for this issue?

**Comment by thupi** [comment]
@infotokabil I haven't been able to find a workaround for this issue yet :)

**Comment by shentao** [comment]
To be improved in the next release, thanks! :)
