### ISSUE TITLE
Not supported documentation for ES5 (native JavaScript browser and current version  of JS)

### ISSUE THREAD

**Issue by maveius** [monterail/vue-multiselect#306]
Please add support for ES5 JS. Without 'import...', 'export', 'module'!

**Comment by shentao** [comment]
Use the vue-multiselect.min.js file. It is already transpiled to ES5.

**Comment by maveius** [comment]
No documentation for "How to use" vue-multiselect.min.js
is only one line about "How to import library":
<script src="https://cdn.jsdelivr.net/vue.multiselect/1.1.4/vue-multiselect.min.js"></script>
but no documentation for  "What next?"

**Comment by shentao** [comment]
VueMultiselect will be available on the window object. As it contains a default export you have to access it through VueMultiselect.default.

```
// register the plugin globally
Vue.component('Multiselect', VueMultiselect.default)
```

**Comment by maveius** [comment]
I'm really delighted, Thanks so much!

**Comment by maveius** [comment]
@shentao please help me:
Inside the component we have only one input called "search" but how to extract selected values from this component ? I would like to send it by subbmit HTML form. I have no Idea and any documentation how to do it!.

In this component we have only three events:
- selected; call selected funtion to save which objects are selected and assign it to "Selected" filed on the component.
- onSelect: runs only for one choosed option
- onUpdate: parameter is array of selected objects but it runs only if you select one of the option

I would like to get all selected elements, even if nothing was selected any option by user, because the selected option came from server.

**Comment by maveius** [comment]
Ok, after fight I do it but its not the best solution. 
Another question:
How to manipulate selected data on the component in. example:
- If You select  option with value "*" then remove your selected and append all options without "*"

**Comment by BruinY** [comment]
use bowser install, 
not find vue-multiselect.min.js.
