### ISSUE TITLE
bug internal-search

### ISSUE THREAD

**Issue by nunob87** [monterail/vue-multiselect#308]
Hello, When using the option-groups with internal-search the results do not appear

<img width="614" alt="captura de ecra 2017-03-06 as 13 34 05" src="https://cloud.githubusercontent.com/assets/11236820/23612028/a0895966-0271-11e7-852a-76e87c87e96e.png">

In the custom-label is there any way to insert html, I want to put name on the left and price on the right. The Custom option template give to use option groups?

thank you

**Comment by shentao** [comment]
You should be able to do this with custom option templates:
http://monterail.github.io/vue-multiselect/#sub-custom-option-template
