### ISSUE TITLE
[2.0] Error with an empty group and tags

### ISSUE THREAD

**Issue by pczarn** [monterail/vue-multiselect#309]
The following component throws an error as soon as I start writing in the search field.
```pug
  Multiselect(
    v-model="selected",
    :options="options",
    :multiple="true",
    :searchable="true",
    :taggable="true",
    label="label",
    track-by="label",
    group-label="type",
    group-values="values",
    @tag="addFixedValue"
  )
```
Options
```js
options: [
  {
    type: 'a',
    values: []
  }
]
```
I get this error in `optionKeys`
```
TypeError: Cannot read property 'toString' of undefined
```

**Comment by sandbox-services** [comment]
Its probably not the most ideal solution but it does the job.
https://github.com/monterail/vue-multiselect/pull/313

**Comment by shentao** [comment]
Adding a warning for when you pass incorrect options that do not match the config. Also gracefully returning `[]`.

**Comment by shentao** [comment]
Seems to be fixed on my working branch

**Comment by mikerockett** [comment]
This issue is persisting for me, on 2.1. I have a taggable select, and the above error gets thrown when I type into the box after adding my first tag. So the first one works without issue, and then it breaks...
