### ISSUE TITLE
2.0.0-beta.14 and css problems

### ISSUE THREAD

**Issue by xereda** [monterail/vue-multiselect#310]
The beta.14 release is having issues with css rendering. Look at this:

2.0.0-beta.14:
![beta14](https://cloud.githubusercontent.com/assets/14337850/23677638/b6c9558e-035f-11e7-8971-d9206a2ff75d.gif)

2.0.0-beta.13:
![beta13](https://cloud.githubusercontent.com/assets/14337850/23677709/fd8c6894-035f-11e7-9fe3-280fe8749b34.gif)

Are there any inconsistencies already found?

Thank you very much in advance,

**Comment by shubhampatel812** [comment]
From 2.0.0-beta.14, You have to include the CSS File Seperately
[Reference](https://github.com/monterail/vue-multiselect#important-breaking-change)

**Comment by shentao** [comment]
Thank you @shubhampatel812!

**Comment by mailnike** [comment]
Hi, i am facing this same issue, although I have already included CSS file in my HTML header section. Is there anything else I am missing?

**Comment by mailnike** [comment]
Okay. so it seems inline CSS HTML page is working but it doesn't work when I refer a .CSS file. weird.

**Comment by shentao** [comment]
Hey @mailnike! Could you show me how and where exactly do you import the css file?
