### ISSUE TITLE
id attribute for input

### ISSUE THREAD

**Issue by ChrisSFR** [monterail/vue-multiselect#315]
Hey there,
I'm using Laravel Dusk, a browser automation and testing API.

Dusk gives me the ability to select an item from a dropdown randomly. But therefor i need to select the specific input element in the dom.
At the moment dusk is capable of selecting the input element by id or name attribute.

Is there a way to add a name or id attribute for the input through the multiselect component?

for example:
<input type="text" **id="books"** autocomplete="off" placeholder="Choose books" class="multiselect__input">

**Comment by ChrisSFR** [comment]
nevermind, simulated the click event manually.
```php
$browser->click('input.multiselect__input');
$browser->click('li.multiselect__element');
```
;)

**Comment by Maidomax** [comment]
@ChrisSFR This still doesn't let you select a particular option by value or by label.

**Comment by cyberfly** [comment]
Just 2019 syntax update for @ChrisSFR answer 

`$browser->click('.multiselect__tags');
                $browser->click('.multiselect__option');`

**Comment by mostafa-amine** [comment]
Workd
