### ISSUE TITLE
Style not working

### ISSUE THREAD

**Issue by raphcadiz** [monterail/vue-multiselect#317]
When I tried to use the package the style is not working. I imported
import Multiselect from 'vue-multiselect'
but that componets style is not loading

**Comment by rousos87** [comment]
@raphcadiz You have to import it separately.

> As of beta.14 styles have to be required separately due to SSR support.
`<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>`

Please check:

[#301](https://github.com/monterail/vue-multiselect/issues/301)
[#297](https://github.com/monterail/vue-multiselect/issues/297)
