### ISSUE TITLE
Is it possible to hide placeholder in multiple select after first selection or when disabled?

### ISSUE THREAD

**Issue by yoavpe1** [monterail/vue-multiselect#318]

**Comment by shentao** [comment]
Placeholder can be dynamic so yes, you can just change it to `''` whenever needed.

**Comment by yoavpe1** [comment]
Thanks for the quick replay..
My question was asked because even when I set the placeholder value to empty string - it keeps taking place in the DOM:

Attached is an example:
With placeholder string:  http://prntscr.com/ekkbi8
With placeholder empty string:  http://prntscr.com/ekkbvd
Thanks...

**Comment by yoavpe1** [comment]
Solved it with CSS for now...
Hiding disabled component placeholder: .multiselect--disabled  .multiselect__single {display: none;}
Hiding after first tag is selected:  .multiselect__tag ~ .multiselect__single {display: none; }

**Comment by shentao** [comment]
Och, okay. Glad you found a solution! If you think the placeholder functionality could use some enhancement - please create a feature request issue!

**Comment by pushamaku** [comment]
@yoavpe1 Can you please try to explain how you solved it, I tried this CSS with no luck. Thank you

**Comment by yoavpe1** [comment]
@pushamaku 
Hi,
To hide the placeholder when the component is disabled:
    .multiselect--disabled   .multiselect__single {
        display: none;
    }

To hide the placeholder after first item is chosen:
    .multiselect__tag ~  .multiselect__single {
        display: none;
    }

Make sure your css overwrite the component css. If it doesn't, try to add a parent class to the css 
for example:
    .your-class  .multiselect__tag ~ .multiselect__single {
        display: none;
    }

Hope it helps...

**Comment by pushamaku** [comment]
@yoavpe1 

Thank you for your help. I have added this CSS, but there I still cannot get rid of the placeHolder when items are selected.

![image](https://cloud.githubusercontent.com/assets/19703660/25947278/c114ac52-3689-11e7-86dd-b48f2349a163.png)

**Comment by yoavpe1** [comment]
@pushamaku 
It is difficult to help without seeing the code :)
I am attaching a screen print of the debugging tool with the relevant code.
Try to find this DOM element (<span class="multiselect__single"> and add to it display: none in the developer tool to see that you are dealing with the correct element.
Then check that the css rule that you wrote applies to this element.
http://prntscr.com/f6kpn2

**Comment by pushamaku** [comment]
@yoavpe1 

Yes, you're absolutely right, but THANK YOU so much for pointing me in the right direction, as I believe the issues is solved now, and no extra logic to mess with the placeholder was needed.

When I checked the DOM, it seems that in my version of this component the relevant element is actually [_multiselect__input_](http://prnt.sc/f6kyxa) and not _multiselect__single_ 

It works perfectly!

**Comment by rostockahoi** [comment]
@yoavpe1 This could actually be worth a new feature. Something like `HidePlaceholderOnSelect` as a new boolean Prop. What do you mean?
