### ISSUE TITLE
Can I set the limit of selection?

### ISSUE THREAD

**Issue by nodocaengine** [monterail/vue-multiselect#32]
When using tagging and multiselect options, can I set the limit of number of selected and created tags?
If I can do so, I want to stop working ajax searching, creating new tags, and show notice that means like "You cannot select and create tags anymore" when the number of inputting tags reaching the limit.

**Comment by shentao** [comment]
Hey there @nodocaengine!

Sadly right now you can’t, but this sounds like a valid request! 🎯
I think I could introduce a limit of selected options (and this way also tags) that would disable adding anything to the list of selected options and show a statement that you can also pass as a prop. Would this be enough?

**Comment by nodocaengine** [comment]
@shentao Thanks for reading my issue and sounds good you said!
I wish it comes true :)

**Comment by icebob** [comment]
+1, limit is an important feature. I'm waiting too :)

**Comment by shentao** [comment]
I will try to add this functionality this weekend! Stay tuned!

**Comment by shentao** [comment]
@nodocaengine @icebob Added the functionality in 0.2.6 :)

Just add `:max="number_here"` prop.

Example usage in the docs. See *Custom Configuration* part of the documentation: http://monterail.github.io/vue-multiselect/

**Comment by icebob** [comment]
Great! Thanks!

**Comment by nodocaengine** [comment]
@shentao Thanks a lot!
