### ISSUE TITLE
No CSS

### ISSUE THREAD

**Issue by PrimozRome** [monterail/vue-multiselect#322]
I have updated to the latest version of vue, vue-cli, vue-multiselect and for some reason vue-multiselect is not loading `.multiselect___*.*` classes. Any idea what would be the reason?

It's loading my overrides but not native component's classes...

**Comment by oe-sfong** [comment]
http://monterail.github.io/vue-multiselect/#sub-getting-started

in the very first block under basic usage


<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>

**Comment by sandbox-services** [comment]
http://monterail.github.io/vue-multiselect/#sub-getting-started

in the very first block under basic usage
<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>

**Comment by PrimozRome** [comment]
Oh dear... missed that. What is the reason behind this change?

**Comment by shentao** [comment]
@PrimozRome It was required to support SSR. Before that change it was impossible to run on the server side. It also made the whole thing a bit smaller, even after you combine the new CSS + JS file.

**Comment by janswist** [comment]
I have very similar error ( #791 ). After couple refreshes styles load, but before that  it basically blocks loading another styles. I tried via npm and via CDN ways.
