### ISSUE TITLE
Behind the icons

### ISSUE THREAD

**Issue by xereda** [monterail/vue-multiselect#324]
The component is getting behind the icons in a Bulma Framework application. What can be done to prevent this from happening !?

![icons](https://cloud.githubusercontent.com/assets/14337850/24118147/903f393e-0d8b-11e7-8885-53832bd5f55e.gif)

**Comment by a-komarev** [comment]
@xereda You can define z-index higher than icon ones for the dropdown list.

**Comment by shentao** [comment]
Use `z-index` either on the multiselect wrapper or on the icons.

**Comment by xereda** [comment]
But if I use z-index in multiselect, it ends up causing inconsistency in your presentation when I use more than one on my form. Look at this:

**Comment by yasoza** [comment]
this [PR](https://github.com/shentao/vue-multiselect/pull/1350) might solve this

**Comment by yasoza** [comment]
#1350
