### ISSUE TITLE
Option to Clear Selection

### ISSUE THREAD

**Issue by jbruni** [monterail/vue-multiselect#325]
I must be missing something... I'm using vue-multiselect for a "filter by product" input, so the **options** are the available products (an array of product objects).

Now, I need to prepend a topmost option, which when clicked sets the v-model value back to null, clearing the selection.

How do I achieve this? I thought it was going to be straightforward and easy... but I couldn't find how to do it.

Thanks.

**Comment by shentao** [comment]
Sounds like you need something similar to: http://monterail.github.io/vue-multiselect/#sub-action-dispatcher

If you want to clear the results just change the `value` back to `null`. You might have to handle `@input` and `:value` separately instead of relying on `v-model`.

Hope that helps.

**Comment by jbruni** [comment]
Yes. Thanks. I've prepended a "fake item" to my options array (with `id` equal to `-1`), and added an `input` event listener to set `value` back to `null` if the "fake item" has been selected. Issue resolved.

**Comment by marcelinhov2** [comment]
@jbruni can you share your code, pls? Tks

**Comment by Glideh** [comment]
I used [slots](https://vue-multiselect.js.org/#sub-slots), especially the `beforeList` one so, it appears on top of the list

```vue
<multiselect ref="selectedItems" :options="items" v-model="selectedItems">
  <template slot="beforeList">
    <div>
      <button @click="selectNone">none</button>
      <button @click="selectAll">all</button>
    </div>
  </template>
</multiselect>
```

```js
selectNone() {
  this.selectedItems = [];
  this.$refs.selectedItems.deactivate();
},
selectAll() {
  this.selectedItems = this.items;
  this.$refs.selectedItems.deactivate();
},
```
