### ISSUE TITLE
Search is not case insensetive, when using option groups

### ISSUE THREAD

**Issue by tonila** [monterail/vue-multiselect#328]
Here is the fiddle:
https://jsfiddle.net/c4L3gs91/12/

Just try to find an item by typing e.g. "V"

I tracked this issue to [multiselectMixin.js:284](https://github.com/monterail/vue-multiselect/blob/2.0/src/multiselectMixin.js#L284)

Adding toLowerCase() to this.search seems to fix this issue.

```
filterAndFlat (options) {
  return flow(
    filterGroups(this.search.toLowerCase(), this.label, this.groupValues, this.groupLabel),
    flattenOptions(this.groupValues, this.groupLabel)
  )(options)
},
```

**Comment by shentao** [comment]
I will look into it.

**Comment by shentao** [comment]
Should be fixed in the upcoming release.

**Comment by ulissesalmeida** [comment]
@shentao Is it fixed in the master?

**Comment by Roriz** [comment]
+1
