### ISSUE TITLE
It don't validate on Submit when using :required <multiselect> in a Form

### ISSUE THREAD

**Issue by Onfealive** [monterail/vue-multiselect#329]
I'm using Vue-Multiselect v2.0.0-beta.15 with Bootstrap v4.0.0-alpha.6.
*Found:
The inside input doesn't have required, but the outer div do.

![phoxo1](https://cloud.githubusercontent.com/assets/18258131/24341453/027e4258-12e4-11e7-912a-c0a854225541.jpg)

*With required, but it too ugly...
![phoxo2](https://cloud.githubusercontent.com/assets/18258131/24341587/e339b34a-12e4-11e7-9f23-025400d35104.jpg)

Please fix it, thanks 😄

**Comment by shentao** [comment]
https://jsfiddle.net/fzovkjpm/ Seems to work for me.

**Comment by adrianoresende** [comment]
@shentao I think you should consider this issue.

Required in the input to make things easier.
More semantics is better.
