### ISSUE TITLE
How to programatically search options and select it for display

### ISSUE THREAD

**Issue by rlightner** [monterail/vue-multiselect#330]
I have a multiselect with group-values that I would like to search and find an id in the options and set as selected. It's not apparent to me how this is accomplished.

**Comment by shentao** [comment]
Please give it a try here https://jsfiddle.net/shentao/c4L3gs91/, save the fiddle and send it here so we can figure out how to make it work.

**Comment by rlightner** [comment]
https://jsfiddle.net/qr4cwurw/

**Comment by shentao** [comment]
Sorry for the late reply. I still don’t understand what you want to accomplish. Something like this? https://jsfiddle.net/8pmnvf3x/

Closing in case it’s no longer valid. If it is, reopen please.

**Comment by rlightner** [comment]
on Mounted, I want to set subCategory '10B' to be selected, so if I'm loading a form that is prepopulated, its not prompting me to select a fermentable, but its set to the prior saved value.

**Comment by shentao** [comment]
Here: https://jsfiddle.net/La63x6rd/
That approach should work. You basically have to find the object you want to preselect and set it as the `value`.

Right now this is the only way to do this. I’m thinking of introducing a "track-by-value-only" based selecting, although I still haven’t figured it out as it’s likely to introduce problems when it comes to async search.
