### ISSUE TITLE
Request: Example repo with Vue 2.x, webpack, Vuex, and Vue-Multiselect

### ISSUE THREAD

**Issue by Joshfindit** [monterail/vue-multiselect#331]
I've been slogging through everything I can get my hands on in order to accomplish a **multiple-select drop-down that gets/sets with the state**, and I don't feel any closer to a solution.

To break down each attempt and error feels like it would take days.

As [Webpack](https://github.com/vuejs-templates/webpack) seems to be the choice of build tool ( `2,725` stars and `1,173` forks vs Browserfy's  `159` stars and `63` forks ), and Vuex is the obvious choice for anything above a certain complexity, it seems like the next logical step to create an example project that brings them together along with [vue-multiselect](https://github.com/monterail/vue-multiselect).

Thoughts?

**Comment by shentao** [comment]
Well, Browserify has much more stars actually (10k+) https://github.com/substack/node-browserify.
I think that this example in the docs: http://monterail.github.io/vue-multiselect/#sub-vuex-support is everything one would need to know how to work with Vuex.

In other words – there are 2 options to work with Vuex and vue-multiselect. 
- Either you don’t use `v-model` and pass the data with `:value` + call an action/mutation within the `@input` handler.
- Or when mapping state to a computed value you can create a computed setter to call the action/mutation and then keep using `v-model`. Please read: https://vuejs.org/v2/guide/computed.html#Computed-Setter and  https://vuex.vuejs.org/en/forms.html

Not sure if creating an example project would help. Maybe we could add Vuex to the example fiddle (https://jsfiddle.net/shentao/c4L3gs91/)

**Comment by Joshfindit** [comment]
@shentao Apologies, I meant the Webpack vs Browserfy Vue.js templates: https://github.com/vuejs-templates.

TYhank you for the breakdown, I'll have to take a look at this again when I've rested

**Comment by shentao** [comment]
Sure! Closing it for now.
If you need any more help just reopen and let me know! :)

**Comment by qkdreyer** [comment]
@shentao Could you give us more advice on how to use a computed setter please ?
