### ISSUE TITLE
Is there a way to use multiselect as text input with autocomplete?

### ISSUE THREAD

**Issue by vedmant** [monterail/vue-multiselect#334]
Hi, is there a way to use multiselect as text input with autocomplete? Means let it allow to keep typed value, something like tag, but just a single value without additional styling: https://screencast.com/t/0EvGwC6PBB0

It would be really helpful, thanks!

**Comment by shentao** [comment]
The current implementation of the slot kinda hinders the ability to disable the `noResult` slot. I guess this would make for a nice enhancement.

**Comment by SirRafaMedina** [comment]
+1

**Comment by shentao** [comment]
I believe this is possible right now with how the `noResult` slot works.

**Comment by Frondor** [comment]
@shentao mind explaining a bit the "how"? Actually, its not possible to get an "autocomplete" behavior. The text will always be reset if no (valid) option is selected.

**Comment by adilhraza** [comment]
Did anyone figure this out? is there a jsfiddle or codepen for this?

**Comment by shentao** [comment]
Maybe you can try to use the tagging feature with `:multiple="false"`?
https://vue-multiselect.js.org/#sub-tagging

**Comment by vortechron** [comment]
for those that want to use multiselect as text input with autocomplete

the binding:
```javascript
{
     taggable: true,
     multiple: false,
     onNewTag(newTag) {
          this.model = newTag;
     }
}
```
