### ISSUE TITLE
Using allowEmpty with multiple = false is buggy

### ISSUE THREAD

**Issue by Fohlen** [monterail/vue-multiselect#336]
Using `allowEmpty` with `multiple = false` is rather buggy. Actually it is not possible to remove all elements once `multiple = false`.
An example can be found here, https://jsfiddle.net/c4L3gs91/27/

**Comment by shentao** [comment]
Could you be more specific? I added `:allow-empty="false"` together with `:multiple="false"` and it works as supposed:
- Once an option is selected you can’t unselect it
- You can only select other options

**Comment by Fohlen** [comment]
It actually happens for me in `2.0-beta13` but I couldn't yet reproduce it in the fiddle.. investigating.

**Comment by shentao** [comment]
Please upgrade to `beta.15`, there were some tweaks regarding this.

**Comment by Fohlen** [comment]
Upgrading to `beta.15` resolved the issue immediately.

**Comment by gapnav** [comment]
hmm.. having same issue on `2.1.3`

**Comment by viaativaweb** [comment]
same issue here, once a value is selected it can never be changed
