### ISSUE TITLE
Custom Label for only display selected area

### ISSUE THREAD

**Issue by g-adolph** [monterail/vue-multiselect#338]
Hi, I need to do a custom label function only in display selected area for each selected item. Something like CustomSelectedLabel.

In your fiddle sample i need to display on selected display area the language but in dropdown list the customLabel result

**Comment by shentao** [comment]
Not yet possible unless you decide to build your own version by extend multiselect.
This is however something I would like to work on next.

**Comment by shentao** [comment]
Custom label now applies to the selected tags too. You can also provide your own tag template with new slot. Will be available in the next release.
