### ISSUE TITLE
SSR?

### ISSUE THREAD

**Issue by tenjojeremy** [monterail/vue-multiselect#340]

**Comment by shentao** [comment]
Yes, vue-multiselect should be fully compatible with SSR.
Keep in mind that you need to add the CSS somewhere in the app.
@tenjojeremy In a different issue, you mentioned a problem with hydration – could you provide more details? A repro would be best.

**Comment by shentao** [comment]
Using it with nuxt.js in a new project – works without any problems. Closing the issue.

**Comment by tenjojeremy** [comment]
Thank you @shentao  for you help
