### ISSUE TITLE
Question: Triggering "select" or "change" on multiple instances on the page

### ISSUE THREAD

**Issue by jaketoolson** [monterail/vue-multiselect#341]
I'm trying to figure out how to programmatically trigger all the multi-selects on my page to select/add a tag.  I'm letting users select items in bulk then apply multiple tags at once to all the selected items.

My thinking is:
-- add the option to all <select> fields and set it as selected

--- then trigger changed ?

**Comment by shentao** [comment]
Let’s say each of the Multiselects is connected to some `selectedX` arrays:
```
<multiselect v-model="selected1" :options="myOptions">
<multiselect v-model="selected2" :options="myOptions">
<multiselect v-model="selected3" :options="myOptions">
```

If you want to add a value to each of those multiselect components, all you need to do is push the tag/option to each of those lists.

Is this what you require?

**Comment by jaketoolson** [comment]
@shentao this makes sense.  I'll try this. Thanks.
