### ISSUE TITLE
Options not being loaded when expected

### ISSUE THREAD

**Issue by juannenna** [monterail/vue-multiselect#344]
Hi! i have a simple question for your vue 2.0 implementation: 

My code is generating multiple <multiselect> with async options, and my options are coming back from the server after the user types 5 letters, thus creating the options for the specified multiselect. However, options only show up on the actual element as I type the 6th character, so essentially one step more than it should be. The weird thing is that if I log the options on every @search-change, they show up perfectly at the correct time, so my guess is there's some sync issue or something? thanks!!!

**Comment by shentao** [comment]
Have use added the `:internal-search="false" flag? Otherwise, you will double filter the options (once on the backend and again within Multiselect itself).
