### ISSUE TITLE
options with falsy values not shown in dropdown

### ISSUE THREAD

**Issue by darthmelak** [monterail/vue-multiselect#345]
I want to use multiselect as a simple select replacement and found this: any falsy option does not show up in the dropdown - and cannot be selected

fiddle: [https://jsfiddle.net/zf3vw4hs/1/](https://jsfiddle.net/zf3vw4hs/1/)

**Comment by shentao** [comment]
Thanks. Working on a fix :)

**Comment by NickSurmanidze** [comment]
Hi,

Great job with the component! I have noticed one thing - when I have v-model with pre-populated value which is 0 (I am using array keys as options) then prepopulated results is not shown until I select it. If I set v-model to some other key, multiselect automatically switches selected value. I think this issue might be related.

**Comment by shentao** [comment]
This is already fixed :)

**Comment by lorenzopiquer** [comment]
Hi,
If initial value is 0 the input shows the placeholder instead of the value, although it does appear as selected in dropdown. 
You can see this behaviour in the first comment @darthmelak fiddler (changing js and css references to 2.0.3)

**Comment by gandesc** [comment]
> If initial value is 0 the input shows the placeholder instead of the value, although it does appear as selected in dropdown.

Same here, using 2.0.3. 

Awesome library, btw!

**Comment by shentao** [comment]
Fixed and released in 2.0.4. Thanks :)

**Comment by lorenzopiquer** [comment]
Awesome!
Thank you and congrats for the library!
