### ISSUE TITLE
error when build command in vue-cli webpack template

### ISSUE THREAD

**Issue by zhiga90** [monterail/vue-multiselect#348]
ERROR in static/js/vendor.7fa26e985f44def8b403.js from UglifyJs
Unexpected token: operator (>) [./~/vue-multiselect/src/multiselectMixin.js:12,0][static/js/vendor.7fa26e985f44def8b403.js:59161,29]

```
function filterOptions (options, search, label) {
  return label
    ? options.filter(option => includes(option[label], search))
    : options.filter(option => includes(option, search))
}
```
something about "option => includes"

**Comment by shentao** [comment]
How does your setup look like? Are you using webpack? It seems that there’s a problem with es6 support. How do you import the library?

**Comment by zhiga90** [comment]
sory about that

**Comment by shentao** [comment]
It’s okay :)

**Comment by IvanRibakov** [comment]
Still seeing this message, using webpack, importing like this: 
`import Multiselect from 'vue-multiselect/src/Multiselect.vue'`

Any thoughts?

**Comment by shentao** [comment]
Change `src` to `lib`.

**Comment by IvanRibakov** [comment]
what about `dist` folder? Can I use that one? Or better to stick with `lib`?

**Comment by shentao** [comment]
Well actually you can just do
```
import { multiselectMixin } from 'vue-multiselect'
// or 
import Multiselect from 'vue-multiselect'
```
