### ISSUE TITLE
Error from UglifyJs Unexpected token punc «(», expected punc «:» 

### ISSUE THREAD

**Issue by vedmant** [monterail/vue-multiselect#349]
Hi, when I run compilation on production mode I have following error:

/js/app.c7e8fcf503f456065fb8.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/vue-multiselect/src/pointerMixin.js:2,0][/js/app.c7e8fcf503f456065fb8.js:2779,7]
 
Probably similar to https://github.com/sagalbot/vue-select/issues/71 , however I'm using Laravel Mix and it would be harder to edit webpack config to include vue-multiselect into babel compilation. I think node_modules should be precompiled anyway.

**Comment by shentao** [comment]
Are you using the default minified and transpiled file – `vue-multiselect.min.js`? Or importing individual mixins? If you’re doing the latter, then make sure you import from the `/lib` catalog. There are the transpiled (ES5) files.

**Comment by vedmant** [comment]
Yeah, my mistake, I used .vue component directly because webpack was importing all styles for me, it worked in Chrome cause it supports ES6. Switched to minified version and imported styles separately. Thanks!
