### ISSUE TITLE
How do you pass data down from parent?

### ISSUE THREAD

**Issue by Asvae** [monterail/vue-multiselect#35]
I use `vue-multiselect` in complex form. It operates in the manner of autocomplete select.

When it comes to getting the selected item from `vue-multiselect` — i use `$emit` in child plus `@event` in parent and everything works fine.
But when i try to modify the multiselect state from parents — it doesn't work. I tried using `selected` props, did `this.options.push()` to no avail.

So is it even possible and if so what's the recommended approach?

Thanks for your attention.

**Comment by shentao** [comment]
If you wish to change the selected options, you can modify the `:selected` prop. The change will update the value inside.
If you want to change the options available inside the multiselect you can simply mutate those using `on-search-change` callback function. Example implementation in the docs for asynchronous options:
https://github.com/monterail/vue-multiselect/blob/master/docs/App.vue#L262
https://github.com/monterail/vue-multiselect/blob/master/docs/App.vue#L774

This can be used for stuff like autocomplete select.

Hope this helps! :)

**Comment by Asvae** [comment]
Sorry, but your solution doesn't appear to work.

I somehow managed to show the `selected` object that was sent from parent (via `placeholder`). Here's the [gist](https://gist.github.com/Asvae/fe1ce1d34fd73ba1b8dbcb391d2f8c94).

But this solution is not perfect. On screenshot lowest component had been clicked on while the topmost hadn't been. They both share the same `selected` prop. Also, they don't follow state change for some reason.

![rnaezpx](http://i.imgur.com/GRqP224.png)

Thanks for keeping up with me. :3

**Comment by shentao** [comment]
Damn!

`:options.sync` don’t need the `.sync` modificator. What you also need is to set the `selected` value somewhere. Usually it is the `:on-change` function, but looking at your example, you modify it in the parent. Make sure when that when you catch the `@selected` you save `this.selected = selected`. Also I’m not sure if you need the `_.cloneDeep` lodash method here.

In the docs there is an example of selects that share the same `selected`:
https://github.com/monterail/vue-multiselect/blob/master/docs/App.vue#L142

Give it a try and let me know! :)

**Comment by Asvae** [comment]
> `:options.sync` don’t need the `.sync` modificator
> you need the `_.cloneDeep` lodash method here

Yeah, definitely overkill. Had to be sure I did everything i could :).

> save this.selected = selected

I certainly do that as I have a lot of `<pre v-text="selected | json"></pre>` sprinkled over the code. They monitor the value and it works as expected. The only issue is displaying the selected object inside the `vue-multiselect`.

I also took a glance at [chrome vue devtools](http://i.imgur.com/1gqFbcJ.png). As you can see, the component is clearly aware of `selected` object. It just won't refresh on change or something.

BTW, I'm willing to invest all the time needed to have this issue solved (meaning coding, not pressure). As `vue-select` is pure awesome and I plan to use it in many many places. :)

**Comment by Asvae** [comment]
I found a culprit. This line:
```
:clear-on-select="false"
```
When it's set to `false`, displayed value doesn't sync from parent. Not sure if it's intended, but sorta confusing.

Thanks for helping out.

**Comment by shentao** [comment]
This is not intended so I will have a look into it in the coming days. Thanks for bringing this up!

In the end, I’m glad it works now! :)
