### ISSUE TITLE
Feature Request: custom-group-label

### ISSUE THREAD

**Issue by randyyaj** [monterail/vue-multiselect#350]
Would it be possible to implement a custom-group-label attribute for option groups?

Is see custom-label but I want to customize the group label as well. Is that already possible and I'm just missing it in the doc somewhere?

I was somewhat able to achieve it by roughly by doing this in my data although its not optimal.

```
options: [{
          language: this.customGroupLabel({ name: 'Javascript', category: 'imperative' }),
          libs: [
            { name: 'Vue.js', category: 'Front-end' },
            { name: 'Adonis', category: 'Backend' }
          ]
        }]
```

**Comment by shentao** [comment]
No plans for a direct support for this so far. I believe mapping to a new options list would be the best solution at the moment.
