### ISSUE TITLE
Enhancement Request: Options Template Slot

### ISSUE THREAD

**Issue by predhme** [monterail/vue-multiselect#353]
The ability to override the original look and feel of each individual option is great. However, is there a way to take it even one step further and provide a means to override the template to render the entire list of options? 

That is, would it be possible to provide a slot to override the entire list of options? We would like to customize the display of the options in certain cases.

**Comment by shentao** [comment]
I think in such case it would be best to just use the multiselectMixin and pointerMixin (if you want the arrow keys support) and build your own version of the component (mostly styles and template) based on the logic within the mixins.

**Comment by predhme** [comment]
@shentao I agree with your suggestion and that is the direction we have taken. Thanks!
