### ISSUE TITLE
Internal Search with groups is case sensitive.

### ISSUE THREAD

**Issue by roylkng** [monterail/vue-multiselect#354]
Internal search is busted when we use the groups for the multislect, is there any hack to handle it for the time being, and removing the internal search option also does not work with groups which is fixed in .14 beta but .14 beta breaks all the styling and look and feel which i edited for the .13 version, so please can we follow the same convention for css and variables until there is major version update.

**Comment by Roriz** [comment]
+1

**Comment by robodude** [comment]
It's more bizarre than your post would lead you to believe! 

Check out the example here: http://monterail.github.io/vue-multiselect/#sub-option-groups

Search for: rails
It finds one match
Search for: Rails
0 Matches! Even though the casing is exactly the same.

Additionally, if you look at the example issue when you go to create a new issue

  https://jsfiddle.net/shentao/c4L3gs91/

Searching doesn't work at all there!

**Comment by robodude** [comment]
I think a big issue here is that the unit tests check against string numbers and not letters.

**Comment by shentao** [comment]
I will try to finally release a new version today/tomorrow that addresses those problems. Sorry :(

**Comment by shentao** [comment]
Fixed. Should be finally released very soon.
