### ISSUE TITLE
import of the multiselect code seems problematic

### ISSUE THREAD

**Issue by vincentLabbe** [monterail/vue-multiselect#356]
```
<script>
import { Multiselect } from 'vue-multiselect';
import * as types from '../store/mutation-types';
import Results from './subComponents/search/Results';

export default {
  name: 'Archives',

  components: {
    Results,
    Multiselect,
  },

data() {
    return {
      months: ['test', 'test', 'test', 'test', 'test', 'test'],
      selectedMonth: null,
    };
  },
....
```

The following code results in the following error:

ERROR in ./~/vue-multiselect/lib/vue-multiselect.min.js
Module build failed: Error: ENOENT: no such file or directory

Can somebody help me?

**Comment by shentao** [comment]
`import { Multiselect } from 'vue-multiselect';` that should work :)

**Comment by vincentLabbe** [comment]
For some reason, it doesn't work, I'm trying to point directly to the vue-multiselect.min.js file and that doesn't work either :/

**Comment by shentao** [comment]
Don’t. If you point at `vue-multiselect` then it uses the `vue-multiselect.min.js` file by default. If you want to pick a specific file from the bundle (see the catalog in node_modules/), use something like `vue-multiselect/dist/vue-multiselect.min.js`. 

Also, whats the error when you do `import Multiselect from 'vue-multiselect';`?

**Comment by shentao** [comment]
Please use `vue-multiselect/dist/vue-multiselect.min.js`. Also, make sure you update to the latest beta release! If you’re using yarn you might need to reinstall the plugin completely. Somewhere during the recent releases, I changed the `"main"` file of the package.

**Comment by vincentLabbe** [comment]
Somehow it started to work after I moved the vue-multiselect.min.js around in the node-modules folder. I guess that maybe my setup had a little hiccup

Thank for the support!

**Comment by shentao** [comment]
Great! Try removing the `node_modules/` directory and doing a fresh `npm i`. :)
