### ISSUE TITLE
Press backspace with no input, the browser back

### ISSUE THREAD

**Issue by kazusa-qooq** [monterail/vue-multiselect#357]
When there is no input text and I press backspace key, the browser page is back.
It is happen in jsFiddle.
Even If there are tags, it is happen.
I checked it on IE and Firefox.

**Comment by shentao** [comment]
Thanks for letting me know. No idea how this wasn’t detected before o.O.

**Comment by ddett** [comment]
I still see this happen in firefox with version 2.1.6 of vue-multiselect ...

**Comment by nDoped** [comment]
@shentao, this is still an issue on version 3.0.0 in FF v126.0.1. This issue needs to be re-opened.
