### ISSUE TITLE
multiselect not visible, always giving fragment instance problem

### ISSUE THREAD

**Issue by chagamkamalakar** [monterail/vue-multiselect#36]
the warning is as follow: 
Attributes ":selected.sync", ":options" are ignored on component <multiselect> because the component is a fragment instance:

i followed same as described in the document. ... please help me out

**Comment by Asvae** [comment]
Take a look [here](https://vuejs.org/guide/components.html#Fragment-Instance). Basically, you can only have one top level element.

Hope this helps.

**Comment by chagamkamalakar** [comment]
let me put my code here 

index.html
```
<html>
    <body>
        <div id="acl">
              <multiselect :selected.sync="selected" :options="options"></multiselect>
        </div>
    </body>
</html>  
```
acl.js

```
import Multiselect from 'vue-multiselect'
new Vue({
    store,
    el: "#acl",
    components: { Multiselect },

    ready() {
    }
});
```

is <div id="acl">  not a root element?

**Comment by Asvae** [comment]
@chagamkamalakar try importing like this:
`import { Multiselect } from 'vue-multiselect'`

**Comment by shentao** [comment]
`import { Multiselect } from 'vue-multiselect'`
This will fix your problem. ;)

**Comment by chagamkamalakar** [comment]
thank you @Asvae , @shentao 

working like charm

**Comment by shentao** [comment]
Damn, I just noticed that I haven’t updated the README file with this change to importing. Sorry about this, my bad. :(
In the docs it is written correctly though. I’m glad it works for you. If you have any other problems, let me know!
@Asvae thanks for help with resolving other issues!

**Comment by Asvae** [comment]
@shentao, I think you can organize the bundle as follows:
```
import _Multiselect from './Multiselect'
import _multiselectMixin from './multiselectMixin'
import _pointerMixin from './pointerMixin'

export default _Multiselect

export var Multiselect = _Multiselect
export var multiselectMixin = _multiselectMixin
export var pointerMixin = _pointerMixin
```
That way, if you import `Multiselect` you get plain component, and if you need something more specific — you can import `{ multiselectMixin }`, for instance.

Backwards compability included :).
