### ISSUE TITLE
clear all extended function

### ISSUE THREAD

**Issue by l86110** [monterail/vue-multiselect#361]
could you provide a clear all function 
![image](https://cloud.githubusercontent.com/assets/5345593/25693008/2f621804-30d9-11e7-8302-a5e2614ad982.png)

**Comment by shentao** [comment]
Good idea, can do :)

**Comment by l86110** [comment]
Thanks very much @shentao

**Comment by DannyFeliz** [comment]
I really need this function

**Comment by miladr** [comment]
I need it too. Thank you.

**Comment by shentao** [comment]
Adding a special slot `clear`, that makes it possible to create a *clear-all* button. The slot receives the search query as props so it can be used also for creating *search* button (coupled with `:internal-search="false`.

Will be available with the next release.

**Comment by denali95** [comment]
Is there a good simple example of how this works?  I'm having trouble understanding how it's working in the docs' Asynchronous Select html code.

**Comment by vahidalvandi** [comment]
how i can use this  ?

**Comment by vahidalvandi** [comment]
i cant use this ! its hidden
