### ISSUE TITLE
Controlling a Property with MultiSelect

### ISSUE THREAD

**Issue by yoavpe1** [monterail/vue-multiselect#362]
Hi,
I have an item with different properties - item.name, item.address, item.isEnable ...
I would like to control item.isEnable value through the Select. 
When choosing disable in the select - the item.isEnable value should be false.
When choosing Enable in the select - the item.isEnable value should be true.

And also the other way round: the select should reflect the item.isEnable value - show 'Disable' if the item.isEnable value is changed to false, and 'Enable' when the item.isEnable value is true.

How do I configure this?

Attached is the fiddle I am trying to do.
https://jsfiddle.net/q5qzk8oy/

Thanks

**Comment by shentao** [comment]
Hey! This should work: https://jsfiddle.net/ta22y2xL/

**Comment by yoavpe1** [comment]
Thanks...
I am sorry but my question wasn't clear enough.
I can not add properties (such as text) to the selectedItem object.
It is a computed object data:
computed: {
        selectedItem: function () {
            return this.$store.state.selectedItem;
        }
}
I need the select component to control SelectedItem.isEnable property (false/true)
and on the other hand reflect the value that it has - show 'Disabled' if selectItem.isEnable is false and 'Enabled' if the value is true.
 <input type="text" v-model="selectedItem.name" />
 <input type="text" v-model="selectedItem.address" />
 <multiselect v-model="selectedItem.isEnable" :options="options"></multiselect>

**Comment by shentao** [comment]
Then it is related to #359 and #263
