### ISSUE TITLE
Click on afterList don't trigger

### ISSUE THREAD

**Issue by Roriz** [monterail/vue-multiselect#364]
Hello everyone,
I would like to retake a difficulty in implementing dynamic addition within the options.

**Steps to Reproduce:**
1. Click on select
2. search for any term not exist, exemple: 'a'
3. click on afterList.

**Expected behavior**
Trigger function addNewValue and new option will appear.

**Current behavior**
Open select just after step 1.

https://jsfiddle.net/c4L3gs91/140/

**Comment by shentao** [comment]
Use `:taggable="true"` with `@tag` handler.
Example: https://jsfiddle.net/ks6q9oj4/
