### ISSUE TITLE
Feature request: add `multiselect--no-results` class when the list is empty

### ISSUE THREAD

**Issue by wujekbogdan** [monterail/vue-multiselect#369]
Hey,

My results are loaded via AJAX. So when the input has focus then `multiselect__content` element shows up, but it's empty. It causes styling issues because there's no way to style this element depending on a number of results (I'd like it to look different when the list is empty - actually I'd like to hide it :))

So it would be great it the root element had a class of `multiselect--no-results` when the results list is empty. It would solve the problem.

It might be even considered as a bug - why to show the list when there's nothing to show?

Thanks

// Edit:
I've solved this problem adding a dynamic `:class` binding on a `<Multiselect>` tag. 
``` html
<multiselect  :class="{'multiselect--empty': filterPhrase.length === 0}" >
```

**Comment by vDupindev** [comment]
Hi, 
What is the best solution to resolve this problem ? (Change the "List is empty." text)
