### ISSUE TITLE
Example on project page is glitchy in Firefox

### ISSUE THREAD

**Issue by rgtk** [monterail/vue-multiselect#370]
Option badges in example select on project page are not algined properly in  `Firefox/54.0`:

![screenshot at 2017-05-10 19-39-36](https://cloud.githubusercontent.com/assets/765841/25915146/74251ee4-35b8-11e7-8d86-6c107070b6ff.png)

**Comment by cl0ne** [comment]
Same as #238

**Comment by rgtk** [comment]
Good eye. Closed.
