### ISSUE TITLE
Choose opening side of select

### ISSUE THREAD

**Issue by MatthiasRMS** [monterail/vue-multiselect#373]
Hi,

I couldn't find a prop to set on which side (up or down) should the dropdown open. By default, it seems like it depends on the scroll, but I'd like to set an exact opening side. 

thanks

**Comment by shentao** [comment]
Added `:open-direction` prop. Accepts `'top' / 'above'` to always open above, `'bottom' / 'below'` to always open below. Otherwise defaults to auto.
Will be available with next release.

**Comment by MatthiasRMS** [comment]
Amazing thanks!

**Comment by shentao** [comment]
Also working on dynamically adjusting the dropdown height if it can’t fit on either side. It also works when the direction is passed by the developer.

**Comment by MattiasMartens** [comment]
Hi, I've been trying to use this property and it seems as if the component is just ignoring it. Specifically I have `open-direction="below"` in the `multiselect` tag, but it still opens above if there's not enough visible space to open below.

For finicky CSS situations like I'm dealing with, it would be nice if there were a dynamically updated class to indicate which the way the drawer is currently opening.

**Comment by MattiasMartens** [comment]
Oh nevermind, I see now that there is! I retroactively thank you.

**Comment by shentao** [comment]
👍 happy to hear that!
