### ISSUE TITLE
Disable clearing search on close

### ISSUE THREAD

**Issue by cl0ne** [monterail/vue-multiselect#374]
Hello,
Is it possible to disable search query clearing when popup have been closed but no selection is made?

**Comment by maximus1010101** [comment]
I'm also looking for the answer to this question.

**Comment by shentao** [comment]
Adding `:preserve-search` prop that will prevent the search query from being cleared after closing the dropdown.
Should be available next release.

**Comment by cl0ne** [comment]
@shentao Thanks!
