### ISSUE TITLE
Unwanted newline in tag mode

### ISSUE THREAD

**Issue by 304NotModified** [monterail/vue-multiselect#379]
We are using v2.0.0-beta.14 and we are seeing an inconsistent styling when using tags. The `<input class=multiselect__input>` element is creating somethings a newline, which looks buggy and awkward. This is all browsers

![image](https://cloud.githubusercontent.com/assets/5808377/26407893/a4b62316-409c-11e7-8915-eccdb8cdd7ea.png)

The first is one line, the 2nd and 3rd are 2 lines.

When coloring the `<input class=multiselect__input>`, you can see that the `<input class=multiselect__input>` is creating the newline

![image](https://cloud.githubusercontent.com/assets/5808377/26407976/dedc908e-409c-11e7-853e-7fd03d82cdaa.png)

how could we prevent this? 

DEMO: https://jsfiddle.net/f7rrtnd0/

**Comment by 304NotModified** [comment]
Added jsfiddle

**Comment by shentao** [comment]
Will be fixed with the new release.

**Comment by davodaslanifakor** [comment]
pleas harry man i need this 
thank you very much...
