### ISSUE TITLE
Missing files in lib directory / build issues

### ISSUE THREAD

**Issue by Toilal** [monterail/vue-multiselect#384]
It seems some files are missing in lib directory. `index.js` requires `./Multiselect`, but no such file is generated by the `bundle:lib` npm task.

Also, `dist` directory seems to contain the distribution files, but those files are ignored from git, so it's not possible to update those files.

main entry point in `package.json` should not be minified (it's up to the final application author to minify all dependencies)

**Comment by Toilal** [comment]
These commits may help :

https://github.com/Toilal/vue-multiselect/commit/91bedcea80df2bf9f12a336d023f8c8d7bbca551 => Removes dist from gitignore and use unminified file as entry point
https://github.com/Toilal/vue-multiselect/commit/2cebcc119d9a9b9b281091a9de2b9698291d742e => Fix CSS files generation in `bundle:dist` (`NODE_ENV=production`)

**Comment by shentao** [comment]
Should be fixed in a new release. The webpack config must be wrong.
