### ISSUE TITLE
Why is not there a .css file?

### ISSUE THREAD

**Issue by afuno** [monterail/vue-multiselect#386]
I added the styles as stated here: http://monterail.github.io/vue-multiselect/#sub-getting-started

```
<template lang="html">
	<div id="app">
		<multiselect v-model="multitags.selected" :options="multitags.list" :multiple="true" :close-on-select="false" :clear-on-select="false" :hide-selected="true" placeholder="Pick some" label="title" track-by="id" @search-change="fetchTags"></multiselect>
	</div>
</template>

<script>
import Multiselect from 'vue-multiselect'

export default {
	//
}
</script>

<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>
```

Everything works, but there are no styles.

It looks like this:
<img width="309" alt="2017-06-05 17 21 55" src="https://cloud.githubusercontent.com/assets/2853419/26787676/89ad222e-4a13-11e7-85ef-ec35ae122485.png">

What is the problem? There are no errors in the browser console. Styles on the page in the browser are not connected.

**Comment by shentao** [comment]
Have you installed using the `@next` tag?
Like 
```
npm install vue-multiselect@next --save
```

**Comment by afuno** [comment]
@shentao Yes. I installed just that.

**Comment by afuno** [comment]
If I write, for example, this code:

```
<style src="vue-multiselect/disssst/vue-multiselect.min.css"></style>
```

I'll get an error about the nonexistent file.

But if I write correctly:

```
<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>
```

There will be no errors in the browser console.

**Comment by shentao** [comment]
That’s weird. Have you checked if the styles are added within the `<head>` tag? Also please make sure to not use `scoped` there.

**Comment by afuno** [comment]
If I add this code to the `head` of the page:

```
<style src="https://unpkg.com/vue-multiselect@2.0.0-beta.14/dist/vue-multiselect.min.css"></style>
```

Styles are connected on the page. But they are not used.

<img width="1309" alt="2017-06-05 17 35 46" src="https://cloud.githubusercontent.com/assets/2853419/26788294/714f093e-4a15-11e7-9751-b205417da60d.png">

**Comment by shentao** [comment]
I meant the `<style>` tag inside `<head>`

**Comment by afuno** [comment]
@shentao Yes. That's exactly what I did.

**Comment by shentao** [comment]
Weird. Could you try adding `@import vue-multiselect/dist/vue-multiselect.min.css` within the style tag? They should show up inside `<head>` :S

**Comment by lucascc** [comment]
I'm using like this:

import Multiselect from 'vue-multiselect'
import 'vue-multiselect/dist/vue-multiselect.min.css'

And it's working just fine.

**Comment by shentao** [comment]
@afuno It should be working. Maybe there are some problems within your setup itself? Can’t think about any other possible problem here. :/

**Comment by hekmatinasser** [comment]
why css file not load in package?
i am using `npm install vue-multiselect --save`

**Comment by sudo-shubham** [comment]
@hekmatinasser use `npm install vue-multiselect@next --save` to install the package.

**Comment by hekmatinasser** [comment]
not load with `vue-multiselect@next` 
only way ` import 'vue-multiselect/dist/vue-multiselect.min.css'`
this problem is rational?
