### ISSUE TITLE
Don't show multiselect__option if empty options

### ISSUE THREAD

**Issue by sleimanx2** [monterail/vue-multiselect#39]
Is there a way to hide the option span if their is no options or if the user didn't start typing yet ?

You can check the search bar in http://krekib.com for a better perspective.

**Comment by shentao** [comment]
Hey @sleimanx2! I have to say it, your site looks really good! 😄 

Right now it’s not possible.
The `no results option` is actually a `slot="noResult"` so you can change what appears inside. You might try changing the slot to an empty span, but I’m not sure if this would help. 

Anyway, this is a very easy improvement so I will try to introduce this change today. I will let you know when it’s available!
All it requires is adding `&& search.length > 0` inside `<li v-show="filteredOptions.length === 0">`.

**Comment by sleimanx2** [comment]
@shentao thank you much appreciated , awesome package by the way !

**Comment by shentao** [comment]
Available in v0.3.0 ;)
