### ISSUE TITLE
bootstrap icons in for-group feed backs and input groups are displayed over the pop-up

### ISSUE THREAD

**Issue by jpujol880807** [monterail/vue-multiselect#392]
Hi i want to use the vue-multiselect plugin with bootstrap form-groups has-feed-back elements 
but the icon of the span  `<span class="glyphicon glyphicon-ok form-control-feedback"></span>`  is displayed over the option of the multiselect element, there is th link to jsfiddle

https://jsfiddle.net/xz2vg7ho/1/

And Here happens with `bootstrap` input-groups

https://jsfiddle.net/xz2vg7ho/3/

**Comment by shentao** [comment]
Hey!

Please add to your css.
```
.form-control-feedback {
  z-index: 0;
}
```
https://jsfiddle.net/n9d2d7vp/

**Comment by jpujol880807** [comment]
Thanks a lot it works like charm now, sorry about my English

**Comment by shentao** [comment]
Not a problem. Happy to help! :)
