### ISSUE TITLE
Is there a way to reset internal value to initial value?

### ISSUE THREAD

**Issue by maxism** [monterail/vue-multiselect#396]
I need to reset vue-multiselect to initial value after selecting some option. In other words I want to prevent changing internal state of vue-multiselect after selection. I found a bit hacky solution:
```
<multiselect 
  :value="value"
  :options="statuses"
  @select="onChange"
  @close="resetValue"
  ref="select"
/>
...
...
methods: {
   resetValue () {
      this.$refs.select.internalValue = [ this.value ]
   }
}
```
Is there a way to implement it in a more correct way?

**Comment by shentao** [comment]
Hey! This approach should work: https://jsfiddle.net/06t5ajf0/
I hope it helps! :)

**Comment by maxism** [comment]
@shentao thanks a lot! But what I should do if ``value`` is computed property with getter and setter?
