### ISSUE TITLE
Dynamic PropsData

### ISSUE THREAD

**Issue by aios** [monterail/vue-multiselect#397]
How i can inject multiselect with dynamic props in my own component?

that is question.

**Comment by shentao** [comment]
Not sure what you mean exactly. You pass props the same way you would do to any other component. 

If you want to pass an object containing all props you can try something like this:
```
<Multiselect v-bind="myProps"></div>
```
More here: https://vuejs.org/v2/api/#v-bind

**Comment by aios** [comment]
Wow!  Nice! Thanks! @shentao
