### ISSUE TITLE
Using more than one label to search multiple column

### ISSUE THREAD

**Issue by antoniputra** [monterail/vue-multiselect#398]
This is my first time using this package, and I feel awesome with this package.

so I am using `<multiselect>` component by wrapping it to my specific dropdown, like: `dropdown-products`.

here is my code:

```javascript
// DropdownProducts.vue
<multiselect
    :value="updatedValue"
    :show-labels="false"
    :options="options"
    :placeholder="placeholder"
    :searchable="searchable"
    :allow-empty="false"
    :multiple="false"
    :label="label"
    :custom-label="customLabel"
    @input="fillHiddenInput">

// I called it like:
<dropdown-products
    :product-id="item.product_id"
    :name="field_product"
    :options="$parent.allItems"
    placeholder="Pilih Produk"
    label="name"
    trackBy="name"
    @input="selectProductChange"></dropdown-products>

```

As you can see, Dropdown Products can be searching by name field as setup in `label="name"` attribute.

but my question is can I search more than one column. something like: `label="['name', 'price']"`, so let user can select product by `name` and `price`?

**NOTE: DropdownProducts is not Asynchronous Select**

**Comment by shentao** [comment]
I recently finished search based on the customLabel output. Would that work? Still, have to release it. Planned to do it this week but struggled to find the time (there are still some fixes left), but I might be able to do it during the weekend.

**Comment by antoniputra** [comment]
it doesn't work when using this approach: `label="['name', 'price']"`, I got this error:

`Invalid prop: type check failed for prop "label". Expected String, got Array.`

**Comment by antoniputra** [comment]
how I can search multiple column, my component is not Asynchronous Select?

**Comment by shentao** [comment]
Please just wait for the next release this weekend.

After the update you should be able to search based on the `customLabel` output. So for example if your `customLabel` looks like this:
```
customLabel (option) { return `${option.label} – ${option.price}`
```
you should be able to search by those two values. Would that be enough?

**Comment by antoniputra** [comment]
That is awesome! Okay I will wait it..

Thanks a million, for your support :+1:

**Comment by Paper-Folding** [comment]
How can I search extra field without showing them? Because my data set contains Chinese characters, I'd like to make users able to search with Pinyin field while not showing Pinyin field on Multiselect.

> Please just wait for the next release this weekend.
> 
> After the update you should be able to search based on the `customLabel` output. So for example if your `customLabel` looks like this:
> 
> ```
> customLabel (option) { return `${option.label} – ${option.price}`
> ```
> 
> you should be able to search by those two values. Would that be enough?

**Comment by Glideh** [comment]
@Paper-Folding a bit late but you can still use a slot template showing only what you want, and a concatenated `customLabel` for the internal search

```vue
<Multiselect
  :options="options"
  :customLabel="methodReturningTheSearchableFieldsJoint"
>
  <template slot="option" slot-scope="props">
    {{ props.option.only_field_that_you_need_to_show }}
  </template>
</Multiselect>
```
