### ISSUE TITLE
Update example on "Basic Usage", missing closing tag. 

### ISSUE THREAD

**Issue by zanematthew** [monterail/vue-multiselect#402]
I was looking over your getting started guide, copy/pasted a few lines of code, and refreshed the page, and noticed your missing the closing tag.

```
<template>
  <div>
    <multiselect v-model="value" :options="options">
  </div>
</template>
```

Unless of course this is something new?

https://monterail.github.io/vue-multiselect/#examples

Lastly it would be nice to have an example showing component registration as well.

btw 🍻 on making an amazing multiselect.

**Comment by shentao** [comment]
Fixed. Thanks!

**Comment by zanematthew** [comment]
Wow, great work!

>Documentation is the life line of code.
