### ISSUE TITLE
May I set options data with value and label

### ISSUE THREAD

**Issue by WenXuanYuan** [monterail/vue-multiselect#406]
In html <option>, it has value and label attributes, may I set :options with an object in multiple selected mode, the @input handle values, but display their correspond label？

**Comment by WenXuanYuan** [comment]
I find use label and tract-by can achieve this, but @input will get the whole option object, is it possible just give :value the array of selected value, and @input just get the input values?

**Comment by pczarn** [comment]
It's currently not possible, because `@input` will always give whole option objects.

**Comment by WenXuanYuan** [comment]
@pczarn Thank you!
