### ISSUE TITLE
<option> inside <multiselect> component, is it possible?

### ISSUE THREAD

**Issue by grzegorztomasiak** [monterail/vue-multiselect#414]
Is it possible to write something like this?

```
<multiselect>
    <option value="foo">Foo</option>
    <option value="bar">Bar</option>
</multiselect>
```

So, multiselect will gather options from the html tags. The reason I need such a scenario is because I use Vue in non spa app, therefor I have forms rendered from the server (Symfony, Twig) which contain simple <select> html elements.

Such a thing works with selectize.js so it was excellent solution, however since I have switched to Vue, I would like to know if that is possible with this component.

**Comment by shentao** [comment]
Hey! You would need to do something like:
```
<multiselect :options="<?php your php code that generates -> [{value: 'foo', label: 'Foo'}, ...] ?>"></multiselect>
```

**Comment by grzegorztomasiak** [comment]
Well, unfortunately that's not an option since on form submission I will never receive selected values on server side. How `selectize.js` works is simply by wrapping <select> HTMLElement with his own

**Comment by shentao** [comment]
Multiselect is more focused on working within SPA environments.
If you need it to work with old fashioned HTML forms you can create a hidden input and add the selected value there.
