### ISSUE TITLE
vue-multiselect component does not display - PLEASE HELP

### ISSUE THREAD

**Issue by shrutijoshi28** [monterail/vue-multiselect#418]
Hello,

I am new to Vue.js and am on an older version( "vue": "1.x", "vue-multiselect": "^2.0.2")
I am trying to add the multiselect component and don't get any error but the component does not load for some reason.

.html

<template>
 <div>
   <multi-select
     v-model="selected"
     :options="options">
   </multi-select>
 </div>
</template>

-------End-------

.js

const multiselect = require('vue-multiselect')
components: { 'multi-select' : multiselect}

----------End--------

DOM

<template>
#document-fragment
 <div>
 <multi-select v-model="selected" :options="options"></multi-select>
 </div>
</template>

I appreciate the help! Thank you!

**Comment by shentao** [comment]
Recently after the release of v2.0.2 stable, you have to use `npm install vue-multiselect@1x` to install a version compatible with Vue 1.x.
You will probably have to change the requirements in `package.json` to `"vue-multiselect: "1.1.4"`.

**Comment by shrutijoshi28** [comment]
Thank you @shentao . I did install the older vue-multiselect and still no luck with the domponent being displayed. It also has the 'vueify' dependency inside the package json.

**Comment by shentao** [comment]
One more thing. Could you try using the ESmodule import style?
```
import Multiselect from 'vue-multiselect'
```
That’s the preferred way.

If you’re using require style imports you probably have to write
```
const multiselect = require('vue-multiselect').default
```

**Comment by shrutijoshi28** [comment]
using import not. But still no luck, I think the '#document-fragment' is the problem, not sure what is causing it [though.]
<img width="598" alt="screen shot 2017-07-05 at 2 59 30 pm" src="https://user-images.githubusercontent.com/3827251/27886860-b3a35788-6192-11e7-864f-cd1e8f68bcbc.png">

**Comment by legreco** [comment]
Same problem here vue-multiselect@2.1.0

**Comment by legreco** [comment]
I have downgraded to vue-multiselect@2.0.8 and everything works.

**Comment by ikhidebright** [comment]
Only downgrading to vue-multiselect@2.0.8 worked for me

**Comment by ahmadrio** [comment]
> I have downgraded to vue-multiselect@2.0.8 and everything works.

thanks it works, you save me bro, after in hours i dont have solution. thanks very much

**Comment by june4th** [comment]
> Only downgrading to vue-multiselect@2.0.8 worked for me

It's so weird, but the newest version works for me everywhere. I installed it on a new Linux PC yesterday, but it did not show. I downgraded it to 2.0.8 worked for me too. However, with the same source code as the newest version, it works on other PC.

**Comment by mattelen** [comment]
If you are having trouble with the new version, please open a new issue and provide a way to reproduce. This original issue is from 5 years ago, running on Vue 1.
