### ISSUE TITLE
Backspace removing last tag - can this be optional?

### ISSUE THREAD

**Issue by JamesMcKenzieJHTNA** [monterail/vue-multiselect#421]
Thank you for developing this component. My users are enjoying it, but find the backspace behavior annoying. When the search query is empty, and you hit the backspace key, the last tag is removed. I'm hoping that this behavior can be disabled.  How would you feel about adding in a config option to disable that?

Thanks so much!

**Comment by vinyoda197** [comment]
same issue got me here. had it resolved with prop  :blockKeys="['Delete']"

**Comment by shentao** [comment]
The solution suggested by @vinyoda197 is the right one. Thanks for sharing!
Closing :)
