### ISSUE TITLE
[FEATURE REQUEST]: Add `matcher` method

### ISSUE THREAD

**Issue by dmitriymarley** [monterail/vue-multiselect#423]
Hello guys,

I've found that there is no way to customize matcher for search input. It would be great, if developers could customize the behavior of it.
E.g., when I type "A", now it's returning all options with "A" in it. But what would be great - find all options **starting** with "A".

**Comment by shubhampatel812** [comment]
Have a look at internalSearch in Props.[Link](http://monterail.github.io/vue-multiselect/#sub-props)
Than use SearchChange event to add your custom search function to filter data.

**Comment by pczarn** [comment]
That's right. Try using `internal-search`. You can see a decent example here: http://monterail.github.io/vue-multiselect/#sub-asynchronous-select

You need to do actual search differently than in an example. For that, you can pass a computed value as multiselect's `options`

for multiselect
```
:options="options"
@search-change="searchChange"
```

for your component
```js
function startsWith (str, query) {
  if (!str) return false
  const text = str.toString().toLowerCase()
  return text.indexOf(query.trim()) === 0
}

// component
export default {
  // ...
  computed: {
    options () {
      return this.entries.filter(entry => startsWith(entry, this.search))
    }
  },
  methods: {
    searchChange (val) {
      this.search = val
    }
  }
}
```
