### ISSUE TITLE
[Bug] Shift+Tab reset value

### ISSUE THREAD

**Issue by DmitriyKurto** [monterail/vue-multiselect#424]
Demo: https://codepen.io/Kurto/pen/QgJELE
vue-multiselect 2.0.0
Navigation with Tab and Shift+Tab works not correctly (resets values)

**Comment by mercs600** [comment]
I have similar situation. I can't back to previous field by shift+tab.

**Comment by pczarn** [comment]
@DmitriyKurto Hello. I found this UX issue is related to two behaviors of multiselect. First, pressing Tab will select the highlighted item, consistently with the native `<select>` element. Second, unlike the `<select>` element, we always open the dropdown on focus. These behaviors can result in selecting the first option by accident.

One simple way to fix it is implemented in PR #430. I will ask Damian about it

**Comment by tochoromero** [comment]
We have the same problem as well, it seems that when you tab out of the multiselect, right before losing the focus and hiding the options the first option is highlighted, so next time you tab in and out of the multiselect the first option (previously highlighted) becomes the selected value.

**Comment by pczarn** [comment]
To fix it, you can pass `:block-keys="['Tab']"` prop to multiselect. I believe we should slightly change multiselect behavior so that we don't need workarounds in the future.

**Comment by DmitriyKurto** [comment]
@pczarn :block-keys="['Tab']"  looks like working. Thanks
