### ISSUE TITLE
Allow showing search box when values are pre-selected

### ISSUE THREAD

**Issue by AndyBursh** [monterail/vue-multiselect#425]
vue-multiselect maintainers,

I have a scenario in which I am using this component and pre-selecting a number of values at page load. In version 2.0.2, the computed property `inputStyle` looks as below, which hides and shows the search box using a style attribute

```
inputStyle () {
    if (this.multiple && this.value && this.value.length) {
        return this.isOpen ? { 'width': 'auto' } : { 'display': 'none' }
    }
},
```

In my scenario, I always want to show the search box and its placeholder. Without resorting to adding `!important` to some of my styles, is there a good way of going about that? This [JS FIddle](https://jsfiddle.net/qgzqg59o/2/) demonstrates a minimum replication of problem.

Regards,
Andy

**Comment by AndyBursh** [comment]
I've just come to work on a pull request for this and realised that the issue doesn't look like it exists on the `master` branch. If somebody can confirm that's the case, I'll close this off and await the next release.

**Comment by pczarn** [comment]
Hi. Do you mean you would like to display the placeholder (such as "Select option") at all times? With the input element, too. If so, we don't support that right now.

**Comment by AndyBursh** [comment]
Yes, that's the case. In essence, I'd like to the input field for a searchable multi-select to be visually identical whether there are selected options or not.

Purely out of curiosity, why isn't it supported? I've added the CSS workaround to my code for the time being.

**Comment by shentao** [comment]
In the 2.0.4 patch, you will be able to customise it with CSS. The patch should ship in the next few days.
