### ISSUE TITLE
Keyboard navigation delay on dropdown

### ISSUE THREAD

**Issue by emilien-d** [monterail/vue-multiselect#426]
Hi,
i found a bug when navigating options with keyboard (chrome 59 / osx),
there is always one or two options delay before the scroll triggers.
Here is a quick gif if of the bug
![juil -11-2017 05-44-17](https://user-images.githubusercontent.com/1143043/28050283-1a38c5a0-65fd-11e7-9f66-248db4717ebe.gif)

**Comment by pczarn** [comment]
Starting to work on this bug. Thanks for the report

The bug was introduced in commit https://github.com/monterail/vue-multiselect/commit/99d03a99bec6df85f39a67b1ac738306cba5a6b3

**Comment by emilien-d** [comment]
you're welcome 👌 
thanks for this nice component
