### ISSUE TITLE
scope="props" not working in carret slot

### ISSUE THREAD

**Issue by ugrupp** [monterail/vue-multiselect#428]
Fiddle:
https://jsfiddle.net/r14r39zc/

I want to add custom code to the carret slot but keep the exisiting "toggle"-behavior. I tried using props.toggle:
```
<template slot="carret" scope="props">
    ...
    <div class="multiselect__select" @mousedown.prevent.stop="props.toggle()"></div>
    ...
</template>
```
which throws the following JS error:

`Uncaught TypeError: props.toggle is not a function`

According to the docs this should be the way to do it - I can't figure out where it screws up... :(

**Comment by pczarn** [comment]
@ugrupp, Could you point to docs for the use of `carret`? As far as I know, the `carret` slot is not even documented.

I believe we should allow `props.toggle()` like you're showing, so I'm going to propose a change for that scoped slot and for docs to describe it

**Comment by ugrupp** [comment]
The carret slot itself is not documented, just mentioned in this issue: #202 I was talking about thr usage of scope="props", which is more or less documented in http://monterail.github.io/vue-multiselect#sub-multiple-select

Thanks for proposing the change. And I agree, this should definitely be documented.

**Comment by shentao** [comment]
The `caret` (previously wrongly called `carret`) slot is now documented and it receives a the toggle function. See docs. :)
