### ISSUE TITLE
onChange is not called if the values somehow result in the initial configuration

### ISSUE THREAD

**Issue by DaHaiz** [monterail/vue-multiselect#43]
problem: i'm persisting the changes on every onChange via ajax.
If you add a value then onChange is called and i'm persisting via ajax.
If you remove that option again onChange is not called again.

It seems that is only compares with the initial config instead of the current one.

**Comment by shentao** [comment]
This might be a problem with not observing the object if it comes straight from the backend. Could you try using the `Vue.set()` method for saving the ajax received state?

**Comment by DaHaiz** [comment]
the data is passed to multiselect by a prop. i am not editing the values at all myself. i'm just mirror it to the backend via changed callback. this is my code, where groups are the selected options.

```
module.exports = {
        components: {
            Multiselect: Multiselect.Multiselect
        },
        props: {
            'groups': {
                type: null,
                default: function() {
                    return [];
                }
            }
        },
        data: function() {
            return {
                options: []
            };

        },
        methods: {
            groupsChanged: function(selectedGroups) {
                this.$http.post('/groups', {groups: selectedGroups}).then(function(response) {
                    console.log('groups updated');
                }, function() {
                    console.error('groups could not be updated');
                });
            },
            updateOptions: function(filter) {
                if (typeof filter == "undefined" || filter.length < 3) {
                    this.$set('options', []);
                    return;
                }

                this.$http.get('/groups', {'filter-name': filter}).then(function(response) {
                    var data = response.data;
                    this.$set('options', data.data);
                }, function() {
                });
            }
        }
    };
```

and this is how its called:

```
<multiselect
                :options="options"
                :multiple="true"
                :selected.sync="groups"
                :on-search-change="updateOptions"
                :clear-on-select="true"
                :on-change="groupsChanged"
                label="name"
                key="id"
                placeholder="Tippen zum Suchen.."
                deselect-label="Gruppe entfernen"
                select-label="Gruppe hinzufügen"
                selected-label="Hinzugefügt"
        >
            <span slot="noResult">
                Keine Gruppe gefunden. Versuchen Sie bitte eine andere Suche..
            </span>
        </multiselect>
```

**Comment by shentao** [comment]
If you’re passing the `:on-change` prop you should modify the selected array yourself. 
In this case your method `groupsChanged` might change the selected array like this:

```
groupsChanged: function(selectedGroups) {
  this.groups = selectedGroups
  // or
  this.$set('groups', selectedGroups)

  // your code follows
}
```

This also means you should remove the `.sync` modifier as it won’t work, because the multiselect component never changes the selected array if the `:on-change` prop is present. This is due to Vuex support where you’re not supposed to mutate stuff outside of mutations.

If you don’t require such functionality and want to mutate the state directly, you can simply remove the `:on-change` prop and create a watch that will ajax-autosave the selected array for you.
Like this:
```
watch: {
  'groups' (selectedGroups) {
     this.$http.post('/groups', {groups: selectedGroups}).then(function(response) {
       console.log('groups updated');
     }, function() {
       console.error('groups could not be updated');
     });
  }
}

**Comment by DaHaiz** [comment]
thanks a lot for your great support! that did it. i went for removing .sync and set it myself in the onChange callback. i have to dig into vuex :)

**Comment by shentao** [comment]
Glad I could help. :) 
I highly recommend Vuex! Makes arguing about the state a lot easier!
