### ISSUE TITLE
Id from object

### ISSUE THREAD

**Issue by majweb** [monterail/vue-multiselect#432]
I have options
days: [
{ id: 1, day: 'Poniedziałek' },
{ id: 2, day: 'Wtorek' },
{ id: 3, day: 'Środa' },
{ id: 4, day: 'Czwartek' },
{ id: 5, day: 'Piątek' },
{ id: 6, day: 'Sobota' },
{ id: 7, day: 'Niedziela' }
]
<multiselect v-model="newItem.plan_start" :options="days" placeholder="Wybierz dzień" name="plan_start" label="day" track-by="id"></multiselect>
How in model return id of selected item? I need this to laravel request

**Comment by pczarn** [comment]
@majweb, could you show concrete code so that we can help you?

If, for example, you're using `v-model` with multiselect, try accessing the id of the selected value simply with `value.id`. Here is an example of single selection of objects like you probably have: http://monterail.github.io/vue-multiselect/#sub-single-select-object

**Comment by majweb** [comment]
Imię polskojęzyczne więc spróbuje😊. Bazowałem na tym przykładzie lecz interesuje mnie zwrócenie nie całego obiektu tylko id w nim mieszczacego się. Mam model , który wchodzi w skład metody do żadania post i ten input misi zawierać wartość liczbowa czyli id zwracanego obiektu.15.07.2017 19:18 Piotr Czarnecki <notifications@github.com> napisał(a):@majweb, could you show concrete code so that we can help you?
If, for example, you're using v-model with multiselect, try accessing the id of the selected value simply with value.id. Here is an example of single selection of objects like you probably have: http://monterail.github.io/vue-multiselect/#sub-single-select-object

**Comment by shentao** [comment]
There are already issues regarding returning just a primitive value rather than the whole object passed to `v-model`. I’m still thinking how to properly approach this and not break the support for dynamic/async options and preselecting options that don’t yet exist in the options list.

As for now, please manually extract the needed value and use it. When preselecting, try to find the option/rebuild it into an object that matches the option schema.

**Comment by majweb** [comment]
```
<label class="typo__label">Select with search</label>
<multiselect v-model="plan_start" :options="days" placeholder="Select one" label="day"              
track-by="day"></multiselect>
```

data () {
   return {
      days: [
      { id: 1, day: 'Poniedziałek' },
      { id: 2, day: 'Wtorek' },
      { id: 3, day: 'Środa' },
      { id: 4, day: 'Czwartek' },
      { id: 5, day: 'Piątek' },
      { id: 6, day: 'Sobota' },
      { id: 7, day: 'Niedziela' }
     ],
     newItem : {'plan_start':'','part_id':'','exercise_id':'','series':'','repeat':'','weight':'','time':''}
     methods: {
                 axios.post('/klient/plany/zapisz', {
                    plan_start: this.newItem.plan_start,
                    part_id: this.newItem.part_id,
                    exercise_id: this.newItem.exercise_id,
                    series: this.selected,
                    repeat: this.repeatsValue,
                    weight: this.weightValue,
                    time: this.timeValue
                })
                        .then(response => {
                            console.log(response);
                        })
                        .catch(function (error) {
                            console.log(error);
                        });
     
    }
In newItem.plan_start must by Id from object

**Comment by stevebauman** [comment]
This is easily dealt with. Simply add a `@input` listener and push the ID's into another data array that you send with your `post` requests:

```vue
<template>
    <multiselect
        v-model="users"
        :options="options"
        :multiple="true"
        label="name"
        track-by="id"
        placeholder="Select approvers"
        @input="updateApprovers"
    ></multiselect>
</template>

<script>
    import Multiselect from 'vue-multiselect';

    export default {
        props: {
            dataUrl: String,
            saveUrl: String,
        },

        data() {
            return {
                approvers: [],
                users: [],
                options: [],
            }
        },

        mounted() {
            this.fetchApprovers();
        },

        methods: {
            /**
             * Updates the approvers form array when a selection is made.
             *
             * @param users
             *
             * @return void
             */
            updateApprovers(users) {
                let approvers = [];

                users.forEach((user) => {
                     approvers.push(user.id);
                });

                this.form.approvers = approvers;
            },

            /**
             * Fetches valid approvers.
             *
             * @return void
             */
            fetchApprovers() {
                axios.get(this.dataUrl).then(({data}) => {
                    this.options = data;
                });
            },
        }
    }
</script>

```

**Comment by majweb** [comment]
show me how this looks im my example

**Comment by pczarn** [comment]
@majweb 

W przykładzie ze zmianami dla `plan_start` to by wyglądało tak

```
<multiselect v-model="plan_start" @input="save" :options="days" placeholder="Select one" label="day"              
track-by="day"></multiselect>
```

```
data () {
  return {
    days: [
      { id: 1, day: 'Poniedziałek' },
      { id: 2, day: 'Wtorek' },
      { id: 3, day: 'Środa' },
      { id: 4, day: 'Czwartek' },
      { id: 5, day: 'Piątek' },
      { id: 6, day: 'Sobota' },
      { id: 7, day: 'Niedziela' }
    ],
    newItem : {'plan_start': null,'part_id':'','exercise_id':'','series':'','repeat':'','weight':'','time':''}
  }
}
```

```
methods: {
  save (plan_start) {
    axios.post('/klient/plany/zapisz', {
      plan_start: plan_start.id,
      part_id: this.newItem.part_id,
      exercise_id: this.newItem.exercise_id,
      series: this.selected,
      repeat: this.repeatsValue,
      weight: this.weightValue,
      time: this.timeValue
    })
    .then(response => {
      console.log(response);
    })
    .catch(function (error) {
      console.log(error);
    });
  }
}
```

**Comment by majweb** [comment]
Co w przypadku jeżeli używam @submit.prevent na formularzu i wtedy wysyłam żadanie post axiosem a widzę że metoda jest przypisana do @input?22.07.2017 16:59 Piotr Czarnecki <notifications@github.com> napisał(a):@majweb
W przykładzie ze zmianami dla plan_start to by wyglądało tak
<multiselect v-model="plan_start" @input="save" :options="days" placeholder="Select one" label="day"              
track-by="day"></multiselect>

data () {
  return {
    days: [
      { id: 1, day: 'Poniedziałek' },
      { id: 2, day: 'Wtorek' },
      { id: 3, day: 'Środa' },
      { id: 4, day: 'Czwartek' },
      { id: 5, day: 'Piątek' },
      { id: 6, day: 'Sobota' },
      { id: 7, day: 'Niedziela' }
    ],
    newItem : {'plan_start': null,'part_id':'','exercise_id':'','series':'','repeat':'','weight':'','time':''}
  }
}

methods: {
  save (plan_start) {
    axios.post('/klient/plany/zapisz', {
      plan_start: plan_start.id,
      part_id: this.newItem.part_id,
      exercise_id: this.newItem.exercise_id,
      series: this.selected,
      repeat: this.repeatsValue,
      weight: this.weightValue,
      time: this.timeValue
    })
    .then(response => {
      console.log(response);
    })
    .catch(function (error) {
      console.log(error);
    });
  }
}

**Comment by KsCorrales** [comment]
@stevebauman your answer works percect thanks.

**Comment by pczarn** [comment]
@majweb then without `@input`

```
data () {
  return {
    days: [
      { id: 1, day: 'Poniedziałek' },
      { id: 2, day: 'Wtorek' },
      { id: 3, day: 'Środa' },
      { id: 4, day: 'Czwartek' },
      { id: 5, day: 'Piątek' },
      { id: 6, day: 'Sobota' },
      { id: 7, day: 'Niedziela' }
    ],
    newItem : {'plan_start': null,'part_id':'','exercise_id':'','series':'','repeat':'','weight':'','time':''}
  }
}
```

```
methods: {
  save () {
    axios.post('/klient/plany/zapisz', {
      plan_start: this.newItem.plan_start.id,
      part_id: this.newItem.part_id,
      exercise_id: this.newItem.exercise_id,
      series: this.selected,
      repeat: this.repeatsValue,
      weight: this.weightValue,
      time: this.timeValue
    })
    .then(response => {
      console.log(response);
    })
    .catch(function (error) {
      console.log(error);
    });
  }
}
```

**Comment by jetmiko** [comment]
@majweb:
this simple idea will do the trick.
1. change your days variable as below:
`var days = {1: 'Sun', 2: 'Mon', 3: 'Tue', 4: 'Wed', 5: 'Thu', 6: 'Fri', 7: 'Sat'}`

2. insert component:
```
<multiselect 
     v-model="plan_start" 
     :options="Object.keys(days)" 
     :custom-label="opt => days[opt]" 
</multiselect>
```

Have a try, it works for me.

**Comment by aocneanu** [comment]
@jetmiko great approach!

@majweb and if you need the preserve the initial type of the keys add `.map(Number)`

> <multiselect 
>     v-model="plan_start" 
>    :options="Object.keys(days).map(Number)" 
>     :custom-label="opt => days[opt]"> 
> </multiselect>

**Comment by sietzekeuning** [comment]
<multiselect 
                                                v-model="rule.type_ids[i]" 
                                                @change="getVehicles" 
                                                :options="types.map(type => type.id)" 
                                                :custom-label="opt => types.find(x => x.id == opt).name">
                                            </multiselect>

**Comment by realnot** [comment]
Hi guys, I still have a problem with this plugin. When I try to modify an item that I retrieve from the backend with an axios request, instead to see the selected value I see the placeholder:"select a story". I tried to use both (v-model and :value) without success. Initially the multiselect should be initialized with the correct value.

If I use :value="chapter.story" then I can see the properly value, but can't swtich to another one

```
<multiselect
  v-model="chapter.story"
  :searchable="false"
  track-by="id"
  placeholder="Select a story"
  :options="stories.map(story => story.id)"
  :custom-label="opt => stories.find(x => x.id == opt).title"
/>
```

If I use :value="chapter.story" then I can see the properly value, but can't swtich to another one

Any suggestion?

**Comment by shentao** [comment]
@realnot if you’re passing primitives as options (so IDs only), you don’t need `track-by` anymore.

**Comment by realnot** [comment]
@shentao, ok thanks, but I'm still getting problem on find method. When I retrieve the object from the backend, I get "undefined" the first time.

chapter is an object: 

chapter: {
    ...
    ...
    story: 4
}

the options is a list of objects:

options: [
   0: {id: 1, title: 'my story title 1'},
   1: {id: 2, title: 'my story title 2'},
]

The prolem here is that initially when I get the chapter, story is not an object. Maybe the solution is binding the :value to a custom method that change the selected value from: `story: 4` to `story: {id: 4, title: 'my story title 4'}?

**Comment by shentao** [comment]
Yeah. That’s one of the requirements. The value has to be a subset of the options and have the same structure (so if options are objects, so must be the value).
It doesn’t have to include all the fields. The minimum is the property that you passed into `track-by` which in this case would be `id` and `title` that you might be using for showing the label. 

Please take a look at the following example: https://vue-multiselect.js.org/#sub-single-select-object

**Comment by Amersfoj** [comment]
> What worked for me with an array of objects like:
> 
> let types = [
> {id: 1, name: "john"},
> {id: 2, name: "steve"}
> ];
> 
> ```
> <multiselect 
>   v-model="rule.id" 
>   :options="types.map(type => type.id)" 
>   :custom-label="opt => types.find(x => x.id == opt).name">
> </multiselect>
> ```

@sietzekeuning In my system the selected value comes from the database in the form of an integer, your code selects the correct value based on that idea. However, every option is Selected, so there is only the "Press enter to remove" option on each option. So I have to click that on any row and then I can select a different row.
Any idea how this happens?

**Comment by kmb645** [comment]
Multiselect explain about these [here](https://vue-multiselect.js.org/#sub-select-with-search) 


> [ { id: 1, day: 'Poniedziałek' }, { id: 2, day: 'Wtorek' }]

```
<multiselect 
  v-model="value" 
  :options="options" 
  :custom-label="customLabel" 
   track-by="day">
</multiselect>

//Now you have to create a method 
customLabel ({ name, day }) {
      return day
}

**Comment by vortechron** [comment]
this issue should be include by default in the library instead of these little hacks hm

**Comment by shentao** [comment]
@vortechron Maybe it will in the future version. Maybe not. If you dislike the "hacks", feel free to build your own solution. I’m not forcing anyone to use this library.

**Comment by vortechron** [comment]
@shentao hey man, your library is awesome, used it all the time, just this bit bother me. hm

**Comment by shentao** [comment]
Yeah, I get that, I also had some use cases where this could be useful and I’m strongly considering adding this to v3 that I finally found some time to work on again. But the workaround isn’t that problematic IMO. And as answered in here on any of the duplicates of that feature request – this collides with how the async function works. I don’t want to introduce mutually exclusive features since that might end up being even more confusing.

**Comment by nadavelyashiv** [comment]
> What worked for me with an array of objects like:
> 
> let types = [
> {id: 1, name: "john"},
> {id: 2, name: "steve"}
> ];
> 
> ```
> <multiselect 
>   v-model="rule.id" 
>   :options="types.map(type => type.id)" 
>   :custom-label="opt => types.find(x => x.id == opt).name">
> </multiselect>
> ```

Great solution, but it creates a problem with search, as the label field is not stated and the search works by searching the IDs.
