### ISSUE TITLE
Block space?

### ISSUE THREAD

**Issue by Hillcow** [monterail/vue-multiselect#435]
Hey there,

is there anyway to prevent spaces in tags? I tried to use :block-keys, but it did not recognise 'Space', 'Spacebar' or 'Space Bar'.

Thank you!

**Comment by pczarn** [comment]
Hi. `block-keys` only works for selecting and unselecting, currently the keys that can result in that are `Enter`, `Delete` and `Tab`. Unfortunately there is currently no way to disallow certain characters in tags. @shentao are we going to add an option for this?

**Comment by pczarn** [comment]
Of course you may check for spaces in your input handler, but the search phrase with spaces will still show up in multiselect as if it were possible to add that tag.
