### ISSUE TITLE
V-Model returning objects

### ISSUE THREAD

**Issue by Hillcow** [monterail/vue-multiselect#436]
Hey there,

I would like to use a hidden input to post the selected tags to an endpoint, like:

`tag1,tag2,tag3,tag4,tag5`

Unfortunately, if I am using objects to display the tags - because I would like to show the name as well as the amount of times the tag has been used in the past - I only get

`[object Object],[object Object],[object Object],[object Object],[object Object]`

Is there any option to tell the plugin that only one property of the object should be passed instead of whole objects?

Thank you!

**Comment by Zip753** [comment]
If you want to simply display the property of each tag, e.g. name, then you should use `label` prop. In case you want to have a more sophisticated label based on each tag object, you can use `custom-label` prop as shown in [this example](http://monterail.github.io/vue-multiselect/#sub-select-with-search) in the documentation.

For instance, if you want to display the frequency of the tag usage alongside its name, your code might look similar to this fiddle (based on the example linked above): https://jsfiddle.net/zip753/ykxk68jy/1/

**Comment by Hillcow** [comment]
@Zip753 unfortunately this is not what I was asking for. On your code you can see that

`{{ value  }}`

is an object. But I can't process that. I want it to be an array of the 'name' property only, which I would like to have in an hidden input, while still having "frequency" to display the results.

**Comment by Zip753** [comment]
If you want to show only names and process "frequency" outside of multiselect, you can then pass an array of names as an input, say `tags.map(tag => tag.name)` instead of `tags`. However I don't see why you can't simply pass `tags` as options, specify `label="name"` and process `value.name` instead of `value` for each tag.

Please provide more context for your use case if you have any other doubts about this.

**Comment by Hillcow** [comment]
You're right, simply had to change the 'selectedTags' with the map function like you described. Thank you!
