### ISSUE TITLE
Taggable search to prioritise search results first

### ISSUE THREAD

**Issue by rickbolton** [monterail/vue-multiselect#443]
Hi,

I'm wondering whether it would be a good idea to push the tag to the end of the options rather than unshift - https://github.com/monterail/vue-multiselect/blob/2.0/src/multiselectMixin.js#L313

My reason for this is I like the fact a user can press enter when searching and making it taggable prevents them from doing this unless they get an exact search match. (Without using the arrow keys as I understand they can still do this)

e.g. current behaviour 
<img width="459" alt="screen shot 2017-07-19 at 11 09 37" src="https://user-images.githubusercontent.com/10371256/28362025-c6f70718-6c72-11e7-82b8-874e325ff8ce.png">

Proposed behaviour:
<img width="468" alt="screen shot 2017-07-19 at 11 10 14" src="https://user-images.githubusercontent.com/10371256/28362045-e21deb4c-6c72-11e7-8ab9-8ddcac41b2e3.png">

I'd be more than happy with a prop that could change this perhaps?

Let me know as I could do a pull request if you'd like?

**Comment by pczarn** [comment]
Hi. Adding yet another configuration option is something to think about. We will let you know next week

**Comment by rickbolton** [comment]
OK thanks

**Comment by rickbolton** [comment]
@pczarn Hey, sorry to bother you. Just wondering whether you've had chance to discuss this at all or should I "fork off" haha

**Comment by shentao** [comment]
Sorry, it’s just now that I finally reached this issue. There’s been a lot of them lately...
I kinda like the idea of `tag-position`prop that decides whether to use `unshift` or `push`.

Would you like to add a PR for this?

**Comment by rickbolton** [comment]
@shentao great! I've submitted a PR #528. I'll close this issue and let you review. 👍

**Comment by shentao** [comment]
Thanks! Looking into it :)
