### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by shah587** [monterail/vue-multiselect#447]
I have array of customers  and each customer object has several properties that are unique.

Customer = {   Id : 0, RegistrationNumber : 1, NationalCompnayNumber : 1 }

so is it possible to search by Id, RegistrationNumber  or  NationalCompnayNumber  ?

**Comment by pczarn** [comment]
Yes, with custom search. The explanation is in https://github.com/monterail/vue-multiselect/issues/319
