### ISSUE TITLE
Force array mode?

### ISSUE THREAD

**Issue by iamvitali** [monterail/vue-multiselect#453]
Hi,
I've noticed if I'm using `:multiple="true"` the value that is stored in `v-model` variable is an array, however, if I use `:multiple="false"` it's a string.

Is it possible to force it into array mode, so that even if it's not a multiple choice selection it still stores that one single answer as an array?

**Comment by Zip753** [comment]
Hi @iamvitali,
If you want to wrap your value in array with `:multiple="false"`, you could create a computed that would wrap your value, like this:
```javascript
computed: {
  wrappedValue() {
    return [this.value];
  }
}
```
given that `value` is used as a model for multiselect component.

Does that answer your question?
