### ISSUE TITLE
":hide-selected" not works

### ISSUE THREAD

**Issue by KsCorrales** [monterail/vue-multiselect#454]
i use ":hide-seleccted='true'" but not works, the options was updated by vuex is any problem with vuex or if the data is set for other action or method?

**Comment by Zip753** [comment]
Hi @KsCorrales 
Can you please elaborate on your problem? A jsfiddle with the example would be great.

**Comment by Xationch** [comment]
Same problem here

I'm using a Ajax request

```
<multiselect v-model="selectedUsers" :hide-selected="true" :internal-search="false" label="name" track-by="id" :options="users" :multiple="true" :searchable="true" :loading="isLoading" @search-change="asyncFindUsers" :show-no-results="false"></multiselect>
```

```
users: [
	{ name: 'Jean', id: 1 },
	{ name: 'Louis', id: 2 }
],
```

```
asyncFindUsers (query) {
	if (query) {
		this.isLoading = true
		axios.get('/api/user/' + query + '/search').then(({data}) => {
			this.users = data.data
			this.isLoading = false
		})
	}
},
```

**Comment by KsCorrales** [comment]
@Zip753 i'ts just that, only i get the data from axios, but :hide-selected not works, i'ts set to true but not hide the options selected.

@Xationch i'ts my same problem

**Comment by Zip753** [comment]
@Xationch thanks for providing an example!

This is a bug, apparently `hide-selected` is not respected when `internal-search` is `false`. I'll be preparing a fix soon.

**Comment by jsgv** [comment]
Any updates on this fix?

**Comment by shentao** [comment]
Fixed. Sorry for the delay. Should be published on Saturday/Sunday.

**Comment by ScriptMint** [comment]
I am using vue-multiselect 2.0.3 and still this hide selected option doesn't work. What additional I have to do in order to make it work?
