### ISSUE TITLE
Pasting Multiple Tags

### ISSUE THREAD

**Issue by michaelpelletier** [monterail/vue-multiselect#455]
Hi!

I'm looking to adopt this for a project and I'm wondering what support is like for pasting multiple tags. I didn't see anything mentioned in the documentation, and it looks like pasting in a comma-separated-list is still treated as one tag. Eg: I paste "blue, yellow" and it's treated as one tag instead of two. Is there a thing that is configurable or would be an easy change?

**Comment by floptwo** [comment]
No configurable thing but this is the way I did it. I hope it helped.

```html
<multiselect ... @tag="addTag"></multiselect>
```

```js
export default {
    // ...
    methods: {
        addTag: function (value) {
            value.split(',').map((item) => {
                this.selected_tags.push({
                    name: item.trim(),
                });
            });
        },
        // ...
    } 
}
````

**Comment by michaelpelletier** [comment]
Oh that'll work perfectly, thanks for the help!

**Comment by andresuchdata** [comment]
> No configurable thing but this is the way I did it. I hope it helped.
> 
> ```
> <multiselect ... @tag="addTag"></multiselect>
> ```
> 
> ```js
> export default {
>     // ...
>     methods: {
>         addTag: function (value) {
>             value.split(',').map((item) => {
>                 this.selected_tags.push({
>                     name: item.trim(),
>                 });
>             });
>         },
>         // ...
>     } 
> }
> ```

Thanks @floptwo ! works directly
