### ISSUE TITLE
Search by group?

### ISSUE THREAD

**Issue by iamvitali** [monterail/vue-multiselect#456]
Is there a way to search groups in `<multiselect>`?

So if it finds a group I would see the group label and all the options for that group.

**Comment by Zip753** [comment]
If you pass the groups to `<multiselect>`, then you have the control over them, right? :) So simply find the group you want in the options you're passing, it doesn't have to do anything with `<multiselect>` really.

**Comment by shentao** [comment]
What I think @Zip753 might mean is that you can use your own search function by disabling the `:internal-search` by passing `false`. This way you can react to `@search` changes yourself and adjust the `:options`. Ofc you will have to mimic the results structure as it is in multiselect itself to fit the grouping requirements but that shouldn’t be much of a problem.
Please look into the source code to see an example of such transfrom.

**Comment by Zip753** [comment]
My bad, I thought of programmatic search somehow.

**Comment by mrleblanc101** [comment]
Why did you close ? It would be a nice enhancement to have this natively
