### ISSUE TITLE
Handle with many input forms

### ISSUE THREAD

**Issue by approached** [monterail/vue-multiselect#458]
Hi@all

my form has 12 multiselect inputs. But how i can handle with data? I don't want create 12 different methods.

Example:
https://jsfiddle.net/oa3tsjcu/

**Comment by shentao** [comment]
Hey!

You can pass the `id` prop to the multiselect. All the events are called with `id` as the second param. This can be used to distinguish which component called the method.

Example:
https://jsfiddle.net/7v5pegm2/
