### ISSUE TITLE
Custom selected option with :multiple=false

### ISSUE THREAD

**Issue by benlbrm** [monterail/vue-multiselect#462]
Hello,

I'm trying to deal with slot template to customize the multiselect
:multiple="false" in my case
I want to add a span with a color from the selected object on the selected option.

I've been able to do it on the option list but not in the selected tag
See the example here:
https://jsfiddle.net/ssbz2tr5/

How can I solve this ?

Thanks
Benoît

**Comment by arenddeboer** [comment]
Did you find a way to do this ? It looks like this is not possible yet, no tag slot with :multiple="false"

**Comment by benlbrm** [comment]
Hi,
Not yet, I'm waiting for a feedback from the author.

**Comment by iMacTia** [comment]
Same issue here!

**Comment by shentao** [comment]
Crap. Wrong issue number for the commit.

https://jsfiddle.net/hrbft25k/ 
This is the closest I could get. As for now, please use the `loading` slot.
Notice I also added a small change to the styles.

**Comment by benlbrm** [comment]
Hi !

Your solution looks good for me, result is ok.
But since I add it into my app, I have the following error:
`[Vue warn]: <transition> can only be used on a single element. Use <transition-group> for lists.

found in

---> <VueMultiselect>
       <EventModal> at C:\Users\xxx\Code\xxx-Desktop\app\src\renderer\views\planning\Modals\Event\index.vue
         <Index> at C:\Users\xxx\Code\xxx-Desktop\app\src\renderer\views\planning\index.vue
           <AppMain> at C:\Users\xxx\Code\xxx-Desktop\app\src\renderer\components\layout\AppMain.vue
             <Root>`

The multiselect is used with other componants inside a transition tag
Any idea ?

**Comment by shentao** [comment]
Have you wrapped the inside of the `<transition>` element into a single div? That might be the problem.

**Comment by benlbrm** [comment]
It is inside a transition like this:

`<template>
  <transition
    :name="transition"
    mode="in-out"
    appear
    :appear-active-class="enterClass"
    :enter-active-class="enterClass"
    :leave-active-class="leaveClass"
    @beforeEnter="beforeEnter"
    @afterLeave="afterLeave"
  >
    <div :class="classes">
      <div class="modal-background" @click="cancel"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">{{ title }}</p>
          <button class="delete" @click="cancel"></button>
        </header>
        <section class="modal-card-body">
          <slot>
            <div class="block">
              
              <p class="control">
                <label class="label">Type</label>
                <multiselect
                  v-model="eventType"
                  :options="eventTypes"
                  :multiple="false"
                  :close-on-select="true"
                  :show-labels="false"
                  v-on:close="getEventTypeIdFromEventTypeSelected"
                  placeholder="Select an event type"
                  label="name"
                  track-by="_id">
                  <template slot="option" scope="props">
                    <span class="color" :style="{backgroundColor: props.option.color}"></span>
                    <span>{{ props.option.name }}</span>
                 </template>
                 <template slot="loading">
                   <span class="color" :style="{backgroundColor: eventType.color}"></span>
                   <span>{{ eventType.name }}</span>
                </template>
                </multiselect>
                </span>
              </p>
              
              <p class="control" v-if="eventFromForm.event_type_id != 'eventType_CP' && eventFromForm.event_type_id != 'eventType_RTT' && eventFromForm.event_type_id != 'eventType_Support'">
                <label class="label">Title</label>
                <input class="input" type="text" placeholder="Title of the event" v-model="eventFromForm.title">
              </p>
              
              <p class="control" v-if="eventFromForm.event_type_id != 'eventType_CP' && eventFromForm.event_type_id != 'eventType_RTT' && eventFromForm.event_type_id != 'eventType_Support'">
                <label class="label">Description</label>
                <textarea class="textarea" placeholder="Description of the event" v-model="eventFromForm.description"></textarea>
              </p>
              
              <div class="columns">
                <div class="column">
                  <p class="control">
                    <label class="label">From</label>
                    <datepicker
                      placeholder="DD/MM/YY"
                      :config="{
                        dateFormat: 'Y-m-d H:i',
                        static: false,
                        enableTime: true,
                        enableSeconds: false, // disabled by default
                        time_24hr: true, // AM/PM time picker is used by default
                        defaultHour: 7,
                      }"
                      v-model="eventFromForm.start">
                    </datepicker>
                  </p>
                </div>
                  
                <div class="column">
                  <p class="control">
                    <label class="label">To</label>
                    <datepicker
                      placeholder="DD/MM/YY"
                      :config="{
                        dateFormat: 'Y-m-d H:i',
                        static: false,
                        enableTime: true,
                        enableSeconds: false, // disabled by default
                        time_24hr: true, // AM/PM time picker is used by default
                        defaultHour: 7,
                      }"
                      v-model="eventFromForm.end">
                    </datepicker>
                  </p>
                </div>
              </div>
              
              <p class="control">
                <label class="label">Assign to</label>

                  <multiselect
                  v-model="resources"
                  :options="options"
                  :multiple="true"
                  :close-on-select="true"
                  :clear-on-select="false"
                  :hide-selected="true"
                  :show-labels="false"
                  placeholder="Pick someone"
                  :custom-label="usersMultiselectLabel"
                  track-by="id"
                  group-values="resources"
                  group-label="office"
                  v-on:close="getResourceIdsFromResourceSelected"
                  v-on:remove="removeResourceFromResourceSelected">
                </multiselect>

              </p>
              
              <p class="control">
                <label class="checkbox">
                  <input id="confirmed" type="checkbox" name="confirmed" v-model="eventFromForm.confirmed">
                  Confirmed event
                </label>
              </p>
            </div>
          </slot>
        </section>
        <footer class="modal-card-foot">
          <a v-if="isSavable" class="button is-primary" @click="save">{{ okText }}</a>
          <a class="button" @click="cancel">{{ cancelText }}</a>
          <a v-if="isDeletable" class="button is-danger align-right" @click="remove">
            <span class="icon"><i class="fa fa-trash-o"></i></span>
            <span>{{ deleteText }}</span>
          </a>
        </footer>
      </div>
    </div>
  </transition>
</template>`

**Comment by shentao** [comment]
I think this might be useful: https://vuejs.org/v2/guide/transitions.html#List-Transitions

**Comment by benlbrm** [comment]
Sorry, my previous comment isn't really readable...
In principe I did like this:

The Multiselect is used inside a componant
The code principe:

-> Template
  -> Transition
    -> div
        -> multiselect
        -> multiselect
        -> Datepicker
         -> inputs

I don't know if problem come from my side, but it can.

**Comment by benlbrm** [comment]
No list inside my template, the only list that I can see, can be done by the multiselect to display the options

**Comment by shentao** [comment]
Oh! I think this line has to be changed:
```
<template slot="loading">
  <span class="color" :style="{backgroundColor: eventType.color}"></span>
  <span>{{ eventType.name }}</span>
</template>
```

to
```
<template slot="loading">
  <span class="color" :style="{backgroundColor: eventType.color}"></span>
</template>
```

The label will be present anyway.

**Comment by benlbrm** [comment]
That was the point !

Thanks very much ! Problem solved.

**Comment by shentao** [comment]
Glad it’s resolved. Happy to help! Good luck with your project. :)

**Comment by gabrielchiconi** [comment]
I'm sorry to necro, but to anyone that gets here through search engines, a cleaner solution I've found follows the following steps:

- Set `:taggable='true'`
- Set `:multiselect='false'`
- Set `@tag='setValue'` where `setValue` is a function that updates the same property as `v-model`

This can be done with object-like options as well, just set the `v-model` property to the specific format 😉
