### ISSUE TITLE
Height is hiding inside parent height

### ISSUE THREAD

**Issue by theromie** [monterail/vue-multiselect#464]
![screenshot_1](https://user-images.githubusercontent.com/11131555/29107149-512a2b3e-7cf6-11e7-89fc-cb3a9241fe5b.png)
Multiselect options height is not overlapping parent height. Its hiding inside parent height
I am showing multiselect in hero banner which having css `min-height: 460px;height: auto;position: relative;z-index: 1;`

**Comment by mapkbalaji** [comment]
How did you resolve this?

**Comment by theromie** [comment]
Removed that background image shape
