### ISSUE TITLE
Layout Issue

### ISSUE THREAD

**Issue by emmanesguerra** [monterail/vue-multiselect#469]
Hi Guys,

Can someone please help me with this..

![layout problem](https://user-images.githubusercontent.com/14354073/29208669-9acb66c2-7ebd-11e7-89bd-f865db489535.png)

I can set the z-index thru inspect element to much higher value but once I re-open the dropdown, it goes under the table.

If this issue has been fix by in other thread, please share link as I can't seem to find it.

Thanks

**Comment by JeffBeltran** [comment]
@emmanesguerra try  

```
.multiselect--active {
  z-index: 3;
}
```
Found that on #392 and it fixed my issue

**Comment by lmatab** [comment]
@emmanesguerra  you can try to add  a lower z-index value to the table

.table {
z-index:0;
}

I did it and it work on my case

**Comment by shentao** [comment]
This issue should be handled by using `z-index` as the other people already mentioned.
I hope that worked for you. Closing the issue :)

**Comment by johndatserakis** [comment]
@JeffBeltran Thank you that worked perfect.
