### ISSUE TITLE
hide-selected not working after setting options in computed property

### ISSUE THREAD

**Issue by chagamkamalakar** [monterail/vue-multiselect#47]
Hi
I am getting data through ajax request, and then setting options property , hide-selected not working as expected . 

even it doesn't show text as "'Press enter to remove" for respective option after selecting the option

and this causes same option selected multiple times .

am using options as array of objects , and using  key , label  props

```
<multiselect 
:options.sync="obj.options" 
:selected.sync="obj.selected" 
:multiple.sync="obj.isMulti" 
:searchable="isSearchable" 
:allow-empty="allowEmpty" 
:hide-selected="obj.hideSelected" 
:touched.sync="isTouched" 
:max-height="400" 
:placeholder.sync="obj.placeholder" 
:allow-empty="allowEmpty"  
:label.sync="obj.label" 
:key.sync="obj.id">
</multiselect>
```

and obj is : 

```
obj : {
					options: [{"id":1,"name":"Multi Day Tour","slug":"multi-day-tour","type":"TOUR","subtype":"TYPE"},{"id":2,"name":"Full Day Tour","slug":"full-day-tour","type":"TOUR","subtype":"TYPE"},{"id":3,"name":"Half Day Tour","slug":"half-day-tour","type":"TOUR","subtype":"TYPE"}],
					selected:[],
					placeholder:"please select a tour type",
					isMulti: false,
					hideSelected: false,
					errorMsg: "Please select at least one tour type",
					label: 'name',
					key : 'id'
				},
```
any workaround please?

**Comment by chagamkamalakar** [comment]
sorry guys 

i made a mistake by passing invalid field for " key"  prop 

i changed that to obj.key

now it's working 

thank you

**Comment by shentao** [comment]
Glad to hear that!

**Comment by kamilwylegala** [comment]
For anyone that came here and is trying to figure out how to make the `key` prop work, the prop is now called `trackBy` :blush:
