### ISSUE TITLE
[LABEL] Problem with large text option after selected

### ISSUE THREAD

**Issue by danilosantosdev** [monterail/vue-multiselect#470]
I'm having a problem with the width of a large text option after selected. How can i fix it?

See in the image above to a better understanding.
![print-plane-class](https://user-images.githubusercontent.com/2335679/29212965-8941e340-7e77-11e7-9e16-b2388d0529f1.png)

**Comment by shentao** [comment]
Have you tried using a `:custom-label`?

You could then limit the length of the label like this:
```
customLabel (option) {
  return option.label.length > 50
    ? option.label.substr(0, 50) + '...'
    : option.label
}
```

**Comment by danilosantosdev** [comment]
@shentao I'll try and back to give a feedback. Thanks!

**Comment by danilosantosdev** [comment]
@shentao, i'm facing this problem.

![print](https://user-images.githubusercontent.com/2335679/29365301-e50bf7c6-826c-11e7-9ad6-2bde54718eb9.png)
