### ISSUE TITLE
Binding dropdowns to different v-model arrays

### ISSUE THREAD

**Issue by maryheng** [monterail/vue-multiselect#471]
Hi all,

**Background:**
Basically I have a Add Loan page where a user can select a **category** and **itemParents** will appear in a table `(v-for)` and each itemParent has a dropdown that shows the **itemChildren** of the itemParent. [image below for reference]
<img width="1136" alt="screen shot 2017-08-14 at 12 32 09 am" src="https://user-images.githubusercontent.com/13627091/29251476-097ebdd2-8088-11e7-9ceb-2f159d06709f.png">

**Problem:**
However, i have a problem when I select an itemChild from a specific itemParent, the itemChild appears in another dropdown **that does not belong to that particular dropdown** (not suppose to happen) **'FD-1'** is suppose to only appear in the **1st dropdown** only. However because the dropdowns are generated from a `v-for`, it has a` v-model `of the **same array**. So I'm not sure how to go about putting the selected item in another array and displaying at the same time(?) [image below for reference]
(Image 1)
<img width="1066" alt="screen shot 2017-08-14 at 12 31 08 am" src="https://user-images.githubusercontent.com/13627091/29251472-ec7d070c-8087-11e7-97f6-d0d106b56a19.png">
(Image 2)
<img width="1058" alt="screen shot 2017-08-14 at 12 31 12 am" src="https://user-images.githubusercontent.com/13627091/29251473-eef480c8-8087-11e7-8ffc-eed672620bb0.png">

**What I want to achieve:**
Each dropdown should only show their own selected and display the selected items. The '3dison' dropdown should not show 'FD-1'.

Here is the code for the dropdown:
```
            <tr v-for="row in rows" :key="row">
              <td>{{ row.itemParent }}</td>
              <!-- {{ row.itemChild }} -->
              <td>
                <div id="multiselectDivItemChild">
                  <p class="control">
                    <multiselect
                    :multiple="true"
                    v-model="itemChildNames"
                    :hide-selected="true"
                    :options="optionsForItemChild"
                    :id="row"
                    @open="getIdOfMultiselect"
                    open-direction="bottom"
                    label="itemChildLabel"
                    track-by="itemChildLabel"
                    @select="selectedItemChildNamesMethod"
                    @remove="removeOption"
                    >
                    </multiselect>
                  </p>
                </div>
              </td>
            </tr>
```

This jsfiddle isn't as similar as the program mentioned above but this is the skeleton only.https://jsfiddle.net/maryheng/5xrrzxv4/2/

How should I go about generating their own **v-model arrays** so they only show their own itemChildren in the dropdown and not show in other dropdowns too?

Please do ask for clarification if i'm not clear enough >.<

Appreciate your help! Still learning to get the hang of vue! Thank you!

**Comment by shentao** [comment]
Hey! There’s one small change needed:
`v-model="itemChildNames"` -> `v-model="row.itemChildNames"`.

Here’s a forked JSFiddle: https://jsfiddle.net/dwfux7rj/

**Comment by maryheng** [comment]
@shentao  Hi! Thank you for your help! Didn't know I could do it that way, newbie at vuejs... but thank you for your help 👍
