### ISSUE TITLE
When scrolling with mouse, the body scrolls when top or bottom of the dropdown scroll is reached.

### ISSUE THREAD

**Issue by yk1711** [monterail/vue-multiselect#472]
![h8eet3txa2](https://user-images.githubusercontent.com/3091884/29264962-cc98ed10-80e7-11e7-9324-9aae728d3a75.gif)

Is there an easy way to "lock" the scroll context inside the multiselect until it's closed ? The way it works on native select. Also seems to work on the popular select2 plugin. I guess that would involve adding a listener on document body to prevent scroll when dropdown is opened.

**Comment by shentao** [comment]
The current behaviour is the preferred one – I don’t want vue-multiselect to interfere with global elements like `<body>`. However, you coul implement such solution yourself. What you need to do is add a function to both `@open` and `@close` events that add and remove `overflow: hidden` to the `<body>` tag.

**Comment by yk1711** [comment]
Thanks for your points of view! `overflow: hidden` would remove the scrollbar on body until multiselect is closed. The native behavior is much more complex, as scrollbar is still visible and works when you mouseout of the select area. So it's more complex than that to really mimic the native way.
