### ISSUE TITLE
How to prevent space as a new tag

### ISSUE THREAD

**Issue by shifangwang** [monterail/vue-multiselect#473]
https://jsfiddle.net/gmsa/04jvjuv3/
![image](https://user-images.githubusercontent.com/16423041/29301879-ea7fc5e0-81b1-11e7-9434-a79263eab7e2.png)

" Press enter to select " appear when press space.
Thanks.

**Comment by shentao** [comment]
Fixed :) Should be live with the 2.0.4 release.
