### ISSUE TITLE
Left padding for options

### ISSUE THREAD

**Issue by kissmygritts** [monterail/vue-multiselect#474]
I've been unable to reproduce this issue, or figure out how to solve it. Maybe some one else has dealt with it.

The options for the select appear to have a left padding or margin. 

![vue-multiselect](https://user-images.githubusercontent.com/8335176/29336133-c1c20838-81c1-11e7-9324-5c6080555eb7.png)

**Comment by shentao** [comment]
This might be because of some global nested styles that modify the default behaviour of `li` or `ul` elements.
