### ISSUE TITLE
Error in "getting started" guide

### ISSUE THREAD

**Issue by Herteby** [monterail/vue-multiselect#475]
http://monterail.github.io/vue-multiselect/#sub-getting-started

```javascript
import Multiselect from 'vue-multiselect'

// register globally
Vue.component(Multiselect)
```
Does not work. It should be:
```javascript
Vue.component('multiselect', Multiselect)
```

**Comment by pokonski** [comment]
Yep, the docs need an update. Got caught by this as well. Not providing the tag name just treats the `<multiselect>` as regular HTML tag and shows nothing (obviously).

**Comment by Herteby** [comment]
I created an issue instead of PR because I wasn't sure which file to edit, but I figured it out now.
PR here: https://github.com/monterail/vue-multiselect/pull/509

**Comment by shentao** [comment]
Oh sorry. I Hardly ever use that notation. Thanks a lot for the PR! :)
