### ISSUE TITLE
Vue-Multiselect is not being displayed inside responsive components

### ISSUE THREAD

**Issue by TinnSoft** [monterail/vue-multiselect#477]
I am trying to use multiselect inside a datatable component which is full responsive, however vue-multiselect is not being displayed in the correct way.
Is there a way to fix it?

How it is being displayed:
![image](https://user-images.githubusercontent.com/20357756/29369900-8adcaa3c-8269-11e7-96db-8416e4734907.png)

How it should looks like:
![image](https://user-images.githubusercontent.com/20357756/29369998-c9dd167c-8269-11e7-94cb-eecbd2cb46b6.png)

**Comment by shentao** [comment]
You can always modify the default styles to change the behaviour within the table. Please see the `src/Multiselect.vue` file for source CSS and classes.

**Comment by cotein** [comment]
Lo solucionaste?
Cómo pudiste?
Estoy en la misma y no sé como hacer.
