### ISSUE TITLE
Using a custom dropdown icon

### ISSUE THREAD

**Issue by jackbarham** [monterail/vue-multiselect#478]
No so much a bug, but I would like to use my own custom icon (drop-down arrow) but can't where to add in my HTML for it?

**Comment by arenddeboer** [comment]
It looks like this is now possible with the latest (github) version using the caret slot
```
          <template slot="caret">
            <div>
              <div @mousedown.prevent.stop="toggle()" class="multiselect__select">
                <icon name="plus" style="color:green;"></icon>
              </div>

            </div>
          </template>
```
Whatever you put in the slot template will be set as the caret, in my case a vue-awesome icon.
In this case I have a local toggle method which calls the multiselect toggle method using a ref 
You will also have to override some css or include your own.

Another option is using only css by for instance adding a background url to an image and removing the current caret by overriding some styles.

**Comment by jackbarham** [comment]
Thanks for the suggestion, but I can't get it to work. I'm using version 2.0.2 and this is my code:

```vue
<multiselect v-model="country" :options="countries" placeholder="Select or type to search" label="label">
	<template slot="caret">
		<i class="icon-down"></i>
	</template>
</multiselect>
```

**Comment by arenddeboer** [comment]
It will not work on the latest npm version. I had to clone this git and run the build script (not sure if the build was necessary) Grep the dist js file for "caret" to see if you have it.

**Comment by jackbarham** [comment]
Thanks, I'll wait until they release a stable version. Thanks for the heads-up though. Looks like it's on it's way.

**Comment by shentao** [comment]
Weird. Could you please provide a reproduction on jsfiddle?

**Comment by jackbarham** [comment]
I have added this Fiddle: https://jsfiddle.net/jackbarham/5zh4ob3a

For now, I've used `<span>test</span>` in the slot to see if something else appears, but it doesn't.

**Comment by jackbarham** [comment]
Did you have a chance to look at the fiddle @shentao?

**Comment by chen8ih** [comment]
@jackbarham, I think slot name is "carret", not caret

**Comment by shentao** [comment]
Eh, just noticed that the change wasn’t released yet (and there was a change in the name). Will push a fix today. Sorry :/

**Comment by jackbarham** [comment]
Thanks, @shentao - I'll check this evening.

**Comment by shentao** [comment]
@jackbarham Vue Multiselect 2.0.3 was released.
https://jsfiddle.net/yghbards/ Forked your fiddle with the updated version.

Sorry everyone for the delay. Trying to get back to active maintenance...

**Comment by jackbarham** [comment]
Thank you. Works perfectly.
