### ISSUE TITLE
Emit input before remove

### ISSUE THREAD

**Issue by glutaminefree** [monterail/vue-multiselect#484]
Hi!

From _multiselectMixin.js:512_

```
this.$emit('remove', deepClone(option), this.id);
this.$emit('input', this.getValue(), this.id);
```

You should emit the _input_ first and only after the _remove_ event. Example https://jsfiddle.net/pqjww0me/21/
I expect, when _remove_ triggered, the _value_ (v-model) must already be updated, but it's not.

**Comment by shentao** [comment]
That’s correct. Will make the required adjustments hopefully this weekend. Thanks!
