### ISSUE TITLE
Dropdown bottom item cutoff when using arrow keys

### ISSUE THREAD

**Issue by jamesAtcodeninja** [monterail/vue-multiselect#488]
![dropdown](https://user-images.githubusercontent.com/26530591/29599165-761d4a2e-8800-11e7-8bdf-5790e20a94c9.gif)

This video is taken from the `Option groups` example on the [vue-multiselect](https://monterail.github.io/vue-multiselect/#sub-multiple-select) site, and the same issue appeared in my project. Pressing the down arrow-key does not show the lowest item in the viewport. 

For example, `max-height="200"` shows 5 list-items but the down key highlights the 6th-item which is not visible in the viewport.

**Comment by shentao** [comment]
Seems related to #486. Will look into it. Thanks!

**Comment by przemyslawDev** [comment]
Hi, I still have this problem on version 2.0.3

**Comment by shentao** [comment]
Can’t reproduce. If your options are higher than the default please remember to use `:option-height` prop.

**Comment by przemyslawDev** [comment]
Sorry I forgot to write. The problem was that in the project the style file to the package was not updated ...
