### ISSUE TITLE
 search query is deleted after click on the page

### ISSUE THREAD

**Issue by marjandejyab** [monterail/vue-multiselect#493]
When searching, if I don't select an option and click on the page, the search query is deleted. how can I fix it?

**Comment by shentao** [comment]
Hey! There is a prop for that: `preserveSearch`. Set it to true and the search query won’t be cleared when opening the dropdown. 
Example http://monterail.github.io/vue-multiselect/#sub-multiple-select

**Comment by jaketoolson** [comment]
@shentao this is happening to me, I wonder if the documentation needs to be updated?

```clear-on-select="false"```

**Comment by wiemann** [comment]
+1

**Comment by shentao** [comment]
@jaketoolson @wiemann that is the correct behaviour. If you close the field, why keep the search query visible? `preserve-search` does just that – remembers the last search query so you can get back it in case someone closed the dropdown by accident.

**Comment by wiemann** [comment]
@shentao Created required behaviour it by using :taggable parameter and adding a @tag method in order to create new tag based on search. @marjandejyab that might solve your problem too
