### ISSUE TITLE
Display selected items in different html element

### ISSUE THREAD

**Issue by jaketoolson** [monterail/vue-multiselect#499]
Curious if its possible to make it so that when items are selected, they are can be populated elsewhere other than inside the search area input?

![14-add-tags-webform-app](https://user-images.githubusercontent.com/612332/30140722-57f56032-932b-11e7-8fef-c37401717729.png)

**Comment by shentao** [comment]
It’s possible.

Use CSS to hide the tags inside the Multiselect. That should be `.multiselect__tags` if I remember correctly. Then, use the `value` to display the selected elements somewhere else.
You will need to implement your own removing methods though.
