### ISSUE TITLE
how to add class into vue-multiselect

### ISSUE THREAD

**Issue by vazh** [monterail/vue-multiselect#500]
sorry if my title didn't seem to explain enough,
let's say i want to validate the form using other library,
any idea how to add the class?
since i use vee-validate it usually goes like this
```html
:class="{'is-danger': errors.has('ca')}"
```
& 1 more thing, i know its silly, but how do i add the highlight to the input when focused?

**Comment by assembledadam** [comment]
Adding a custom class to the input element isn't supported by this component, which I think is madness. At the moment you are forced to customise/override the default CSS.

This is really frustrating for me as I have a bunch of existing form styles that I want applied to this, and I'm going to need to duplicate them all.

@shentao how come this isn't in there? Seems like it would be fairly straight forward to add a "class" prop.

**Comment by shentao** [comment]
Why would you want to add a custom class to the `<input>` element? You know that the input is just a very small fragment of the component. It’s actually borderless and sometimes there’s no `<input>` at all. It would be useless.
If you add `:class="{'is-danger': errors.has('ca')}"` to the `<multiselect>` it will add that class to the root element of the component. You can then add the needed styles to change the border or whatever you wish to do with it.

Here’s an example: https://jsfiddle.net/shentao/qj7xovms/

**Comment by atrujillofalcon** [comment]
Why this is closed?

**Comment by shentao** [comment]
@atrujillofalcon because it was answered above and I don’t consider this an actual issue.

**Comment by rickyanwar** [comment]
in specific template we need binding class in input element 
![image](https://user-images.githubusercontent.com/36995966/82943589-77c89400-9fcc-11ea-9a21-b68c01b2b9fe.png)

**Comment by qmarcos** [comment]
Using the binding option you always can do something like this:

```html
<multiselect
:class="{'myclass': true, 'myotherclass': true}"
 v-model="mymodel"
></multiselect>
```

The problem I have found is that those classes are applied to the root `div` of the component HTML, which have set a `z-index` value of `-1` so for some specific styling (validation background images for example) is not too useful.

**Comment by rizkhal** [comment]
you can override multiselect class like this

```
.multiselect__placeholder {
  display: inline-block !important;
  margin-bottom: 0px !important;
  padding-top: 0px !important;
}

.multiselect.invalid .multiselect__tags {
  border: 1px solid #f86c6b !important;
}
```

don't forget to remove scoped tag :)

![Screenshot from 2020-12-03 00-24-49](https://user-images.githubusercontent.com/24653114/100892810-af714500-34f5-11eb-9405-841b334f3712.png)
