### ISSUE TITLE
why can't we set the input as required

### ISSUE THREAD

**Issue by cargie** [monterail/vue-multiselect#505]

**Comment by shentao** [comment]
Because sadly it doesn’t work as a regular HTML5 input. You need at least a computed property that will check if the multiselect isn’t empty.

**Comment by TheAndroidGuy** [comment]
@shentao when i add the `required` attribute to the input field in the html via chrome it works perfectly.

Can you somehow make it possible to add that attribute to the input field?

[Here is screenshot](https://prnt.sc/ieq2yx).
