### ISSUE TITLE
Single select with max prop

### ISSUE THREAD

**Issue by kinaps** [monterail/vue-multiselect#510]
# Bug description
Select options are NOT visible in single select if you'll setup max value to 1. If you'll setup max value to '0' everything works but validation. 

## Props: 
1. :multiple="false" 
2. :max="1"

Also you cannot setup max value to "false" (default value). 
`Invalid prop: type check failed for prop "max". Expected Number, got Boolean.`

## My use case:
```
<multiselect 
       v-model="defaults[key]" 
       :options="fieldConfig.options" 
       :multiple="fieldConfig.max > 1" 
       :max="fieldConfig.max" 
       :name="key" 
       track-by="id" 
       label="name"
>
</multiselect>

```
### Feedback
This multiselect is the best I ever used. Really great job 👍 . Thank you.

**Comment by shentao** [comment]
Hey! Thanks for the kind words. :) Trying to get back to active maintenance.

Changed the default `max` value to `0`.
Added a warning when using `multiple: false` and `max > 0` as this doesn’t really make any sense. In single select you can only have 1 element max anyway.
