### ISSUE TITLE
Feature: OnSelectedPlaceholder

### ISSUE THREAD

**Issue by Fohlen** [monterail/vue-multiselect#512]
Currently still using `2.0.0-beta15` but I haven't seen it anywhere in the docs anyways.

It would be nice to have an option to change the placeholder text after one element is selected (in a multiple-select).
Sometimes the default placeholder is "all ..", and should change to "all selected .."

**Comment by shentao** [comment]
Not sure if this is what you mean but look at this: https://jsfiddle.net/shentao/7wtn1972/
You can adjust the placeholder dynamically.

**Comment by Fohlen** [comment]
Perfect, it's exactly what I asked for. I have been suspecting that it is possible to do it with the `customPlaceholder` option. Probably one of the two options is appropriate

- maybe this is mandatory enough to add a separate option
- add more enhanced documentation about `customPlaceholder` (this example could serve well)

**Comment by shentao** [comment]
Actually, this is just passing a dynamic value to the `placeholder` property. I just named the dynamic value `customPlaceholder`. I think this is already documented in the props section. You can also modify other parts of the component this way.
See https://monterail.github.io/vue-multiselect/#sub-props
