### ISSUE TITLE
Bootstrap 3 and 4 compatibility

### ISSUE THREAD

**Issue by michaelsogos** [monterail/vue-multiselect#513]
Dear @shentao ,

Is this library compatible with bootstrap css?

**Comment by shentao** [comment]
Sadly it’s not (Multiselect internal styling are quite complex).
However, you can choose not to import the default CSS file and use bootstrap-like styles to style it yourself.

**Comment by michaelsogos** [comment]
Do you have rules or LESS or SCSS file as a starting point?

**Comment by shentao** [comment]
https://github.com/monterail/vue-multiselect/blob/2.0/src/Multiselect.vue

Here is the code structure along with the CSS. I hope this helps!

I used sass and pug before, but someone had a problem with it like year ago so I had to move to vanilla css/html. :(

**Comment by jbnv** [comment]
I guess this means I won't be using Vue-Multiselect in my Bootstrap Vue project. Quite a shame.

**Comment by shentao** [comment]
I'm perfectly cool with that. 🙂
