### ISSUE TITLE
Updating options does not update label when closed

### ISSUE THREAD

**Issue by thatsmydoing** [monterail/vue-multiselect#514]
I'm trying to make the entries in the options list editable. It works for the actual programmatic value and when the options list is open, but when it's closed, the currently selected option's label is still the original one.

https://jsfiddle.net/vjLspwvc/1/

Clicking on the Test button updates the actual value, and the label when the list is open, but not the one displayed on the closed list.

**Comment by thatsmydoing** [comment]
Ah, it seems that it's necessary to create the object instead of just reusing the same one from the options list. I assumed it would automatically watch for deep edits, but I guess not.

https://jsfiddle.net/vjLspwvc/2/

**Comment by shentao** [comment]
This is not related to the component but Vue itself. Please read the Array Change Detection Caveats: https://vuejs.org/v2/guide/list.html#Caveats

You need to write something like 
`Vue.set(this.options, 1, { newObj})`

**Comment by thatsmydoing** [comment]
No, it's not that particular issue. Even if it's outside of the array, and even if I use the vue helper method to set the attribute, it doesn't update at all.

https://jsfiddle.net/vjLspwvc/3/

All that really matters is that you pass a different object as value so that the component will notice the update.
