### ISSUE TITLE
Using with normal from inputs

### ISSUE THREAD

**Issue by dobromir-hristov** [monterail/vue-multiselect#52]
If I wanted to sync up the multiselect with a normal input field, lets say an input:hidden, it all works well if I use primitive values for the multiselect. If I use an array of objects on the other hand,  like 
```js
[ { value: 1, label: 104 },
   {value: 2, label: 105}]
```
it writes the whole selected object to the synced up property, but that cant be sent over as a normal form submit data if I`m not mistaking. If I use something like v-model="synced.value" on the aforementioned hidden input, It will get only the value, but then If I try to pass it back to multiselect (after a page refresh for example) it wont work as multiselect needs the whole object it passed as current in the first place, correct?

Should I do some toString parsing or there is a better way.

**Comment by shentao** [comment]
As far as I know, regular inputs accept only primitives as value. 
Right now multiselect doesn’t support recognizing whole objects based on the `key/id` (even if it uses it internally to match and compare objects).

I’m not sure what you mean by *normal form submit data*. If you use regular XHR requests (or with a wrapper library like `vue-resource` or `axios`) you can send a JSON object. The same goes with [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects).

**Comment by dobromir-hristov** [comment]
No I had to do a normal form.submit() on the form. Complicated to explain but to work around this i had two inputs. For the value and for the Label. If I used multiple prop I just separated the values with a comma and all worked.

**Comment by shentao** [comment]
Could you provide a snippet of the submit code? Is this some kind of remote service where you send the form?

**Comment by dobromir-hristov** [comment]
I will try to give a better explanation later.

**Comment by shentao** [comment]
In the other issue you asked for an `on-close` event. If you need something similar to it, you can pass a callback function to `:on-change` prop. This method would need to accept the `selected` new value. Additionally you would have to remove the `.sync` modifier. 

You can look into the documentation at the Vuex section.

Hope this helps.
