### ISSUE TITLE
Multiselect recursion

### ISSUE THREAD

**Issue by Sharvadze** [monterail/vue-multiselect#523]
Hi, I'm trying to build an option tree using component recursion, but couldn't figure out how to avoid the duplication of multiselect tag itself

Here is my code, any guidance is greatly appreciated

`<template>
<multiselect placeholder='' select-label='' v-model="pvalue" :options="model" label="name">
            <template slot="option" scope="props">
                <div class="option__desc"><span class="option__title">{{ props.option.param + ' - ' + props.option.name }}</span>
                    <category-dropdown-tree v-if="props.option.children" :model="props.option.children"></category-dropdown-tree>
                </div>
            </template>
        </multiselect>
</template>`

**Comment by shentao** [comment]
I don’t think Multiselect is the right choice here. You would probably be better with a custom implementation of a tree-view.

Feel free to fork / copy the code of the Multiselect component if you need parts of it.

Otherwise I can’t really help you, sorry. :(
