### ISSUE TITLE
Event when removing a tag from a taggable select

### ISSUE THREAD

**Issue by abishekrsrikaanth** [monterail/vue-multiselect#524]
The `taggable` prop allows defining the `@tag` that is triggered when adding a tag. 
I perform an action on the `addTag` method configured on `@tag`.

If I wanted to do the same when removing a taggable item, how can I do that?

**Comment by shentao** [comment]
Once a tag is added it is treated as a regular option. There are no special events for tags apart from `@tag` for adding. 
You can use the `@remove` event to handle removing. If the tags you add using your `addTag` include a flag like `isTag`, you can use that to identify user-created tags from other options.

I hope this helps! :)
