### ISSUE TITLE
Bug when searching

### ISSUE THREAD

**Issue by Defender32** [monterail/vue-multiselect#533]
When searching to be displayed above the text "undefined"

**Comment by shentao** [comment]
Please provide a reproduction link (you can use: https://jsfiddle.net/shentao/jqofkzxc/)

**Comment by Defender32** [comment]
http://prntscr.com/gwzl0u

**Comment by shentao** [comment]
Thanks! Wasn’t completely aware of that.
I wonder why it doesn’t happen on the docs pages though. Gonna investigate it this weekend.

**Comment by shentao** [comment]
Weird. Somehow I can’t reproduce it now. Could you please provide a fiddle with it? As well as browser version used.

**Comment by Defender32** [comment]
Now, there is no problem.

**Comment by langemike** [comment]
Took me 2 hours to discover! It's a problem regarding Vue 2.5.0

The error can be seen over here where i changed loading the latest Vue version to 2.5.0
https://jsfiddle.net/xgs90k9j/3/

First you need to type in something. Then "undefined" appears.

It doesn't seem to be a problem regarding Multiselect. But something to do with Vue itself.

**Comment by ayaz323** [comment]
i have same problem

**Comment by langemike** [comment]
@ayaz323 if you're using Vue 2.5.0, please upgrade it to a newer version to solve the problem.
