### ISSUE TITLE
Select the only option on blur

### ISSUE THREAD

**Issue by dtkahl** [monterail/vue-multiselect#536]
Hi. I use the multiselect to let the user enter a year number. (short example: https://jsfiddle.net/53joaarp/1/)

The problem is, if the user enters a valid option like "2012" in search input and than goes on to the next field (blur the multiselect) without explicit clicking on the option in the dropdown list, the multiselect value will stay empty.

I think this could be unexpected for the user because he entered a valid option and wants to go on with entering data without clicking the option and maybe he do not understand the issue why the field stays empty.

Is there any way jet to select the only option, if the user entered an exact and valid option in the input?  If not, is this a feature you would consider to add to the multiselect as additional option?

**Comment by shentao** [comment]
This is indeed quite tricky. I could imagine it could be solved like this:
You will have to extend the component and add a listener inside the `created` hook.

```
created () {
  this.$on('close', () => {
    if (this.options.length) this.select(this.options[0])
  }
}
```
