### ISSUE TITLE
Feature: custom placeholder

### ISSUE THREAD

**Issue by Fohlen** [monterail/vue-multiselect#537]
As a developer I would like to have a custom placeholder.
This is useful in situations where you implement the following logic

- selecting no element means selecting all available elements
- selecting a single element => selected elements

If you do this in a dependant-scenario (let's say the city you pick depends on the country), it can appear that no previous selection will mean no available selection.

A custom placeholder like

```
customPlaceholder() => {
  return (logic.allOptions) ? `all cities for ${logic.country}` : 'no cities'
}
```

Would come in handy to solve this issue.

**Comment by shentao** [comment]
You can pass a dynamic placeholder. All the data is already available outside of VueMultiselect internals so a computed property or function call should be enough.

Example:

```
// template
<VueMultiselect v-model="value" :options="allOptions" :placeholder="customPlaceholder"/>

// computed in script
computed: {
  customPlaceholder () {
    return this.allOptions ? `all cities for ${this.country}` : 'no cities'
  }
}
```

I hope it helps.
Cheers1

**Comment by falstack** [comment]
it not work

**Comment by Venegrad** [comment]
How to allow html markup in palceholder? if i need insert span with color?
