### ISSUE TITLE
Selecting items when using Custom Option Template

### ISSUE THREAD

**Issue by abishekrsrikaanth** [monterail/vue-multiselect#538]
I am using the Custom option template to allow multiple option selections on my dropdown. Every selection stores the entire object and not the value that is configured using the `track-by` option. To pre-select values on page load, is binding all the objects the way to go or is there an alternative?

**Comment by shentao** [comment]
Sadly you have to preselect the whole objects at the moment. This is due the fact that we support async search where some elements might not be present in the options list. Showing them just based on the `track-by` values would not be possible (labels, custom labels and stuff).
So far `track-by` is only used for comparing.
