### ISSUE TITLE
Reset a value when @remove

### ISSUE THREAD

**Issue by Konafets** [monterail/vue-multiselect#539]
Hi, I like to reset the model to its origin state when the @remove event is fired.

Please have a look at https://jsfiddle.net/konafets/Ldjhonfj/3/

## What do I expect?

`items.*.value` should set to `{id: null, title: ''}`

## What happened?

`items.*.value` is `null`

**Comment by shentao** [comment]
The current behaviour is the desired one. `{ id: null, title: '' }` is actually an object just with no id and empty string title. Not having a value means it has to be either an empty array (for multiple selects) or `null`.
If you need, you can modify the `items.*.value` inside your `@remove` handler.

**Comment by Konafets** [comment]
I was not intending to change the current behavior. I am aware of the fact that my question only makes sense in my case.

> If you need, you can modify the items.*.value inside your @remove handler.

That it was I tried and didn't work as demonstrated in the linked fiddle.

**Comment by shentao** [comment]
Sorry, must have misunderstood you.

Please use `Vue.set`. That should solve the problem.
Explaination: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by Konafets** [comment]
Ah, I see. Thanks you!

**Comment by shentao** [comment]
Sure! Happy to help :)
