### ISSUE TITLE
change overflow inside multiselect

### ISSUE THREAD

**Issue by filipenco92** [monterail/vue-multiselect#540]
hello, i want to change default overflow! i use the plugin https://bosnaufal.github.io/vue2-scrollbar/ , how can i make this? need to add: 
< vue-scrollbar classes="my-scrollbar" ref="scroll" >
     < div class="scroll-me" >
            // options of the multiselect (dropdown items)
     </ div >
</ vue-scrollbar >

sorry for my bad english :)

**Comment by shentao** [comment]
Hey! I believe this is not currently possible. Also, why do you want to use the custom scrollbar? For example, the horizontal scrolling is broken on a trackpad on a mac.
What is it that you need to accomplish with a custom scrollbar? Maybe it can be done without it?

**Comment by filipenco92** [comment]
thank your for answear! very bad... i hope the new release will be soon...  i use in the project this scroll plugin, is the customer desire :)

**Comment by shentao** [comment]
I believe you can extend the current component and provide your custom *options list* template along with some adjustments to make it work with vue2-scrollbar.
