### ISSUE TITLE
[Question] Change result ordering?

### ISSUE THREAD

**Issue by OwenMelbz** [monterail/vue-multiselect#542]
Hi,

Is it possible to change the result ordering?

e.g Currently its alphabetically so if you had typed in "bo" you get the following

![which_parts_do_you_require_____1st_choice_spares](https://user-images.githubusercontent.com/1094740/31777300-a61a0b06-b4e5-11e7-8698-d551c5f50dd9.jpg)

However is it possible to change this? to return by relevancy?

e.g If you search "bo" it would show all of the results that start with "bo" rather than alphabetically?

Does this make sense - sorry hard to explain.

Thanks

**Comment by shentao** [comment]
Hey! I believe this should be possible if you disable the `internalSearch` prop and filter the results yourself using the `@search` event. If the `options` array is sorted by relevance, this is how it will show inside the multiselect.
Please see the async search in the docs for an example of external search.

**Comment by zhuwei** [comment]
> Hey! I believe this should be possible if you disable the `internalSearch` prop and filter the results yourself using the `@search` event. If the `options` array is sorted by relevance, this is how it will show inside the multiselect. Please see the async search in the docs for an example.
Sorting rules have no association with 'internalSearch'
