### ISSUE TITLE
QUESTION: How can i refresh custom labels when options change?

### ISSUE THREAD

**Issue by acacha** [monterail/vue-multiselect#544]
It's possible to refresh labels (in my case custom labels) when i change programatically the options associated to multiselect? Are labels reactive to changes?

Or maybe is there any way to change the current selected label if I change programatically the current selected value?

Thanks

**Comment by shentao** [comment]
A custom label is reactive if it uses data from the data model. It should work with `this.options` too. See example: https://jsfiddle.net/shentao/Lq39gx8n/

I hope this helps! :)
