### ISSUE TITLE
Search by group name in group options.

### ISSUE THREAD

**Issue by DeepakAryal** [monterail/vue-multiselect#545]
I have a lots of groups and data in a table. i want to search by group name as well as by data. is it possible to do that?

**Comment by shentao** [comment]
You will have to implement your own search and disable the `internalSearch`. See example: https://monterail.github.io/vue-multiselect/#sub-asynchronous-select

**Comment by pandalion** [comment]
Hi, @shentao - the example link is broken for me, please do you have a working link or a little advice on how to get started on searching by group name? Thank you

**Comment by mrleblanc101** [comment]
Why did you close ? It would be a nice enhancement to have this natively
