### ISSUE TITLE
QUESTION: Using Vuex for storing asynchronous options will not trigger the options dropdown unless I set 'internalSearch: false'

### ISSUE THREAD

**Issue by Mark-de-Haan** [monterail/vue-multiselect#547]
I did not add a fiddle due to actions + asynch stuff, but to explain in short:

1) multiselect with
  @search-change="getOptions"
  :multiple="true"
  searchable="true" 
  track-by="code"
  label="label"

2) getOptions -> returns an Array of objects {id, label, code} and stores them in the state via a mutation

3) My component holding vue-multiselect uses a Vuex getter to retrieve the list of options

Issue:
In my component, I verified that the getter was working because I could console log the list of options. The vue-multiselect component also contained the options (verified using Vue console).

But the dropdown was not updated, telling me there were no options available.

I solved the issue using :internalSearch="false"

Is this a bug, or missing documentation?

#### EDIT 
I noticed a similar issue #344 and you closed that after suggesting internal-search: false
It took me a while to figure out I had to use this, should this be documented?

**Comment by shentao** [comment]
I believe this is documented in the *async* section: https://monterail.github.io/vue-multiselect/#sub-asynchronous-select

And yes, the `:internalSearch="false"` is required if you have an outside search.

**Comment by Mark-de-Haan** [comment]
Ahhh ok, I always use your README.md to check for available options, no wonder I never found it haha.

Thx for the reply!
