### ISSUE TITLE
On webpage, replace 2.0.0 with 2.0.3 - it's very important

### ISSUE THREAD

**Issue by akarelas-pt** [monterail/vue-multiselect#549]
I included <script ...></script> and <link rel="stylesheet"...> tags to import this library in my non-SPA script. While the versions I was including were 2.0.0, as the webpage says I should write, the appearance was broken (on a Buefy site). When I replaced 2.0.0 with 2.0.3 everything got fixed.

**Comment by shentao** [comment]
True. Thanks for pointing this out! :)
