### ISSUE TITLE
On-change doesn't work on last item

### ISSUE THREAD

**Issue by DevKingDigital** [monterail/vue-multiselect#55]
When using the on-change attribute, the method doesn't get fired if you remove the last item in the selection.

**Comment by shentao** [comment]
Make sure you don’t have the `.sync` modifier at the `selected` attribute.

**Comment by DevKingDigital** [comment]
Doens't seem to make a difference. Here is my markup

```
<multiselect :options="roles" :selected="selectedRoles"
                                    placeholder="Please Select" :multiple="true" :hide-selected="true"
                                    label="Roles" key="id" :on-change="selectPermissions"></multiselect>
```

**Comment by shentao** [comment]
When using the `on-change` attribute you have to explicit mutate the object. In your case it would be something like this:
```
 selectPermissions: function (roles) {
            this.selectedRoles = roles;
            roles.forEach(function (value, key) {
                this.$set('selectedPermissions', value.permissions);
            }.bind(this));
        }
```

**Comment by DevKingDigital** [comment]
Still doesn't appear to resolve the issue. I mutated the object and added a `console.log` so that I could check when the method was being hit. It hits the method if there is more than one and I remove one, but if there is only one option selected and I remove that option - It doens't hit the method as nothing gets logged in the console. Also when checking Vue devtools, the `selectedRoles` data property on my Vue instance doesn't reset to an empty array once the last one has been de-selected

**Comment by shentao** [comment]
Looking into it now.

**Comment by shentao** [comment]
Btw. why do you use `.bind(this)` in this forEach function? Aren’t you overriding the `this.selectedPermissions` for each of selected roles? Or is this a computed setter?
Why not something like
```
for (var role of roles) {
  this.$set('selectedPermissions', role.permissions)
}```

or to collect all the permission per selected roles
```
this.$set('selectedPermissions', roles.map((role) => role.permissions))
```


Even with exact the same multiselect props configuration I can not reproduce the problem. Could you provide some more

**Comment by shentao** [comment]
@DevKingDigital Hey, why did you close the issue? Does it work now? Where was the problem
