### ISSUE TITLE
Laravel id in value and name in label

### ISSUE THREAD

**Issue by majweb** [monterail/vue-multiselect#550]
Hello 
I used axios to catch elements from laravel api.
I need put ID of the element in value and Title in label. 

`<multiselect v-model="newitem" :options="trainers" label="title" placeholder="Wpisz nowego trenera"></multiselect>`

I want send POST request to laravel api and i need ID of the element in newitem.

**Comment by shentao** [comment]
```
<multiselect v-model="newitem" :options="trainers" track-by="id" label="title" placeholder="Wpisz nowego trenera"></multiselect>
```

When sending a post request you should be using `this.newItem.id`.

Anyway, I don’t see where this is related to Multiselect at all. Closing
