### ISSUE TITLE
Support slot-scope in Vue 2.5

### ISSUE THREAD

**Issue by ianfieldarsclinica** [monterail/vue-multiselect#551]
New warning in Vue 2.5:

'the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.'

Repro: https://jsfiddle.net/grw9tv4w/

**Comment by shentao** [comment]
It is supported. The change is required only on the user side, not in the library code. I will make the adjustments in the docs tho.
Thanks!

**Comment by ianfieldarsclinica** [comment]
Was the documentation updated?  I'm still not seeing how to use it.  What value goes in the slot-scope attribute?

Thanks!

**Comment by shentao** [comment]
Yes the docs have been updated. But I just noticed that there are some places in the content where I haven’t changed it.
However, the code examples are fine, see:
https://monterail.github.io/vue-multiselect/#sub-multiple-select

You use it the same way as you would use `scope`. Here’s how: https://vuejs.org/v2/guide/components.html#Scoped-Slots

**Comment by ianfieldarsclinica** [comment]
Got it!  Thanks for the clarification.
