### ISSUE TITLE
How do i populate the dropdown after the user has entered something and press enter

### ISSUE THREAD

**Issue by gj1118** [monterail/vue-multiselect#56]
Hi, 
I am trying to implement the case where the component acts as a traditional search box. Once when the user has entered something and pressed the enter button , I would like to use the user's input criteria as the search parameter and pass it to the API. The API would then return me all the values based on the user's search criteria. Now, the API is ready, but I am not sure how to use vue-multiselect to perform that kind of operation. Can you please help me out with this ? 

I keep getting this error : "No Elements Found. Consider changing your search query"

```Javascript
	
		<multiselect 
			:selected.sync="selected" 
			:options="booksArray" 
			:on-search-change="getBooks"
			placeholder="Type to search" 
			label="BookCode" 
			key="BookID">
		</multiselect>

<script>
	import Multiselect from 'vue-multiselect'
	export default {
		data () {
			return {
				booksArray:[],
				selected:null, 
			}
		},
		created () {
			console.log('going to create the object');
		},
		methods : {
			getBooks (item) {
				console.log('search item : '+item);
				this.$http.get('bookApiService').then(response => {
					this.booksArray = response.data.resource;
					console.log(this.booksArray.length);
					console.log(JSON.stringify(this.booksArray));
				})
			} 
		}, 
		components: {Multiselect}
	}
</script>




```

Thank you for your time and patience. 

With Regards
Gagan

**Comment by asvae** [comment]
@gj1118 

You probably want typeahead and not multiselect.

But I did something similar [here](https://gist.github.com/asvae/0cac596565396356ad5e42736a20ba35). Though, I won't advise this solution.

**Comment by shentao** [comment]
@gj1118 Hey there!
Is this API call correct? You’re not passing the `item` query into the `$http` request.

What does those console.logs print inside the `then` callback?

The above example should work except for the case when the returned books do not contain the search phrase in any of the keys. For example, you search for `Witcher` and the returned array looks like this:
```
[
  { BookCode: 'Sword of Destiny', BookID: 321 }, 
  { BookCode: 'Blood of Elves', BookID: 322 }
]
```

Multiselect does a search through all the keys available in the options array.

**Comment by gj1118** [comment]
Hi damian , the api call was just a sample one but i think for my purposes
i will have to use typeahead.

I only need to fill the options with the information that matches the
criteria has mentioned ..

Thanks
On Jul 8, 2016 3:13 PM, "Damian Dulisz" <notifications@github.com> wrote:
>
> @gj1118 Hey there!
> Is this API call correct? You’re not passing the item query into the
$http request.
>
> What does those console.logs print inside the then callback?
>
> The above example should work except for the case when the returned books
do not contain the search phrase in any of the keys. For example, you
search for Witcher and the returned array looks like this:
>
> [
>   { BookCode: 'Sword of Destiny', BookID: 321 },
>   { BookCode: 'Blood of Elves', BookID: 322 }
> ]
>
> Multiselect does a search through all the keys available in the options
array.

**Comment by shentao** [comment]
Okay :)

If you change your mind you can look into the documentation at the Asynchronous dropdown part.
