### ISSUE TITLE
Option to clear selection (empty option marked as active)

### ISSUE THREAD

**Issue by sourenaraya** [monterail/vue-multiselect#568]
Hello. I am trying to implement empty option, thats clears input\selection as suggested in #325  
Its kinda works, but when selected first time, its marked as active. 
Am i doing something wrong?

Fiddle below
https://jsfiddle.net/jfm7rj61/

**Comment by sourenaraya** [comment]
Okay. The problem was, null instead of [ ] (empti array).
But still, i dont think this is good, in case of :multiple="false".

Also, in fiddle its wont work even with [ ], i have no idea whats going on here...

**Comment by shentao** [comment]
Hey!

You have to use `nextTick` for that. Here’s a working example: https://jsfiddle.net/Lr1m4hrd/

**Comment by sourenaraya** [comment]
Well, it works with the `nextTick`, but still, label appears for a split second and _than_ disappears.
And this doesnt happen if using empty array instead of null.
Maybe will be better to add support for null as empty value?
