### ISSUE TITLE
Follow flow of document

### ISSUE THREAD

**Issue by jeppebemad** [monterail/vue-multiselect#571]
Is there a way to make the component follow the flow of the document when its height changes? Currently, if I select a long list of tags, the component will overflow the rest of the document as the height grows. 

I would like it to be part of the document flow, so that it pushes below items down when growing.

Thanks for a great project!

**Comment by shentao** [comment]
This should not happen – see docs. Might it be that your CSS is somehow changing the default behaviour? I see a possible problem if your tags consist of extremely long words, but that can be fixed with a single rule: `word-break: break-all;`.

Cheers

**Comment by jeppebemad** [comment]
Thank you for the response. It made me search a little deeper, and I did indeed find that a parent element had a max-height set. It's working now :)
