### ISSUE TITLE
Suggestion: Can integrate a checkbox in the option template

### ISSUE THREAD

**Issue by eossa** [monterail/vue-multiselect#574]
I cannot to check the input checkbox when I select an option.

https://jsfiddle.net/shentao/jqofkzxc/

Can you do something? 
Thanks!

**Comment by shentao** [comment]
Hey! 

It might be quite hard to do it properly. Hopefully this helps though: https://jsfiddle.net/3numjz68/

**Comment by eka4ecap** [comment]
that's good, but when I want to click dismiss (x) for the data selected checkbox is still checked
