### ISSUE TITLE
Getting [object, object] after selecting an option

### ISSUE THREAD

**Issue by launchriot** [monterail/vue-multiselect#582]
Trying to use a custom component as a template. This is what I have:

**Multiselect**
```
<multiselect v-model="value" :options="options3" field-label="Test Test Test" helptipBody="This is a helptip, letting you know what to do." required >
  <template slot="option" slot-scope="props">
    <dawn-select-options>
      <img slot="image" slot-scope="image" :src="props.option.img">
      <p slot="row1" slot-scope="row1">{{ props.option.title }} ({{ props.option.number }})</p>
      <p slot="row2" slot-scope="row2">{{ props.option.tags }}</p>
    </dawn-select-options>
  </template>
</multiselect>
```

**The custom template is this component:**

```
<div class="dawnSelect__content-table-wrapper">
      <div class="dawnSelect__content-table-body-wrapper">
          <div class="dawnSelect__content-table-row-wrapper">
              <div class="dawnSelect__content-table-image-wrapper">
                  <slot name="image"></slot>
              </div>
              <div class="dawnSelect__content-table-content-wrapper">
                  <slot name="row1"></slot>
                  <slot name="row2"></slot>
                  <slot name="row3"></slot>
                  <slot name="row4"></slot>
                  <slot name="row5"></slot>
                  <slot name="row6"></slot>
              </div>
          </div>
      </div>
  </div>
```

And while it renders correctly on load, if I select an option, the select option in the field is [object, object].

~Not only that, it renders every other instance of multiselect on the page to have [object, object] selected as well.~
**Update:** Every instance on the page was updating because they were all sharing a v-model (oops). But it seems that every template with slot="option" slot-scope="props" is returning [object,object]

**Comment by launchriot** [comment]
Seems like I was missing label and track-by. But it's strange because I am 99% sure it was working the past few days without those options.

**Comment by shentao** [comment]
Hey! There’s no `field-label` prop. Please use the `label` prop as well as `track-by` field for objects. 

As for the slots, I’m pretty sure you don’t need to pass the `slot-scope="image"` as you’re not using the `image` variable anywhere. 

Other than that, it should be working properly.

**Comment by launchriot** [comment]
Thanks! field-label is a prop I added that puts a field label on top of the field, unrelated to the objects. Just like helpTipBody is another one I added.
