### ISSUE TITLE
How to make theming only child elements in OptGroup?

### ISSUE THREAD

**Issue by Libero82** [monterail/vue-multiselect#585]
Hello!

If i use "Custom option template" + "Option groups", then group element template too.
How to make theming only child elements?

**Comment by FreekVR** [comment]
Hey,

I was just having the same issue, you can use a conditional to mimic the appearance of the original option template for a group.

`<template slot="option" slot-scope="props">
                <span v-if="props.option.$isLabel">{{ props.option.$groupLabel }}</span>
                <span :class="props.option.class" v-else>{{ props.option.name }}</span>
</template>`

**Comment by Libero82** [comment]
Thank you!

**Comment by Zakini** [comment]
Sorry to resurrect an old issue, but I can find any docs for what exactly `props.option` contains. I get that it's mostly whatever is passed via `options` but I had no idea things like `$isLabel` were added too.

**Comment by thatside-zaraffa** [comment]
@Zakini there is no docs - yesterday I spent half a day to find out the way to solve my problem and found this issue. We should make a PR though...

**Comment by shentao** [comment]
Please do! All improvements to the docs are very welcome. 🙂
