### ISSUE TITLE
Problemm with getOptionLabel

### ISSUE THREAD

**Issue by Big-Shark** [monterail/vue-multiselect#59]
Hi.

I have a small problem 
![rsz_1screenshot_from_2016-07-16_02-56-37](https://cloud.githubusercontent.com/assets/646054/16882268/82727386-4b01-11e6-8e62-e0871af5837b.png)

This is my template
```
<multiselect
:on-search-change="getUsers | debounce 200"
:selected.sync="newOwners"
:options="users"
:searchable="searchable"
:clear-on-select="false"
placeholder="Search users..."
label="label"
key="value"
class="form-control col-md-10">
</multiselect>
```

What am I doing wrong?

**Comment by shentao** [comment]
You can remove the `:searchable` prop, as by default it is true.
This looks like a single-select so you can also remove `:clear-on-select` as it might be not necessary.
What does the console throw? There must be something as the `getOptionLabel(option)` didn’t work.
How does the `users` Array look like? Looking at the props you passed it should look similar to this:
```
[
  { label: 'Jon Snow', value: 'some_unique_id' },
  { label: 'Tony Stark', value: 'some_other_unique_id' }
]
```

**Comment by Big-Shark** [comment]
@shentao Console log showing this error
```
[Vue warn]: Error when evaluating expression "filteredOptions.length === 0 && search.length": TypeError: scope.search is null (found in component: <multiselect>)
```

My search method
```
    getUsers(search) {
      this.$http.get(this.$get('urls.admin_find_user'), {
        params: { email: search }
      }).then(resp => {
        this.$set('users', resp.data.items);
      })
    },
```
and response
```
{"items":[{"label":"...","value":"..."},...]}
```

**Comment by shentao** [comment]
Fixed in 0.3.1 :)

**Comment by Big-Shark** [comment]
@shentao I updated your library and this error ("[Vue warn]: Error when evaluating expression "filteredOptions.length === 0 && search.length": TypeError: scope.search is null (found in component: <multiselect>) ") is fixed, but I see same result, label does not work.

I think I found a reason, I use changed delimiters
``
Vue.config.delimiters = ['${', '}'];
```
I am right, this is a reason?

**Comment by Big-Shark** [comment]
@shentao Yes, I am right, I changed my delimiters to standard, and all it works, thanks

**Comment by shentao** [comment]
I looked at the component’s template and this can be probably fixed. I will try to do it during the weekend. Thanks for bringing this up! :)
