### ISSUE TITLE
Focus after selecting element

### ISSUE THREAD

**Issue by msx2** [monterail/vue-multiselect#6]
After you select elements using keyboard you end up with the focus being transferred to the first element on the options list. The solution is okay if you used search option, or when you enable removing elements from the list after selection. But the same happens when you navigate through the list using arrows only (i.e. empty search field). 😉 

Also, the other issue is when you have mouse pointer on either of the elements on the list... and then you navigate using arrows on keyboard and hit enter. Your selection ends up on the position you initially hovered. 😕

**Comment by msx2** [comment]
Oh, and focus issues are also present in single select dropdowns.

**Comment by shentao** [comment]
@msx2 Thanks for reporting!

The part about keeping the focus/highlight of the recently added field when not removing those from the list and not searching sounds like a valid improvement!

However, I can not reproduce the second problem. Could you please provide more information? What browser / system are you running? Or a screencast if possible?
There is this glitch when you’re hovering over an option and later use arrows to scroll down the list. When the viewport scrolls down, the pointer jumps back to the mouse position. Is this what you mean?

**Comment by msx2** [comment]
@shentao All the issues I found are combined in this short video: https://youtu.be/U1QHr0jJwYU. Some of them (e.g. random changing focus position while navigating down the options list) are hard to reproduce and luckily happened during recording 😉
