### ISSUE TITLE
Custom Vue delimiters not obeyed

### ISSUE THREAD

**Issue by mattjneuber** [monterail/vue-multiselect#60]
In my app, I use [[ ]] as Vue delimiters instead of {{ }}. Upon trying to use vue-multiselect, the options displayed in the dropdown are all {{ getOptionLabel(option) }} since Vue isn't using the curly braces.

**Comment by shentao** [comment]
I'm currently working on a solution for this problem. It will come with a big release soon (see #57). Please be patient!

**Comment by shentao** [comment]
@mattjneuber Fixed in v1.0.0
