### ISSUE TITLE
Display bug with "press enter to select" and long label

### ISSUE THREAD

**Issue by jpmurray** [monterail/vue-multiselect#62]
Here's what it does...

<img width="560" alt="screen shot 2016-07-21 at 11 41 09" src="https://cloud.githubusercontent.com/assets/1550428/17029154/17c86064-4f38-11e6-92fb-d577c5a4c706.png">

**Comment by shentao** [comment]
You can remove the labels passing a prop `show-labels="false"`.
I’m also adding this to the list of planned improvements in 1.0 release. (WIP #57)
