### ISSUE TITLE
Browserify and/or Laravel Elixir issue

### ISSUE THREAD

**Issue by dmitov** [monterail/vue-multiselect#64]
Hello there,

I'm using the mentioned to process my js files and I get this error:

> Browserify Failed!: [BABEL] /data/www/node_modules/vue-multiselect/lib/vue-multiselect.js: Unknown option: direct.presets while parsing file: /data/www/node_modules/vue-multiselect/lib/vue-multiselect.js
> { [ReferenceError: [BABEL] /data/www/node_modules/vue-multiselect/lib/vue-multiselect.js: Unknown option: direct.presets while parsing file: /data/www/node_modules/vue-multiselect/lib/vue-multiselect.js]
>   filename: '/data/www/node_modules/vue-multiselect/lib/vue-multiselect.js',
>   stream: 
>    Labeled {
>      _readableState: 
>       ReadableState {
>         highWaterMark: 16,
>         buffer: [],
>         length: 0,
>         pipes: [Object],
>         pipesCount: 1,
>         flowing: true,
>         ended: false,
>         endEmitted: false,
>         reading: true,
>         sync: false,
>         needReadable: true,
>         emittedReadable: false,
>         readableListening: false,
>         objectMode: true,
>         defaultEncoding: 'utf8',
>         ranOut: false,
>         awaitDrain: 0,
>         readingMore: false,
>         decoder: null,
>         encoding: null,
>         resumeScheduled: false },
>      readable: true,
>      domain: null,
>      _events: 
>       { end: [Object],
>         error: [Object],
>         data: [Function: ondata],
>         _mutate: [Object] },
>      _eventsCount: 4,
>      _maxListeners: undefined,
>      _writableState: 
>       WritableState {
>         highWaterMark: 16,
>         objectMode: true,
>         needDrain: false,
>         ending: true,
>         ended: true,
>         finished: true,
>         decodeStrings: true,
>         defaultEncoding: 'utf8',
>         length: 0,
>         writing: false,
>         corked: 0,
>         sync: false,
>         bufferProcessing: false,
>         onwrite: [Function],
>         writecb: null,
>         writelen: 0,
>         buffer: [],
>         pendingcb: 0,
>         prefinished: true,
>         errorEmitted: false },
>      writable: true,
>      allowHalfOpen: true,
>      _options: { objectMode: true },
>      _wrapOptions: { objectMode: true },
>      _streams: [ [Object] ],
>      length: 1,
>      label: 'deps' } }

Any advice?

**Comment by shentao** [comment]
Hardly. I’m not a Laravel Elixir user. There were such problems before with this (but with different error messages), so might check out older issues. 

You might also try to upgrade your Babel, as this looks like a Babel error.

**Comment by asvae** [comment]
@dmitov here's my [package.json](http://laravel.io/bin/wJz09). Hope this helps.

**Comment by jpmurray** [comment]
Yeah, I _think_ those are thrown because you might not have included vueify in gulp?

**Comment by shentao** [comment]
Btw. @asvae @jpmurray thanks for helping with the issues!
