### ISSUE TITLE
[Help wanted] Multiple select field with predefined options problem

### ISSUE THREAD

**Issue by jpmurray** [monterail/vue-multiselect#67]
Hello,

I have a page on which I can have a non fixed number of multiselect element. Basically, the "create" version of the page, to create an entry, works flawlessly. But, the "edit" version is causing me some trouble: I assign the value found in the database on the `ready()` method of the page's component (in which the multiselects are).

You can see in the image below what happens:

<img width="247" alt="screen shot 2016-07-26 at 08 48 46" src="https://cloud.githubusercontent.com/assets/1550428/17138428/3e95cd7e-530e-11e6-8366-f53a703c4d24.png">

The last one always works: it's set, and I can select new values. But for all the ones before the value are set, but they are stuck with a loading icon and I can't do anything with them. Trying to search for a new value _seems_ to work (if I `console.log` the search results, they show), but they won't appear in the multiselect search box.

I can recall something like this in the doc, or in issues (was it even myself? hehe), that could help, but I can't seem to be able to find it, so... Any help welcome ! :) 🎱

**Comment by shentao** [comment]
Could you provide some code with the implementation? This would probably help solving this problem.

Also, 1.0 (#57) will introduce breaking changes to both searching and loading (showing spinner). It will be fully controlled from within the parent component.
See line: https://github.com/monterail/vue-multiselect/pull/57/files#diff-08af04817a34c893a1d251cf084c7fefR155, the `_ajax-search.jade` file and `asyncFind` in main.js.

**Comment by jpmurray** [comment]
Sure. Here is part of the code for the parent component that is relevant

```
import Multiselect from 'vue-multiselect'

Vue.component('log-edit', {
    components: {Multiselect},
    
    methods: {
        searchMusic: function(query) {
            this.$http.post('/music/multiselect', {
                search_query: query, // search query
            }).then((response) => {
                var index = this.form.entries.length - 1;
                this.form.entries[index].options = response.data;
            });
        },
        setMusicValue(value)  {
            var index = this.form.entries.length - 1;
            this.form.entries[index].selected = value;
        },
    },
    ready() {
        this.form.entries = this.$root.oldFormValue.entries;
    }
}

```

and here's the multiselect element

```
<multiselect
:selected.sync="form.entries[$index].selected"
:options="form.entries[$index].options"
placeholder="Search for a song title"
:multiple="false"
:show-labels="false"
:on-search-change="searchMusic"
:on-change="setMusicValue"></multiselect>
```

**Comment by shentao** [comment]
Please remove the `.sync` modifier if you use `:on-change`. That might help.

Also, in your promise resolving function, you always update the last entry:
```
var index = this.form.entries.length - 1; // is always the index of the last multiselect
this.form.entries[index].options = response.data;
```
This might be the problem why the spinner is triggered and never ends. After you type into the search box it triggers the spinner and waits for the `:options` to be updated. The `:options` only get updated in the last multiselect.

Also, do you use `track-by` when iterating through entries? It often causes problems with inputs.

**Comment by BakerCo** [comment]
I am having the same issue... except I am using vue-router and returning from the data() multiselect is overwriting the incoming value and setting it to null.

**Comment by shentao** [comment]
```
created () {
    if (!this.selected) {
      this.$set('value', this.multiple ? [] : null)
    } else {
      this.value = deepClone(this.selected)
    }
```

This might cause the issue. I will try to provide a hotfix for it soon.

**Comment by shentao** [comment]
@jpmurray I changed the above code in the v1.0.0 release. Let me know if this helps.

**Comment by jpmurray** [comment]
@shentao I'll be looking at it in the coming days, I've been über busy lately, haven't got a minute yet to actually read all of your replies! ;-)

**Comment by shentao** [comment]
Sure thing!

**Comment by BakerCo** [comment]
I tried with my issue, has the usage changed? `:selected.sync="model"` no longer works for me. the model is no longer bound to the multiselect.

**Comment by shentao** [comment]
@BakerCo Yes, the usage has changed, hence the version change to 1.0.0. Please refer to the updated documentation.

**Comment by jpmurray** [comment]
SO.

I'm sorry, I hardly had to time validate your precious imputs of the last days sooner, but here I am.

Basically, I just followed your comment [over here](https://github.com/monterail/vue-multiselect/issues/67#issuecomment-235623550) while updating to 1.0.1 and it just works. It was probably, like you said, just a matter of what instance I was trying to update. Passing the id attribute makes it work flawlessly.

As per your other questions, even if it doesn't matter anymore because it works (👍) : I was sure I was using `track-by`but it seems I don't so, here's that ;-)

Thanaks again for all of your help. I'm going to have to play with the code a bit more in the coming days, I don't expect any hicups, so I'll close the issue! ;-)

**Comment by shentao** [comment]
Really glad to hear that!

Let me know if there are any other issues with the new release.

Cheers!
