### ISSUE TITLE
Weird IE Edge issue with onChange prop

### ISSUE THREAD

**Issue by dobromir-hristov** [monterail/vue-multiselect#68]
So today I discovered that ONLY on the Microsoft Edge, the multiselect's onChange prop gets called before The parent model's `this.data` has been set.

**What should happen**

`this.searchParams` Should be set as it is set via the data() call on the parent Vue
```js
data () {
   return {
     searchParams: JSON.parse(JSON.stringify(window.vueData.searchParams))
  }
}
```

```html
<multiselect :selected.sync="searchParams.tire_width"
                                             :options="options.dropdowns.tire_width.data"                              
                                             :on-change="setMultiselectValue"
                                ></multiselect>
```
`setMultiselectValue` is used with the `onChange` prop. Here is what I get when I console each value.

```js
setMultiselectValue (newVal){
                console.log(this.searchParams); // My whole Search Params object. It has the right structure, but everything has an empty value.... This is not possible as i have not set it anywhere empty.
                console.log(vueData.searchParams); // This is the JSON that gets returned from my backend, and its all full with the data that it should be.
                console.log(newVal); // This is the EXACT value I am expecting, because it is the same as the one in vueData.searchParams. 
```

How on earth, can Multiselect return its new Value, which is passed by the Selected prop, WHICH is returned from the parent this.searchParams, but at the same time this.searchParams is empty... 

I have no idea if I managed to explain this at all, I will happily do some sort of skype call or what ever, because this occurs ONLY on the Edge ... Every other browser I could try works flawlessly ... And it should...

I cant do a fiddle as this is tightly coupled with my project..

**Comment by shentao** [comment]
Please remove the `.sync` modifier when you use the `:on-change` prop. Otherwise, this might lead to some unexpected problems.

Could you try installing the 1.0 beta version? `npm install vue-multiselect@next`. There will be a small change to the code you have. Ofc other places could break, because this version introduces some breaking changes, but in your code you just have to remove the deprecated `.sync` and change `:on-change` prop to `@update` listener.

```html
<multiselect 
  :selected="searchParams.tire_width"
  :options="options.dropdowns.tire_width.data"                              
  @update="setMultiselectValue"
></multiselect>
```
And also
```javascript
setMultiselectValue (newVal){ 
  this.searchParams.tire_width = newVal
}
```

**Comment by dobromir-hristov** [comment]
Removing the .sync did not help. Gonna try the new branch, give me a moment.

**Comment by dobromir-hristov** [comment]
OK I installed the branch and some of the problems got fixed. For example now on initial load at least the multiselect doesnt fire an event in Edge. 

Works OK on other browsers, but on Edge when I `console.log('this.searchParams')` from the setMultiselectValue I get the same empty objects as before. This is just isnane because I`m debugging atm with firefox and all the values are good. Most strange part is, only the multiselect fields are wiped out, as if it wiped them out before the parent is even ready.

**Comment by dobromir-hristov** [comment]
OK... Problem is lame...
searchParams is v-model binded to an input:text field so I can do a normal submit on the form later on. On Edge, because the initial value of that input is null, it replaces my Main Vue's data with empty strings... 
This is a Vue.js/Edge issue of some sort...

**Comment by shentao** [comment]
Ouch. I was about to go step by step through the multiselect initialization process. 😃 

Well, glad it works now! 
Also thanks for testing out the beta version. How do you like the changes? I would be happy to hear some feedback about the direction of changes.

**Comment by dobromir-hristov** [comment]
Its great, but I want to see more events. For example, when you are finished selecting multiple selects when `multiple:true` then you can have a changed event. 
Not sure if it works like that atm.

**Comment by shentao** [comment]
Hmm, I could provide additional events like `@close` and `@open` that would return the current value of the multiselect. This would probably very useful when `multiple: true` as you wouldn’t need to listen to the `@update` event anymore, but to the `@close` one. The only drawback being – one would first have to close the dropdown to trigger updates.

With the `@open` event it would be possible to make better validations, as this would be basically a signal that the dropdown was touched.

Would that be fine?

**Comment by dobromir-hristov** [comment]
Yes, one would have to close, you dont know if the user is ready selecting before that.

**Comment by dobromir-hristov** [comment]
Should we change the `@update` to a `@change` so it is in unison with normal input events?

**Comment by shentao** [comment]
I believe I’ve tried it, but it has been looking for the native `change` event, which it, of course, couldn’t find. But I will try it again, to make sure if that was true.
