### ISSUE TITLE
Single select vs "press enter to remove"

### ISSUE THREAD

**Issue by msx2** [monterail/vue-multiselect#7]
![screen shot 2016-05-25 at 14 13 28](https://cloud.githubusercontent.com/assets/1129643/15539462/f127a712-2282-11e6-80ae-e24f5d841729.png)
`Press enter to remove` is present there, but does not work 😄  It's a part of documentation page.

**Comment by shentao** [comment]
My bad! There are props for disabling this highlight label (or all labels), but it wasn’t properly set in the documentation.

Will have to change this! Thanks for catching!

**Comment by shentao** [comment]
Fixed in v0.1.5 #10.
Closing
