### ISSUE TITLE
When form (fieldset) is set to 'disabled', the dropdown is still active

### ISSUE THREAD

**Issue by hekigan** [monterail/vue-multiselect#72]
First of all thank you for this component, it's pretty helpful.

My problem is that I want to **disable a whole form** (when submitting via ajax for ex). 
I would put a _disabled_ attribute to a form fieldset, then **all inputs/buttons/etc**... are supposed to be '**readonly**' in that state.

But multiselect is still fully active. For example, when clicking the right arrow, the dropdown is shown.

I looked in the source, but did not see anything related to this.

Any suggestion?

**Comment by shentao** [comment]
Thanks for noticing this!
I’m working on the 1.0 release right now. I will try to introduce this feature right away.

You can try out the current beta with `npm install vue-multiselect@next`.

**Comment by shentao** [comment]
Fixed in v1.0.0
