### ISSUE TITLE
Only thing missing... Grouping?

### ISSUE THREAD

**Issue by eybarta** [monterail/vue-multiselect#73]
Awesome work! thank you. One important feature I'm looking for to
start using this plugin would be grouping, similar to SELECTIZE, etc.. 
where I'd be able to visually split the 'options' in the dropdown
by categories, very important in my specific case.
Any plans on implementing something like this? or maybe it already
is and I completely missed it in the docs..?! 
Thanks

**Comment by shentao** [comment]
Had this in mind (was in the road map before the last change to it). I will probably introduce this feature after the 1.0 release.

**Comment by eybarta** [comment]
Great! I'll be waiting.. :)

**Comment by shentao** [comment]
Btw. You can already try out the 1.0 beta: `npm install vue-multiselect@next`

**Comment by alexjoverm** [comment]
+ 1, this is a most-wanted for me personally

**Comment by shentao** [comment]
Been thinking about this already, but it will require some possible breaking changes to be done together with a remodel of the options list. I don’t have time this week, but next weekend I might try to introduce it.

**Comment by pepf** [comment]
+1 Looking forward to see what you're coming up  with!

**Comment by josepramon** [comment]
+1 on this feature

**Comment by boudydegeer** [comment]
+1 \o/

**Comment by jpmurray** [comment]
Guys, you can use the add reaction button to the original post if you want to +1 something. Just add a 👍 . It'll keep everyone to get notification spammed for each of the +1 comments...

**Comment by davidyao** [comment]
+1 LOL

**Comment by shentao** [comment]
Already working on this feature.
Temporary closing this issue to avoid unnecessary spam.
Reactions are welcome. :)

**Comment by shentao** [comment]
Mostly done, just need to verify if it works in all use cases. Will try to publish it this weekend :)
