### ISSUE TITLE
Version 1.1.0 doesn't work properly

### ISSUE THREAD

**Issue by hootlex** [monterail/vue-multiselect#78]
Congrats on the Version 1!

Though, when using v1.1.0, lib/vue-multiselect.min.js file is 109kb while it should be around 30kb.

Also, when used like the previous versions, it returns the following error and doesn't show any options:

`
[Vue warn]: Failed to resolve partial: multiselectBasicOptionPartial (found in component: <multiselect>)
`

After switching to v1.0.1 the error goes away, and the dropdown works as expected.

**Comment by shentao** [comment]
Thanks a lot for your quick notice!
Sorry everyone! Nightly builds (published after midnight) are never the most stable ones. :/

Already fixed in v1.1.1! Once again thanks!

**Comment by hootlex** [comment]
No problem @shentao :)
