### ISSUE TITLE
Avoid post-filtering

### ISSUE THREAD

**Issue by ignaciovazquez** [monterail/vue-multiselect#79]
Hi!

I'm using vue-multiselect to match a number of options via Ajax (loving it so far!)

Even though we set the options propertly, we found that if the search string typed in the select is not present in the actual "label" property, the field is not displayed.

It looks like vue-multiselect is running additional string matching filters after we set the options.
Is it possible to disable the post filters so we display everything that comes back via Ajax?

Thanks!

**Comment by shentao** [comment]
Right now it’s not possible but I guess I can introduce such prop option soon. Thanks for the idea!

**Comment by shentao** [comment]
Hey @ignaciovazquez!
I added `:local-search` in v1.1.2. Set it to false to omit the local filtering based on search query. This should work fine with results from Ajax calls. :)

**Comment by ignaciovazquez** [comment]
That's great, thanks! I was about to send a PR with the changes, but better if it comes from the source. 

Thanks for the swift response time.

Ignacio

**Comment by shentao** [comment]
No problem! ;)

Found a bug, so I had to publish a patch version anyway.
