### ISSUE TITLE
Documentation: single selects shared value

### ISSUE THREAD

**Issue by msx2** [monterail/vue-multiselect#8]
Is there any reason in particular why the two single select dropdowns share the same values, and respond when you change values in the other one?
Once you select value in `Single select dropdown`, you select the same option from `Single select with search`. And when you remove the option from `Single select with search`, it's also being removed from `Single select dropdown`, even though its own control does not allow that.

**Comment by shentao** [comment]
Those two selects share the same **selected value**. The reason behind such unobvious decision was to test if you could easily control the **selected value** from other sources like Vuex mutations or simply other methods of the parent component.

> And when you remove the option from Single select with search, it's also being removed from Single select dropdown, even though its own control does not allow that.

vue-multiselect doesn’t claim responsibility of how the developer modifies the **selected value** outside of the component. It does, however, keep a copy of the value for internal operations. This way the parent’s passed **selected value** doesn’t change if you provide an `:on-change` callback function. This makes it possible to use with Vuex or Redux, by not mutating the state of the component directly.

**Comment by shentao** [comment]
Fixed in #10. New docs state that the object is shared and why.
Closing! :)
