### ISSUE TITLE
Dynamically resetting select box

### ISSUE THREAD

**Issue by FrizzaUK** [monterail/vue-multiselect#81]
I am trying to reset a select dropdown based on another action on my page.  I have tried setting 'selected' to null but the 'value' of the select still holds the original selected option.  Unless I am missing something is there a way to do this?

Thanks.

**Comment by shentao** [comment]
This should work. We’ve got a watcher on `:selected` prop.
```javascript
'selected' () {
  this.value = deepClone(this.selected)
}
```
What happens if you set the `:selected` prop to for example empty object / empty string / empty array?

**Comment by FrizzaUK** [comment]
If I set 'selected' to an empty object then it resets OK, however if it is set to null then nothing happens.  I can work with that, can't believe I didn't try that!

**Comment by shentao** [comment]
Weird. Maybe it is a problem with the watcher. I will look into it in spare time. 
I hope that you can work with the empty object for now.
