### ISSUE TITLE
HTML Custom Label

### ISSUE THREAD

**Issue by FrizzaUK** [monterail/vue-multiselect#82]
Hi,

Now that you have just added Custom option templates, any chance of allowing the 'customLabel' function to support HTML?

Thanks.

Matt

**Comment by shentao** [comment]
Not yet. This feature will be merged in 2.0 release anyway, as it will be just a customRenderFunction then.

**Comment by FrizzaUK** [comment]
Super, I will wait for version 2.

Good job with the library it is working well :)

**Comment by shentao** [comment]
Glad you like it :)

**Comment by shentao** [comment]
Btw. @FrizzaUK this is already supported in 1.x :)

**Comment by rjcrystal** [comment]
@shentao Can you tell me exactly how can i put HTML in the custom label function, i tried but it just shows html tags as text.

**Comment by rousseauo** [comment]
Is it possible in v2 ? Can't find anything about custom html labels in the documentation.

**Comment by shentao** [comment]
You can use the slot option slot for that.
See example: https://vue-multiselect.js.org/#sub-custom-option-template

**Comment by anant-creator** [comment]
can we use html tag inside Multiselect customLable method?
I wanna add
 import Multiselect from 'vue-multiselect'
	methods:{
		customLabel(listing) {
			return `${listing.name}${listing.publish == 1 ? '' : '<span class="btn danger">(Unpublished)</span>'}`
		},
		activityName ({ name}) {
			return `${name}`
		}
	},

**Comment by ordinov** [comment]
Use the "tag" template slot, instead of customLabel:

`<template slot="tag" slot-scope="props"><span class="option__desc"><div class="anyclass"><b>My HTML</b></div></template>`

https://vue-multiselect.js.org/#sub-custom-option-template
