### ISSUE TITLE
Error on @update

### ISSUE THREAD

**Issue by scrwdnet** [monterail/vue-multiselect#86]
I'm receiving the following error when using the `@update` binding:
`Uncaught TypeError: Cannot read property 'apply' of undefined`

I have the component registered:
```
import Multiselect from 'vue-multiselect';
Vue.component('multiselect', Multiselect);
```

HTML:
```
<multiselect :id="$index" @update="updateSelectOptions" :options="postcodes" :selected="area.postcodes" :multiple="true" :searchable="true" label="postcode" key="id" :max-height="150"></multiselect>
```

The multiselect works perfectly it just gives the error when updating. Not sure if it is something to do with my webpack setup? This is what I can see when looking further into the error (not sure how helpful it is!)
```
(function(scope
/**/) {
return  scope.updateSelectOptions.apply(this,scope.$arguments);
})
```

**Comment by shentao** [comment]
That’s weird. Would you mind trying to register it locally?
Also, where is your `updateSelectOptions` method located?

**Comment by shentao** [comment]
Hey @scrwdnet! I managed to reproduce this problem locally. 
The global component registration doesn’t cause any problems. Uff... :) 

However, the problem happens when the `updateSelectOptions` method isn’t defined on the component, where the multiselect is used. Is the method defined in the same component the `postcodes` data is?

**Comment by scrwdnet** [comment]
Hey @shentao just been looking into this for the past couple of hours, you are right I didn't have the method on the right component it was in a sibling component and I must have had a bad case of code blindness!

Thanks for taking the time to have a look into it for me. Would it be worth adding in a check for the method and throwing an error message if it doesn't exist might help someone in the future who is having a moment of madness!

Thanks again, it's a great component!

**Comment by shentao** [comment]
Haha! It happens to the best of us! :D 

You’re right, but this is more a Vue related issue. Maybe you could suggest adding such error message to Vue?

**Comment by scrwdnet** [comment]
Ahhh ok, yeah I'll bring up an issue and see if they can add something helpful :D
