### ISSUE TITLE
Problem deleting options in multiple scenario

### ISSUE THREAD

**Issue by MaxHalford** [monterail/vue-multiselect#89]
Hello!

I'm pulling with a weird bug. I've instantiated a `Multiselect` component with the multiple attribute set to `True`.

If I select a few options and try to delete an option other than the last, then the last one gets deleted and not the I wanted to delete.

![Example](http://g.recordit.co/tboyHfq8iu.gif)

Is this happening to anyone else? Please tell me if you need to know anything about my setup.

Edit: I'm using version 1.1.2.

**Comment by shentao** [comment]
Does the options array consist of objects? If yes, you have to pass the `key` prop, which will be used to compare the options. The key values have to be unique.
Is this prop present?

**Comment by MaxHalford** [comment]
I feel silly now haha. Thank you very much. You may close the issue :)

**Comment by shentao** [comment]
No problem! 😄 
Glad I could help!
