### ISSUE TITLE
Error while using multiselect with JSX

### ISSUE THREAD

**Issue by voronianski** [monterail/vue-multiselect#90]
I have such an error in my console which breaks the app:

```
this.$options.filters.filterBy is not a function
```

I'm using the component inside JSX render method like:

```js
<Multiselect
  options={this.options}
  selected={this.selected}
  on-update={val => this.selected = val}
  placeholder="Type to search or add tag"
/>
```

**Comment by voronianski** [comment]
https://github.com/vuejs/vue/issues/2756

**Comment by shentao** [comment]
Which version of vue-multiselect are you using? There is a beta version that supports Vue 2.0.
Please `npm install vue-multiselect@next`. It should be working then.
I will add a notice that the 2.0 supporting beta is available. :)

**Comment by voronianski** [comment]
@shentao thanks!
