### ISSUE TITLE
IE11 search bug

### ISSUE THREAD

**Issue by FrizzaUK** [monterail/vue-multiselect#93]
On the 'Single select with search' example:

Click on the dropdown, type in Ra then select using cursor keys and press enter.  The component has selected the correct property but the label remains as the search string ('Ra').

This works fine in Chrome but most of our users use Internet Explorer.

**Comment by restored18** [comment]
I second this issue, I have no problem in Firefox, but in IE 11 the search box will not clear the search string if an item is selected with the enter key.

**Comment by shentao** [comment]
Damn. I honestly hate to fix bugs for IE. However, this sounds quite serious. I’m just not sure if this is just multiselects fault or maybe there is a problem in updating inputs in general. Will try to fix this in the upcoming week finally.

**Comment by shentao** [comment]
Finally published and available in v1.1.3!

**Comment by shentao** [comment]
@restored18 @FrizzaUK 
Finally published and available in v1.1.3! :)
