### ISSUE TITLE
Setting multiselect to display only (no selection possible)

### ISSUE THREAD

**Issue by ropeladder** [monterail/vue-multiselect#95]
First of all, very nice component. Thanks for all your work.

This may be out of the scope of what you are building, but I would love a way to easily render the multiselect as a simple, non-editable list, for example using an "editable" or "displayOnly" property. The "disabled" property comes close, but of course it shows the dropdown arrow, delection 'x's, greys out the items, etc...

**Comment by shentao** [comment]
Hey! Thanks for the kind words.

Do you need a dropdown, that can be opened but the value can not be changed? 
Well, this shouldn’t be much of a problem to implement, as I would have to early return inside the `select` and `remove` methods. This and some additional styles. 
But the priority for this is quite low – first the official 2.0 release.

**Comment by ropeladder** [comment]
Actually I meant without the dropdown, really just an `<li>` for each of the tags with zero interactivity. Of course it's pretty easy to do something like:
```
<ul v-if="!editing">
    <li v-for="tag in taggingSelected">{{tag}}</li>
</ul>
<multiselect v-if="editing" ... ></multiselect>
```
...but for styling consistency and brevity it would be great to have it all within the multiselect component.

**Comment by shentao** [comment]
Hmm, what about just using multiselect’s styles? They are not scoped actually, so you can use them to keep it consistent. 

Consider this example in jade/pug
```jade
    .multiselect.multiselect--active
      .multiselect__tags
        span.multiselect__single Selected
      .multiselect__content
        .multiselect__option(v-for="option in selectedOptions")
          | {{ option.name }}
```

Would that be enough? :)

**Comment by shentao** [comment]
This is already working, just pass `:disabled="true"`.

**Comment by Branksy** [comment]
@shentao :disabled greys out the items however (as @ropeladder points out)
