### ISSUE TITLE
hide-selected not working when selected is Set

### ISSUE THREAD

**Issue by adrianolobo** [monterail/vue-multiselect#98]
The prop :hide-selected does not work then the :selected prop is set. It still shows all the selected options.

**Comment by shentao** [comment]
Are the options objects or primitives? If objects, you need to pass the `key` prop that is used to compare objects.

**Comment by adrianolobo** [comment]
It worked, Thanks :D

**Comment by Xationch** [comment]
@shentao Can you explain how to do that with a exemple? 

```
:options="users"
```

```
users: [
	{ name: 'Jean', id: 1 },
	{ name: 'Louis', id: 2 }
],
```
