### ISSUE TITLE
[Question] How to manually clear select?

### ISSUE THREAD

**Issue by Astray-git** [monterail/vue-multiselect#99]
I have `:selected="null"`
Is there anyway other than `ClearOnSelect `, `resetAfter` to clear the selected value?

**Comment by shentao** [comment]
You should do this manually. For example in the `@update` event handler function.
The current implementation of resetAfter should be changed as it still uses the old `this.$set('selected')`, which leads to two-way binding. Thanks for pointing me to this direction!

**Comment by Astray-git** [comment]
Sorry, may be my description above is not clear.
Say I have a `<multiple-select>` with selections [[1 x][2 x]   ].
As now we don't have two-way binding, how to clear selections from outside of the `<multiple-select>`.?

**Comment by shentao** [comment]
Just change the `:selected` prop value. For example, do `this.selected.splice(0, 1)` to remove the first selected option. The multiselect should update automatically.

**Comment by Astray-git** [comment]
Thanks. I should modify the `this.selected` bind to `:selected` prop in `@update` handler.😄
